import type { ITProizvod, KategorijaProizvoda } from './types';

export const itProizvodi: ITProizvod[] = [
  { id: 'spaja-accelerator', naziv: 'SPAJA Accelerator', opis: 'Ubrzanje performansi svih platformi', ikona: '⚡', kategorija: 'ubrzanje', funkcije: ['CDN optimizacija', 'Edge caching', 'Lazy loading'], ciljnePlatforme: ['ai-iq-super-platforma', 'io-openui-ao'], uticaj: 'visok' },
  { id: 'spaja-turbo', naziv: 'SPAJA Turbo', opis: 'Turbo mode za build procese', ikona: '🔥', kategorija: 'ubrzanje', funkcije: ['Parallel builds', 'Incremental compilation', 'Hot reload'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-optimizer', naziv: 'SPAJA Optimizer', opis: 'Optimizacija resursa i bundle size', ikona: '⚙️', kategorija: 'ubrzanje', funkcije: ['Tree shaking', 'Code splitting', 'Minification'], ciljnePlatforme: ['ai-iq-super-platforma', 'io-openui-ao'], uticaj: 'srednji' },
  { id: 'spaja-monitor', naziv: 'SPAJA Monitor', opis: 'Monitoring svih servisa u realnom vremenu', ikona: '📊', kategorija: 'monitoring', funkcije: ['Real-time dashboards', 'Alerting', 'Anomaly detection'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-logger', naziv: 'SPAJA Logger', opis: 'Centralizovano logovanje i analiza', ikona: '📝', kategorija: 'monitoring', funkcije: ['Structured logging', 'Log aggregation', 'Search'], ciljnePlatforme: ['ai-iq-super-platforma', 'omega-ai-github'], uticaj: 'srednji' },
  { id: 'spaja-shield', naziv: 'SPAJA Shield', opis: 'Bezbednosni stit za sve platforme', ikona: '🛡️', kategorija: 'bezbednost', funkcije: ['WAF', 'DDoS protection', 'Rate limiting'], ciljnePlatforme: ['ai-iq-super-platforma', 'ai-iq-world-bank'], uticaj: 'visok' },
  { id: 'spaja-firewall', naziv: 'SPAJA Firewall', opis: 'Napredni firewall sa AI detekcijom', ikona: '🔒', kategorija: 'bezbednost', funkcije: ['AI threat detection', 'IP filtering', 'Geo-blocking'], ciljnePlatforme: ['ai-iq-world-bank', 'ai-iq-menjacnica'], uticaj: 'visok' },
  { id: 'spaja-crypto', naziv: 'SPAJA Crypto', opis: 'Kriptografski modul za enkripciju', ikona: '🔐', kategorija: 'bezbednost', funkcije: ['E2E encryption', 'Key management', 'Digital signatures'], ciljnePlatforme: ['ai-iq-world-bank', 'ai-iq-menjacnica'], uticaj: 'srednji' },
  { id: 'omega-ai-engine', naziv: 'OMEGA AI Engine', opis: 'Centralni AI engine sa SpajaPro Prompt integracijom', ikona: '🧠', kategorija: 'ai', funkcije: ['SpajaPro Prompt obrada', 'Multi-model support', 'Fine-tuning', 'Inference optimization'], ciljnePlatforme: ['omega-ai-github', 'omega-ai-vercel', 'omega-ai-google'], uticaj: 'visok' },
  { id: 'spajapro-prompt-engine', naziv: 'SpajaPro Prompt Engine', opis: 'SpajaPro 6-15 Prompt engine — zamena za ChatGPT u celom ekosistemu', ikona: '🌟', kategorija: 'ai', funkcije: ['SpajaPro 6-15 verzije', 'Univerzalni Prompt', 'Persona Prompt', 'Platforma Prompt', 'Multi-language Prompt', 'Prompt optimizacija'], ciljnePlatforme: ['ai-iq-super-platforma', 'io-openui-ao', 'omega-ai-github', 'omega-ai-vercel'], uticaj: 'visok' },
  { id: 'spaja-deploy', naziv: 'SPAJA Deploy', opis: 'Automatski deploy na sve platforme', ikona: '🚀', kategorija: 'deploy', funkcije: ['Zero-downtime deploy', 'Rollback', 'Preview environments'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-cicd', naziv: 'SPAJA CI/CD', opis: 'Kontinuirana integracija i isporuka', ikona: '🔄', kategorija: 'deploy', funkcije: ['GitHub Actions', 'Automated testing', 'Pipeline management'], ciljnePlatforme: ['ai-iq-super-platforma', 'io-openui-ao'], uticaj: 'srednji' },
  { id: 'spaja-integrator', naziv: 'SPAJA Integrator', opis: 'Integracija izmedju svih platformi', ikona: '🔗', kategorija: 'integracija', funkcije: ['API gateway', 'Event bus', 'Data sync'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-connector', naziv: 'SPAJA Connector', opis: 'Konektori za eksterne servise', ikona: '🔌', kategorija: 'integracija', funkcije: ['REST connectors', 'GraphQL bridge', 'Webhook management'], ciljnePlatforme: ['ai-iq-super-platforma', 'io-openui-ao'], uticaj: 'srednji' },
  { id: 'spaja-api-gateway', naziv: 'SPAJA API Gateway', opis: 'Centralni API gateway', ikona: '🌐', kategorija: 'integracija', funkcije: ['Rate limiting', 'Authentication', 'Load balancing'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-data-sync', naziv: 'SPAJA Data Sync', opis: 'Sinhronizacija podataka izmedju platformi', ikona: '📡', kategorija: 'podaci', funkcije: ['Real-time sync', 'Conflict resolution', 'Backup'], ciljnePlatforme: ['ai-iq-super-platforma', 'ai-iq-world-bank'], uticaj: 'visok' },
  { id: 'spaja-messenger', naziv: 'SPAJA Messenger', opis: 'Komunikacioni sistem izmedju modula', ikona: '💬', kategorija: 'komunikacija', funkcije: ['Real-time messaging', 'Channels', 'Notifications'], ciljnePlatforme: ['io-openui-ao'], uticaj: 'srednji' },
  { id: 'spaja-metrics', naziv: 'SPAJA Metrics', opis: 'Metrike i KPI pracenje', ikona: '📈', kategorija: 'monitoring', funkcije: ['Custom metrics', 'KPI tracking', 'Reports'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'digitalni-kompjuter', naziv: 'Digitalni Kompjuter', opis: 'SpajaUltraOmegaCore digitalni kompjuter — osnova za pokretanje svih igrica u dimenzionalnom prostoru (360D–5760D). Bez digitalnog kompjutera igrice ne mogu da se pokrenu.', ikona: '🖥️', kategorija: 'ubrzanje', funkcije: ['Dimenzionalno renderovanje 360D–5760D', 'Geometrijsko procesiranje (Elipsoid, Rezonanca, Hiperbola, Spirala)', 'Pokretanje igrica u svim dimenzijama', 'Multi-dimenzionalni GPU za 3D naočare', 'Cirkularna formula kalkulacija'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'digitalni-brauzer', naziv: 'Digitalni Brauzer', opis: 'SpajaUltraOmegaCore digitalni brauzer — neophodan za pristup i pokretanje dimenzionalnih igrica. Renderuje igrice direktno u brauzeru sa podrškom za sve dimenzije.', ikona: '🌐', kategorija: 'ubrzanje', funkcije: ['WebGL/WebGPU dimenzionalno renderovanje', 'Pokretanje igrica u brauzeru', 'Podrška za 3D naočare preko brauzera', 'Dimenzionalni streaming (360D–5760D)', 'Offline igrice sa Service Worker-om'], ciljnePlatforme: ['ai-iq-super-platforma', 'io-openui-ao'], uticaj: 'visok' },
  // ─── Gaming industrija IT proizvodi ─────────────────────────────
  { id: 'spaja-game-engine', naziv: 'SPAJA Game Engine', opis: 'Dimenzionalni game engine za renderovanje igrica u 360D–5760D prostoru. Podržava Elipsoid, Rezonanca, Hiperbola i Spirala geometrije kao osnovu za sve igrice.', ikona: '🎮', kategorija: 'gaming', funkcije: ['Dimenzionalno renderovanje 360D–5760D', 'Geometrijski shader sistem', 'Fizika po cirkularnim formulama', 'Multi-dimenzionalni level editor', 'Real-time lighting po dimenzijama'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-physics-engine', naziv: 'SPAJA Physics Engine', opis: 'Fizički engine koji simulira dimenzionalnu fiziku — gravitacija, kolizija i dinamika se menjaju prema izabranoj dimenziji (D). Elipsoidna kolizija, rezonantna gravitacija, hiperbolička dinamika.', ikona: '⚛️', kategorija: 'gaming', funkcije: ['Elipsoidna kolizija detekcija', 'Rezonantna gravitacija po D', 'Hiperbolička dinamika objekata', 'Spiralna putanja projektila', 'Multi-dimenzionalni ragdoll'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-audio-engine', naziv: 'SPAJA Audio Engine', opis: 'Audio engine za dimenzionalni zvuk — 3D pozicioni audio u svim dimenzijama. Rezonantne frekvencije, elipsoidno prostiranje zvuka, spiralni eho efekti.', ikona: '🔊', kategorija: 'gaming', funkcije: ['3D pozicioni audio po dimenzijama', 'Rezonantne zvučne frekvencije', 'Elipsoidno prostiranje zvuka', 'Spiralni eho i reverb', 'Dinamički soundtrack po D nivou'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-multiplayer-server', naziv: 'SPAJA Multiplayer Server', opis: 'Multiplayer server za dimenzionalne igrice — sinhronizacija igrača između dimenzija u realnom vremenu. Podržava PvP, co-op i masovni multiplayer.', ikona: '👥', kategorija: 'gaming', funkcije: ['Real-time multiplayer sinhronizacija', 'Cross-dimenzionalni matchmaking', 'PvP, Co-op i MMO režimi', 'Anti-lag kompenzacija po D', 'Dimenzionalni lobby sistem'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-anti-cheat', naziv: 'SPAJA Anti-Cheat', opis: 'Anti-cheat sistem za dimenzionalne igrice — detektuje manipulaciju dimenzija, speed hack, wall hack kroz dimenzionalne zidove i eksploataciju cirkularnih formula.', ikona: '🛡️', kategorija: 'gaming', funkcije: ['Dimenzionalna integritet provera', 'Speed hack detekcija po D', 'Wall hack kroz dimenzionalne zidove', 'Formula eksploatacija zaštita', 'Real-time banning sistem'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-streaming-platform', naziv: 'SPAJA Streaming Platform', opis: 'Gaming streaming platforma za prenos igrica u svim dimenzijama. Podrška za live streaming iz 360D do 5760D sa 3D naočarima za gledaoce.', ikona: '📺', kategorija: 'gaming', funkcije: ['Live streaming iz svih dimenzija', '3D stream za gledaoce sa naočarima', 'Chat integracija po dimenzijama', 'Clip i highlight generisanje', 'Streamer overlay za dimenzionalne igrice'], ciljnePlatforme: ['ai-iq-super-platforma', 'io-openui-ao'], uticaj: 'srednji' },
  { id: 'spaja-game-analytics', naziv: 'SPAJA Game Analytics', opis: 'Analitika za dimenzionalne igrice — praćenje igrača, dimenzionalnih performansi, popularnosti dimenzija i balansa igrica.', ikona: '📊', kategorija: 'gaming', funkcije: ['Praćenje igrača po dimenzijama', 'Heatmapa aktivnosti po D', 'Balans analiza između dimenzija', 'Retention i engagement metrike', 'A/B testiranje po dimenzijama'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-vr-ar-engine', naziv: 'SPAJA VR/AR Engine', opis: 'VR i AR engine za dimenzionalne igrice — puna VR podrška za spoljašnje dimenzije (1440D+) sa 3D naočarima, AR overlay za unutrašnje dimenzije.', ikona: '🥽', kategorija: 'gaming', funkcije: ['VR režim za 1440D, 2880D, 5760D', 'AR overlay za 360D, 720D', 'Hand tracking u dimenzijama', 'Haptic feedback po geometrijskim slojevima', '360° dimenzionalni prikaz'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-ai-npc', naziv: 'SPAJA AI NPC Engine', opis: 'AI engine za NPC-ove u dimenzionalnim igricama — NPC-ovi se ponašaju različito u svakoj dimenziji. Koristi OMEGA AI za inteligentno ponašanje i SpajaPro za dijaloge.', ikona: '🤖', kategorija: 'gaming', funkcije: ['OMEGA AI ponašanje NPC-ova', 'SpajaPro generisani dijalozi', 'Dimenzionalno prilagođavanje AI', 'Proceduralne misije i questovi', 'Emotion sistem po D nivou'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-level-generator', naziv: 'SPAJA Level Generator', opis: 'Proceduralni generator nivoa za dimenzionalne igrice — generiše nivoe koristeći cirkularne formule i geometrijske slojeve svake dimenzije.', ikona: '🗺️', kategorija: 'gaming', funkcije: ['Proceduralno generisanje nivoa po D', 'Cirkularne formule za layout', 'Geometrijski slojevi kao teme', 'Infinite level generisanje', 'Seed-based reprodukcija nivoa'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  // ─── Gaming industrija — Prošireni Engine ekosistem ──────────────
  { id: 'spaja-animation-engine', naziv: 'SPAJA Animation Engine', opis: 'Animacioni engine za dimenzionalne igrice — skeletal, blend tree i proceduralne animacije koje se prilagođavaju dimenziji (D). Elipsoidne rotacije, spiralne tranzicije, hiperboličke deformacije.', ikona: '🎭', kategorija: 'gaming', funkcije: ['Skeletal animacija po dimenzijama', 'Blend tree sa geometrijskim prelazima', 'Proceduralne animacije po D', 'IK sistem za dimenzionalna tela', 'Sprite sheet dimenzionalni atlas'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-particle-system', naziv: 'SPAJA Particle System', opis: 'Particle sistem za dimenzionalne efekte — eksplozije, magija, dim, vatra, kiša — svi efekti se menjaju prema dimenziji (D). Elipsoidne čestice, spiralni vorteksi, hiperboličke emisije.', ikona: '✨', kategorija: 'gaming', funkcije: ['Dimenzionalni particle efekti', 'Elipsoidne, Spiralne, Hiperboličke čestice', 'GPU particle za milione čestica', 'Particle collision po D', 'Prilagođeni emitteri po geometrijama'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-terrain-generator', naziv: 'SPAJA Terrain Generator', opis: 'Generator terena za dimenzionalne igrice — proceduralni tereni formirani cirkularnim formulama. Planine, doline, okeani, pustinje — sve se menja prema dimenziji.', ikona: '🏔️', kategorija: 'gaming', funkcije: ['Proceduralni tereni po cirkularnim formulama', 'Dimenzionalni biomi i klimatski sistemi', 'LOD sistem po dimenzijama', 'Voxel i heightmap tereni', 'Real-time teren deformacija'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-weather-system', naziv: 'SPAJA Weather System', opis: 'Vremenski sistem za dimenzionalne igrice — kiša, sneg, oluje, vulkani — svi vremenski fenomeni se ponašaju drugačije u svakoj dimenziji. Rezonantne oluje, spiralni tornadi, elipsoidna kiša.', ikona: '🌦️', kategorija: 'gaming', funkcije: ['Dimenzionalni vremenski efekti', 'Rezonantne oluje i grmljavine', 'Spiralni tornadi i vetrovi', 'Elipsoidna kiša i sneg', 'Dinamički dan/noć ciklus po D'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-networking-sdk', naziv: 'SPAJA Networking SDK', opis: 'Networking SDK za brzu implementaciju multiplayer-a u dimenzionalnim igricama. Podržava P2P, dedicated server, relay — sve optimizovano za cross-dimenzionalnu komunikaciju.', ikona: '🌐', kategorija: 'gaming', funkcije: ['P2P, Dedicated i Relay networking', 'Cross-dimenzionalna sinhronizacija stanja', 'Delta kompresija po D', 'Prediction i reconciliation', 'WebRTC i WebSocket podrška'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-asset-pipeline', naziv: 'SPAJA Asset Pipeline', opis: 'Asset pipeline za automatsku obradu resursa za dimenzionalne igrice — teksture, modeli, zvukovi se automatski optimizuju za svaku dimenziju (D).', ikona: '📦', kategorija: 'gaming', funkcije: ['Automatska optimizacija asseta po D', 'Teksture LOD po dimenzijama', 'Model decimation za niže D', 'Audio kompresija po kvalitetu', 'Streaming asset loading'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-shader-compiler', naziv: 'SPAJA Shader Compiler', opis: 'Shader compiler za dimenzionalne vizualne efekte — kompajlira shadere optimizovane za svaku dimenziju. Geometrijski shaderi, dimenzionalno osvetljenje, spiralni post-processing.', ikona: '🎨', kategorija: 'gaming', funkcije: ['Geometrijski shader jezik', 'Dimenzionalno osvetljenje modeli', 'Spiralni post-processing efekti', 'Cross-platform shader kompilacija', 'Hot reload shader razvoj'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-scene-graph', naziv: 'SPAJA Scene Graph Engine', opis: 'Scene graph za organizaciju dimenzionalnog prostora — hijerarhijska organizacija objekata po dimenzijama sa automatskom culling optimizacijom.', ikona: '🌲', kategorija: 'gaming', funkcije: ['Dimenzionalna hijerarhija objekata', 'Octree/BSP po dimenzijama', 'Frustum culling za svaku D', 'Portal-based rendering', 'Instanced rendering po geometrijama'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-cinematic-engine', naziv: 'SPAJA Cinematic Engine', opis: 'Engine za cinematske sekvence u dimenzionalnim igricama — cutscene editor, kamera kontrola, post-processing — sve prilagođeno dimenzionalnom prostoru.', ikona: '🎬', kategorija: 'gaming', funkcije: ['Cutscene editor po dimenzijama', 'Dimenzionalna kamera kontrola', 'Cinematski post-processing po D', 'Lip sync sa SpajaPro dijalozima', 'Real-time cinematics'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-motion-capture', naziv: 'SPAJA Motion Capture', opis: 'Motion capture sistem za dimenzionalne igrice — snimanje pokreta i konverzija u dimenzionalne animacije. Podržava dimenzionalnu ekstrapolaciju pokreta.', ikona: '🏃', kategorija: 'gaming', funkcije: ['Dimenzionalni motion capture', 'Konverzija pokreta u sve D', 'Face capture za NPC-ove', 'Body tracking za VR', 'Ekstrapolacija pokreta po geometrijama'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-cloud-save', naziv: 'SPAJA Cloud Save', opis: 'Cloud save sistem za dimenzionalne igrice — čuvanje progresa kroz sve dimenzije, cross-platform sync, automatski backup sa dimenzionalnom redundancijom.', ikona: '☁️', kategorija: 'gaming', funkcije: ['Cloud save za sve dimenzije', 'Cross-platform sync progresa', 'Automatski backup po D', 'Dimenzionalna redundancija', 'Offline save sa sync na reconnect'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-mod-support', naziv: 'SPAJA Mod Support Engine', opis: 'Mod support za dimenzionalne igrice — igrači mogu praviti modove koji funkcionišu u svim dimenzijama. SpajaUltraOmegaCore skripting za modere.', ikona: '🔧', kategorija: 'gaming', funkcije: ['SpajaUltraOmegaCore modding API', 'Steam Workshop stil integracija', 'Mod kompatibilnost po dimenzijama', 'Sandboxed mod izvršavanje', 'Mod ranking i recenzije'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-procedural-music', naziv: 'SPAJA Procedural Music', opis: 'Proceduralni muzički engine za dimenzionalne igrice — generiše muziku u realnom vremenu baziranu na rezonantnim frekvencijama svake dimenzije.', ikona: '🎼', kategorija: 'gaming', funkcije: ['Proceduralna muzika po D frekvencijama', 'Rezonantni harmonski generator', 'Adaptivni soundtrack na gameplay', 'Spiralne melodije i ritmovi', 'Dinamički mixing po dimenzijama'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-destructible-env', naziv: 'SPAJA Destructible Environment', opis: 'Sistem destruktivnog okruženja za dimenzionalne igrice — sve se može uništiti i svaka dimenzija ima drugačiju fiziku uništavanja.', ikona: '💥', kategorija: 'gaming', funkcije: ['Dimenzionalna destrukcija objekata', 'Fizika krhotina po D', 'Elipsoidno raspadanje struktura', 'Rezonantni šokovi uništavanja', 'Spiralno rasipanje fragmenata'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-character-customizer', naziv: 'SPAJA Character Customizer', opis: 'Sistem za prilagođavanje likova u dimenzionalnim igricama — svaka dimenzija ima drugačije opcije za prilagođavanje. Geometrijske forme utiču na izgled.', ikona: '👤', kategorija: 'gaming', funkcije: ['Dimenzionalno prilagođavanje lika', 'Geometrijske forme kao stilovi', 'Dinamička promena po D', 'Proceduralna generacija lica', 'Outfit sistem po dimenzijama'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-quest-engine', naziv: 'SPAJA Quest Engine', opis: 'Quest engine za dimenzionalne igrice — proceduralno generisanje misija, questova i izazova koristeći OMEGA AI i cirkularne formule.', ikona: '📜', kategorija: 'gaming', funkcije: ['OMEGA AI proceduralni questovi', 'Cirkularne formule za quest logiku', 'Branching dijalozi sa SpajaPro', 'Dimenzionalni quest tracker', 'Dynamic difficulty po D'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-inventory-system', naziv: 'SPAJA Inventory System', opis: 'Sistem inventara za dimenzionalne igrice — predmeti imaju različite osobine u različitim dimenzijama. Cross-dimenzionalno skladištenje i trgovina.', ikona: '🎒', kategorija: 'gaming', funkcije: ['Dimenzionalni predmeti sa D osobinama', 'Cross-dimenzionalno skladištenje', 'Craftanje sa geometrijskim materijalima', 'Predmet evolucija po dimenzijama', 'Drag-and-drop UI po D'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-crafting-engine', naziv: 'SPAJA Crafting Engine', opis: 'Crafting engine za dimenzionalne igrice — recepti se formiraju cirkularnim formulama. Kombinovanje geometrijskih materijala u svim dimenzijama.', ikona: '⚒️', kategorija: 'gaming', funkcije: ['Recepti po cirkularnim formulama', 'Geometrijski materijali za craftanje', 'Dimenzionalni radni sto', 'Proceduralni recepti sa AI', 'Blueprint sistem po D'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-achievement-system', naziv: 'SPAJA Achievement System', opis: 'Achievement sistem za dimenzionalne igrice — postignuća se otključavaju po dimenzijama. Cross-igrica achievements za ceo gaming ekosistem.', ikona: '🏅', kategorija: 'gaming', funkcije: ['Dimenzionalna postignuća po D', 'Cross-igrica achievement tracking', 'Achievement showcase profil', 'Rare achievement statistika', 'Leaderboard integracija'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-leaderboard-server', naziv: 'SPAJA Leaderboard Server', opis: 'Leaderboard server za dimenzionalne igrice — rangiranje po dimenzijama, kategorijama i igricama. Real-time ažuriranje sa anti-cheat integracijom.', ikona: '📊', kategorija: 'gaming', funkcije: ['Real-time leaderboard po dimenzijama', 'Globalno i regionalno rangiranje', 'Anti-cheat integracija za fair play', 'Sezonski leaderboardi po D', 'Dimenzionalni ELO sistem'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-replay-system', naziv: 'SPAJA Replay System', opis: 'Replay sistem za dimenzionalne igrice — snimanje i reprodukcija gameplay-a u svim dimenzijama. Kill cam, highlight reel, slow motion u dimenzijama.', ikona: '⏪', kategorija: 'gaming', funkcije: ['Gameplay snimanje po dimenzijama', 'Kill cam i highlight generator', 'Slow motion u dimenzionalnom prostoru', 'Replay sharing sa zajednicom', 'Cinematic replay režim'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-map-editor', naziv: 'SPAJA Map Editor', opis: 'Map editor za dimenzionalne igrice — vizuelni editor za kreiranje mapa u svim dimenzijama. Zajednička kreacija, deljenje mapa, rangiranje.', ikona: '🗺️', kategorija: 'gaming', funkcije: ['Vizuelni map editor po dimenzijama', 'Drag-and-drop geometrijski objekti', 'Zajednička kreacija mapa', 'Map ranking i showcase', 'Import/export po D formatima'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-ai-director', naziv: 'SPAJA AI Director', opis: 'AI Director za dimenzionalne igrice — dinamički prilagođava težinu, tempo i sadržaj igre prema igraču koristeći OMEGA AI. Left 4 Dead stil ali za sve dimenzije.', ikona: '🎯', kategorija: 'gaming', funkcije: ['OMEGA AI dinamička težina', 'Dimenzionalno prilagođavanje tempa', 'Proceduralni eventi po D', 'Igrač profiling sa AI', 'Adaptivni spawn sistem'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-localization-engine', naziv: 'SPAJA Localization Engine', opis: 'Lokalizacioni engine za dimenzionalne igrice — automatska lokalizacija sa SpajaPro u sve jezike. Dimenzionalni kontekst za precizne prevode.', ikona: '🌍', kategorija: 'gaming', funkcije: ['SpajaPro automatska lokalizacija', 'Kontekstualni prevodi po D', 'RTL i CJK podrška', 'Voice-over lokalizacija', 'A/B testiranje prevoda'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-input-system', naziv: 'SPAJA Input System', opis: 'Univerzalni input sistem za dimenzionalne igrice — tastatura, miš, gamepad, touch, VR kontroleri, motion kontroleri — sve prilagođeno dimenzijama.', ikona: '🎮', kategorija: 'gaming', funkcije: ['Multi-platform input handling', 'VR kontroler mapiranje po D', 'Gamepad vibracioni feedback', 'Touch kontrole za mobilni', 'Custom input mapiranje po igricama'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-ui-toolkit', naziv: 'SPAJA Gaming UI Toolkit', opis: 'UI toolkit za dimenzionalne igrice — HUD, menije, inventar, minimap — sve se prilagođava dimenziji. Responsivni UI za sve platforme.', ikona: '🖼️', kategorija: 'gaming', funkcije: ['Dimenzionalni HUD po D', 'Responsivni gaming menije', 'Minimap po dimenzijama', 'Inventory UI komponente', 'Health bar i status efekti'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  // ─── SPAJA Generator za Endžine ───────────────────────────────────
  { id: 'spaja-generator-engine', naziv: 'SPAJA Generator za Endžine', opis: 'SPAJA Generator za Endžine — engine generator koji prevlači engine-e preko celog repozitorijuma AI-IQ-SUPER-PLATFORMA. Generiše, primenjuje i optimizuje sve engine-e u ekosistemu. Link: https://chatgpt.com/c/697aae0b-4984-8385-a9b6-1e762b39d7de', ikona: '🔧', kategorija: 'ai', funkcije: ['Generisanje engine-a za sve module', 'Prevlačenje preko celog repozitorijuma', 'Optimizacija svih engine-a', 'SpajaPro/OMEGA AI/Proksi integracija', 'Gaming i Finansijski engine generisanje', '100% pokrivenost repozitorijuma'], ciljnePlatforme: ['ai-iq-super-platforma', 'io-openui-ao', 'omega-ai-github', 'spajapro-platforma'], uticaj: 'visok' },
];

export function getProizvodiPoKategoriji(kategorija: KategorijaProizvoda): ITProizvod[] {
  return itProizvodi.filter((p) => p.kategorija === kategorija);
}

export function getBrojPoKategoriji(): Record<string, number> {
  return itProizvodi.reduce<Record<string, number>>((acc, p) => {
    acc[p.kategorija] = (acc[p.kategorija] ?? 0) + 1;
    return acc;
  }, {});
}

export function getProizvodiVisokogUticaja(): ITProizvod[] {
  return itProizvodi.filter((p) => p.uticaj === 'visok');
}
