import type { ITProizvod, KategorijaProizvoda } from './types';

export const itProizvodi: ITProizvod[] = [
  { id: 'spaja-accelerator', naziv: 'SPAJA Accelerator', opis: 'Ubrzanje performansi svih platformi', ikona: '⚡', kategorija: 'ubrzanje', funkcije: ['CDN optimizacija', 'Edge caching', 'Lazy loading'], ciljnePlatforme: ['ai-iq-super-platforma', 'io-openui-ao'], uticaj: 'visok' },
  { id: 'spaja-turbo', naziv: 'SPAJA Turbo', opis: 'Turbo mode za build procese', ikona: '🔥', kategorija: 'ubrzanje', funkcije: ['Parallel builds', 'Incremental compilation', 'Hot reload'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-optimizer', naziv: 'SPAJA Optimizer', opis: 'Optimizacija resursa i bundle size', ikona: '⚙️', kategorija: 'ubrzanje', funkcije: ['Tree shaking', 'Code splitting', 'Minification'], ciljnePlatforme: ['ai-iq-super-platforma', 'io-openui-ao'], uticaj: 'srednji' },
  { id: 'spaja-monitor', naziv: 'SPAJA Monitor', opis: 'Monitoring svih servisa u realnom vremenu', ikona: '📊', kategorija: 'monitoring', funkcije: ['Real-time dashboards', 'Alerting', 'Anomaly detection'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-logger', naziv: 'SPAJA Logger', opis: 'Centralizovano logovanje i analiza', ikona: '📝', kategorija: 'monitoring', funkcije: ['Structured logging', 'Log aggregation', 'Search'], ciljnePlatforme: ['ai-iq-super-platforma', 'omega-ai-github'], uticaj: 'srednji' },
  { id: 'spaja-shield', naziv: 'SPAJA Shield', opis: 'Bezbednosni stit za sve platforme', ikona: '🛡️', kategorija: 'bezbednost', funkcije: ['WAF', 'DDoS protection', 'Rate limiting'], ciljnePlatforme: ['ai-iq-super-platforma', 'ai-iq-world-bank'], uticaj: 'visok' },
  { id: 'spaja-firewall', naziv: 'SPAJA Firewall', opis: 'Napredni firewall sa AI detekcijom', ikona: '🔒', kategorija: 'bezbednost', funkcije: ['AI threat detection', 'IP filtering', 'Geo-blocking'], ciljnePlatforme: ['ai-iq-world-bank', 'ai-iq-menjacnica'], uticaj: 'visok' },
  { id: 'spaja-crypto', naziv: 'SPAJA Crypto', opis: 'Kriptografski modul za enkripciju', ikona: '🔐', kategorija: 'bezbednost', funkcije: ['E2E encryption', 'Key management', 'Digital signatures'], ciljnePlatforme: ['ai-iq-world-bank', 'ai-iq-menjacnica'], uticaj: 'srednji' },
  { id: 'omega-ai-engine', naziv: 'OMEGA AI Engine', opis: 'Centralni AI engine sa SpajaPro Prompt integracijom', ikona: '🧠', kategorija: 'ai', funkcije: ['SpajaPro Prompt obrada', 'Multi-model support', 'Fine-tuning', 'Inference optimization'], ciljnePlatforme: ['omega-ai-github', 'omega-ai-vercel', 'omega-ai-google'], uticaj: 'visok' },
  { id: 'spajapro-prompt-engine', naziv: 'SpajaPro Prompt Engine', opis: 'SpajaPro 6-15 Prompt engine — zamena za ChatGPT u celom ekosistemu', ikona: '🌟', kategorija: 'ai', funkcije: ['SpajaPro 6-15 verzije', 'Univerzalni Prompt', 'Persona Prompt', 'Platforma Prompt', 'Multi-language Prompt', 'Prompt optimizacija'], ciljnePlatforme: ['ai-iq-super-platforma', 'io-openui-ao', 'omega-ai-github', 'omega-ai-vercel'], uticaj: 'visok' },
  { id: 'spaja-deploy', naziv: 'SPAJA Deploy', opis: 'Automatski deploy na sve platforme', ikona: '🚀', kategorija: 'deploy', funkcije: ['Zero-downtime deploy', 'Rollback', 'Preview environments'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-cicd', naziv: 'SPAJA CI/CD', opis: 'Kontinuirana integracija i isporuka', ikona: '🔄', kategorija: 'deploy', funkcije: ['GitHub Actions', 'Automated testing', 'Pipeline management'], ciljnePlatforme: ['ai-iq-super-platforma', 'io-openui-ao'], uticaj: 'srednji' },
  { id: 'spaja-integrator', naziv: 'SPAJA Integrator', opis: 'Integracija izmedju svih platformi', ikona: '🔗', kategorija: 'integracija', funkcije: ['API gateway', 'Event bus', 'Data sync'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-connector', naziv: 'SPAJA Connector', opis: 'Konektori za eksterne servise', ikona: '🔌', kategorija: 'integracija', funkcije: ['REST connectors', 'GraphQL bridge', 'Webhook management'], ciljnePlatforme: ['ai-iq-super-platforma', 'io-openui-ao'], uticaj: 'srednji' },
  { id: 'spaja-api-gateway', naziv: 'SPAJA API Gateway', opis: 'Centralni API gateway', ikona: '🌐', kategorija: 'integracija', funkcije: ['Rate limiting', 'Authentication', 'Load balancing'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-data-sync', naziv: 'SPAJA Data Sync', opis: 'Sinhronizacija podataka izmedju platformi', ikona: '📡', kategorija: 'podaci', funkcije: ['Real-time sync', 'Conflict resolution', 'Backup'], ciljnePlatforme: ['ai-iq-super-platforma', 'ai-iq-world-bank'], uticaj: 'visok' },
  { id: 'spaja-messenger', naziv: 'SPAJA Messenger', opis: 'Komunikacioni sistem izmedju modula', ikona: '💬', kategorija: 'komunikacija', funkcije: ['Real-time messaging', 'Channels', 'Notifications'], ciljnePlatforme: ['io-openui-ao'], uticaj: 'srednji' },
  { id: 'spaja-metrics', naziv: 'SPAJA Metrics', opis: 'Metrike i KPI pracenje', ikona: '📈', kategorija: 'monitoring', funkcije: ['Custom metrics', 'KPI tracking', 'Reports'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'digitalni-kompjuter', naziv: 'Digitalni Kompjuter', opis: 'SpajaUltraOmegaCore digitalni kompjuter — osnova za pokretanje svih igrica u dimenzionalnom prostoru (360D–5760D). Bez digitalnog kompjutera igrice ne mogu da se pokrenu.', ikona: '🖥️', kategorija: 'ubrzanje', funkcije: ['Dimenzionalno renderovanje 360D–5760D', 'Geometrijsko procesiranje (Elipsoid, Rezonanca, Hiperbola, Spirala)', 'Pokretanje igrica u svim dimenzijama', 'Multi-dimenzionalni GPU za 3D naočare', 'Cirkularna formula kalkulacija'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'digitalni-brauzer', naziv: 'Digitalni Brauzer', opis: 'SpajaUltraOmegaCore digitalni brauzer — neophodan za pristup i pokretanje dimenzionalnih igrica. Renderuje igrice direktno u brauzeru sa podrškom za sve dimenzije.', ikona: '🌐', kategorija: 'ubrzanje', funkcije: ['WebGL/WebGPU dimenzionalno renderovanje', 'Pokretanje igrica u brauzeru', 'Podrška za 3D naočare preko brauzera', 'Dimenzionalni streaming (360D–5760D)', 'Offline igrice sa Service Worker-om'], ciljnePlatforme: ['ai-iq-super-platforma', 'io-openui-ao'], uticaj: 'visok' },
  // ─── Gaming industrija IT proizvodi ─────────────────────────────
  { id: 'spaja-game-engine', naziv: 'SPAJA Game Engine', opis: 'Dimenzionalni game engine za renderovanje igrica u 360D–5760D prostoru. Podržava Elipsoid, Rezonanca, Hiperbola i Spirala geometrije kao osnovu za sve igrice.', ikona: '🎮', kategorija: 'gaming', funkcije: ['Dimenzionalno renderovanje 360D–5760D', 'Geometrijski shader sistem', 'Fizika po cirkularnim formulama', 'Multi-dimenzionalni level editor', 'Real-time lighting po dimenzijama'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-physics-engine', naziv: 'SPAJA Physics Engine', opis: 'Fizički engine koji simulira dimenzionalnu fiziku — gravitacija, kolizija i dinamika se menjaju prema izabranoj dimenziji (D). Elipsoidna kolizija, rezonantna gravitacija, hiperbolička dinamika.', ikona: '⚛️', kategorija: 'gaming', funkcije: ['Elipsoidna kolizija detekcija', 'Rezonantna gravitacija po D', 'Hiperbolička dinamika objekata', 'Spiralna putanja projektila', 'Multi-dimenzionalni ragdoll'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-audio-engine', naziv: 'SPAJA Audio Engine', opis: 'Audio engine za dimenzionalni zvuk — 3D pozicioni audio u svim dimenzijama. Rezonantne frekvencije, elipsoidno prostiranje zvuka, spiralni eho efekti.', ikona: '🔊', kategorija: 'gaming', funkcije: ['3D pozicioni audio po dimenzijama', 'Rezonantne zvučne frekvencije', 'Elipsoidno prostiranje zvuka', 'Spiralni eho i reverb', 'Dinamički soundtrack po D nivou'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-multiplayer-server', naziv: 'SPAJA Multiplayer Server', opis: 'Multiplayer server za dimenzionalne igrice — sinhronizacija igrača između dimenzija u realnom vremenu. Podržava PvP, co-op i masovni multiplayer.', ikona: '👥', kategorija: 'gaming', funkcije: ['Real-time multiplayer sinhronizacija', 'Cross-dimenzionalni matchmaking', 'PvP, Co-op i MMO režimi', 'Anti-lag kompenzacija po D', 'Dimenzionalni lobby sistem'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-anti-cheat', naziv: 'SPAJA Anti-Cheat', opis: 'Anti-cheat sistem za dimenzionalne igrice — detektuje manipulaciju dimenzija, speed hack, wall hack kroz dimenzionalne zidove i eksploataciju cirkularnih formula.', ikona: '🛡️', kategorija: 'gaming', funkcije: ['Dimenzionalna integritet provera', 'Speed hack detekcija po D', 'Wall hack kroz dimenzionalne zidove', 'Formula eksploatacija zaštita', 'Real-time banning sistem'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-streaming-platform', naziv: 'SPAJA Streaming Platform', opis: 'Gaming streaming platforma za prenos igrica u svim dimenzijama. Podrška za live streaming iz 360D do 5760D sa 3D naočarima za gledaoce.', ikona: '📺', kategorija: 'gaming', funkcije: ['Live streaming iz svih dimenzija', '3D stream za gledaoce sa naočarima', 'Chat integracija po dimenzijama', 'Clip i highlight generisanje', 'Streamer overlay za dimenzionalne igrice'], ciljnePlatforme: ['ai-iq-super-platforma', 'io-openui-ao'], uticaj: 'srednji' },
  { id: 'spaja-game-analytics', naziv: 'SPAJA Game Analytics', opis: 'Analitika za dimenzionalne igrice — praćenje igrača, dimenzionalnih performansi, popularnosti dimenzija i balansa igrica.', ikona: '📊', kategorija: 'gaming', funkcije: ['Praćenje igrača po dimenzijama', 'Heatmapa aktivnosti po D', 'Balans analiza između dimenzija', 'Retention i engagement metrike', 'A/B testiranje po dimenzijama'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
  { id: 'spaja-vr-ar-engine', naziv: 'SPAJA VR/AR Engine', opis: 'VR i AR engine za dimenzionalne igrice — puna VR podrška za spoljašnje dimenzije (1440D+) sa 3D naočarima, AR overlay za unutrašnje dimenzije.', ikona: '🥽', kategorija: 'gaming', funkcije: ['VR režim za 1440D, 2880D, 5760D', 'AR overlay za 360D, 720D', 'Hand tracking u dimenzijama', 'Haptic feedback po geometrijskim slojevima', '360° dimenzionalni prikaz'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-ai-npc', naziv: 'SPAJA AI NPC Engine', opis: 'AI engine za NPC-ove u dimenzionalnim igricama — NPC-ovi se ponašaju različito u svakoj dimenziji. Koristi OMEGA AI za inteligentno ponašanje i SpajaPro za dijaloge.', ikona: '🤖', kategorija: 'gaming', funkcije: ['OMEGA AI ponašanje NPC-ova', 'SpajaPro generisani dijalozi', 'Dimenzionalno prilagođavanje AI', 'Proceduralne misije i questovi', 'Emotion sistem po D nivou'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'visok' },
  { id: 'spaja-level-generator', naziv: 'SPAJA Level Generator', opis: 'Proceduralni generator nivoa za dimenzionalne igrice — generiše nivoe koristeći cirkularne formule i geometrijske slojeve svake dimenzije.', ikona: '🗺️', kategorija: 'gaming', funkcije: ['Proceduralno generisanje nivoa po D', 'Cirkularne formule za layout', 'Geometrijski slojevi kao teme', 'Infinite level generisanje', 'Seed-based reprodukcija nivoa'], ciljnePlatforme: ['ai-iq-super-platforma'], uticaj: 'srednji' },
];

export function getProizvodiPoKategoriji(kategorija: KategorijaProizvoda): ITProizvod[] {
  return itProizvodi.filter((p) => p.kategorija === kategorija);
}

export function getBrojPoKategoriji(): Record<string, number> {
  return itProizvodi.reduce<Record<string, number>>((acc, p) => {
    acc[p.kategorija] = (acc[p.kategorija] ?? 0) + 1;
    return acc;
  }, {});
}

export function getProizvodiVisokogUticaja(): ITProizvod[] {
  return itProizvodi.filter((p) => p.uticaj === 'visok');
}
