import type { NavItem } from './types';

export const navigation: NavItem[] = [
  { label: 'Početna', href: '/', icon: '🏠', description: 'Digitalna Industrija — pregled' },
  { label: 'Dashboard', href: '/dashboard', icon: '📊', description: 'Statistika i stanje ekosistema' },
  { label: 'Industrija', href: '/industrija', icon: '🏭', description: 'O digitalnoj industriji' },
  { label: 'Platforme', href: '/platforme', icon: '🧩', description: 'Sve platforme u ekosistemu' },
  { label: 'Organizacije', href: '/organizacije', icon: '🏢', description: 'Organizaciona struktura' },
  { label: 'Kompanije', href: '/kompanije', icon: '🏛️', description: 'Kompanije u ekosistemu' },
  { label: 'Proizvodi (EN)', href: '/proizvodi', icon: '📦', description: 'IT proizvodi i alati (engleski prikaz)' },
  { label: 'IT Proizvodi', href: '/it-proizvodi', icon: '⚙️', description: 'Svi IT proizvodi digitalne industrije' },
  { label: 'OMEGA AI', href: '/omega-ai', icon: '🧠', description: '21 OMEGA AI persona u 8 oktava' },
  { label: 'SpajaPro', href: '/spaja-pro', icon: '🚀', description: 'SpajaPro Engine verzije 6-15' },
  { label: 'Prompt', href: '/prompt', icon: '💬', description: 'Prompt sistem sa 28 promptova' },
  { label: 'Igrice', href: '/igrice', icon: '🎮', description: '95 igrica u 18 kategorija' },
  { label: 'Dimenzije', href: '/dimenzije', icon: '🌀', description: 'Dimenzionalni sistem 360D-5760D' },
  { label: 'Proksi', href: '/proksi', icon: '📡', description: 'Proksi mreža i signali' },
  { label: 'Mobilna Mreža', href: '/mobilna-mreza', icon: '📱', description: 'SPAJA Mobilna Mreža sa 4 centrale' },
  { label: 'Ekosistem', href: '/ekosistem', icon: '🌐', description: 'Celokupan pregled ekosistema' },
  { label: 'Deploy', href: '/deploy', icon: '🚀', description: 'Status deploy-a platformi' },
  { label: 'Auto-Popravka', href: '/auto-popravka', icon: '🔧', description: 'Autonomni sistem za popravku' },
  { label: 'AI Platforma', href: '/ai-platforma', icon: '🤖', description: 'AI platforma i modeli' },
  { label: 'Banka', href: '/banka', icon: '🏦', description: 'SPAJA Banka platforma' },
  { label: 'Menjačnica', href: '/menjacnica', icon: '💱', description: 'SPAJA Menjačnica platforma' },
  { label: 'Kompanija SPAJA', href: '/kompanija', icon: '🏗️', description: 'O matičnoj kompaniji SPAJA' },
  { label: 'Organizacija SPAJA', href: '/organizacija', icon: '🏛️', description: 'Interna organizaciona struktura SPAJA' },
  { label: 'Proksi GitHub', href: '/proksi-github-deploy', icon: '🐙', description: 'Proksi GitHub Deploy sistem' },
  { label: 'WiFi Antena', href: '/proksi-wifi-antena', icon: '📶', description: 'Proksi WiFi Antena sistem' },
  { label: 'SPAJA Prompt', href: '/spaja-univerzalni-prompt', icon: '🎯', description: 'SPAJA Univerzalni Prompt' },
  { label: 'Generator Endžina', href: '/spaja-generator-engine', icon: '🔧', description: 'SPAJA Generator za Endžine — engine generator' },
  { label: 'Digitalni Brouvzer', href: '/spaja-digitalni-brouvzer', icon: '🌐', description: 'SPAJA Digitalni Brouvzer — brauzer platforma za industriju' },
  { label: 'Laboratorija', href: '/io-openui-ao-laboratorija', icon: '🔬', description: 'IOOpenUIAO Laboratorija za Simulacije' },
  { label: 'Render Medija', href: '/spaja-render-medija', icon: '🎬', description: 'SPAJA Render za Slike i Video' },
  { label: 'Gaming Platforma', href: '/io-openui-ao-gaming-platforma', icon: '🎮', description: 'IO/OPENUI/AO Gaming — SPAJA Univerzalni Endžin nad 95 igrica (www.ioopenuiao.ac)' },
];
