import type { NavItem } from './types';

export const navigation: NavItem[] = [
  { label: 'Početna', href: '/', icon: '🏠', description: 'Digitalna Industrija — pregled' },
  { label: 'Dashboard', href: '/dashboard', icon: '📊', description: 'Statistika i stanje ekosistema' },
  { label: 'Industrija', href: '/industrija', icon: '🏭', description: 'O digitalnoj industriji' },
  { label: 'Platforme', href: '/platforme', icon: '🧩', description: 'Sve platforme u ekosistemu' },
  { label: 'Palasterizacija', href: '/palasterizacija', icon: '🧱', description: 'Novi modul za standardizaciju i stabilizaciju procesa' },
  { label: 'Perkolizonik', href: '/perkolizonik', icon: '⚙️', description: 'Operativni modul za stabilizaciju tokova, kapaciteta i latencije sistema' },
  { label: 'Polimerzacija', href: '/polimerzacija', icon: '🧬', description: 'Lančano vezivanje i kohezija procesnih jedinica' },
  { label: 'Polimerizacija 2', href: '/polimerizacija-2', icon: '🧬', description: 'V2 prošireni katalog lanaca, scan istorija i trendovi' },
  { label: 'Harmonizacija', href: '/harmonizacija', icon: '🎵', description: 'Sinhronizacija procesnih slojeva i optimizacija protoka podataka' },
  { label: 'Kristalizacija', href: '/kristalizacija', icon: '💎', description: 'Stabilizacija procesnog jezgra i purifikacija izlaznih tokova' },
  { label: 'Vektorizacija', href: '/vektorizacija', icon: '📐', description: 'Transformacija procesnog prostora i projekcija multi-dimenzionalnih entiteta' },
  { label: 'Sintetizacija', href: '/sintetizacija', icon: '🔬', description: 'Sinteza i integracija procesnih entiteta u koherentne strukture' },
  { label: 'Rezonancija', href: '/rezonancija', icon: '🎛️', description: 'Usklađivanje frekvencija i stabilizacija oscilatornih tokova' },
  { label: 'Modulacija', href: '/modulacija', icon: '📡', description: 'Adaptivno kodovanje signala i višekanalni prenosni tokovi' },
  { label: 'Demodulacija', href: '/demodulacija', icon: '📶', description: 'Rekonstrukcija modulisanih tokova i verifikacija kvaliteta izlaza' },
  { label: 'Eksosistzdacija', href: '/eksosistzdacija', icon: '🧩', description: 'Modul za povezivanje i konsolidaciju ekosistemskih tokova' },
  { label: 'Organizacije', href: '/organizacije', icon: '🏢', description: 'Organizaciona struktura' },
  { label: 'Kompanije', href: '/kompanije', icon: '🏛️', description: 'Kompanije u ekosistemu' },
  { label: 'Proizvodi (EN)', href: '/proizvodi', icon: '📦', description: 'IT proizvodi i alati (engleski prikaz)' },
  { label: 'IT Proizvodi', href: '/it-proizvodi', icon: '⚙️', description: 'Svi IT proizvodi digitalne industrije' },
  { label: 'Ekslatacija Proizvoda', href: '/ekslatacija-proizvoda', icon: '💸', description: 'Komercijalni lifecycle IT proizvoda — faze, modeli, kanali i potencijal prihoda' },
  { label: 'OMEGA AI', href: '/omega-ai', icon: '🧠', description: '21 OMEGA AI persona u 8 oktava' },
  { label: 'SpajaPro', href: '/spaja-pro', icon: '🚀', description: 'SpajaPro Engine verzije 6-15' },
  { label: 'Story of Life', href: '/story-of-life', icon: '📖', description: 'Narativ evolucije i životnog ciklusa AI IQ SUPER PLATFORMA sistema' },
  { label: 'Prompt', href: '/prompt', icon: '💬', description: 'Prompt sistem sa 28 promptova' },
  { label: 'Igrice', href: '/igrice', icon: '🎮', description: '97 igrica u 18 kategorija' },
  { label: 'Gejming Industrija', href: '/gejming-industrija', icon: '🕹️', description: 'Nad-sloj gejming industrije — katalog, lifecycle, creation pipeline i distribucija' },
  { label: 'Gejming Likovi', href: '/gejming-likovi', icon: '🎭', description: 'Industrija gejming likova — dizajn likova, objekata, subjekata i svega što postoji za igrice' },
  { label: 'Dimenzije', href: '/dimenzije', icon: '🌀', description: 'Dimenzionalni sistem 360D-5760D' },
  { label: 'Proksi', href: '/proksi', icon: '📡', description: 'Proksi mreža i signali' },
  { label: 'Mobilna Mreža', href: '/mobilna-mreza', icon: '📱', description: 'SPAJA Mobilna Mreža sa 4 centrale' },
  { label: 'Call Centar', href: '/call-centar', icon: '📞', description: 'Moblini SPAJA licence, digitalne usluge i dodela paketa' },
  { label: 'Ekosistem', href: '/ekosistem', icon: '🌐', description: 'Celokupan pregled ekosistema' },
  { label: 'Deploy', href: '/deploy', icon: '🚀', description: 'Status deploy-a platformi' },
  { label: 'Auto-Popravka', href: '/auto-popravka', icon: '🔧', description: 'Autonomni sistem za popravku' },
  { label: 'AI Platforma', href: '/ai-platforma', icon: '🤖', description: 'AI platforma i modeli' },
  { label: 'Banka', href: '/banka', icon: '🏦', description: 'SPAJA Banka platforma' },
  { label: 'AI IQ World Bank', href: '/ai-iq-world-bank', icon: '🌐', description: 'AI IQ WORLD BANK — sve o njoj: usluge, AI tehnologija, ERSTE računi, partneri, transferi, GitHub billing i ekosistem' },
  { label: 'AI IQ World Bank Procesiranje', href: '/ai-iq-world-bank-procesiranje', icon: '⚙️', description: 'Aktivni sloj procesiranja AI IQ World Bank: transakcije, kamatna obrada, AI fraud detekcija, SWIFT/blockchain rutiranje' },
  { label: 'Licencni Budžet Srbija', href: '/licencni-budzet-srbija', icon: '📜', description: 'Registar i budžet licenci za Srbiju — aktivna nabavka, regulatorni rokovi i godišnji plan troškova' },
  { label: 'Digitalna Industrija PIB/MB', href: '/digitalna-industrija-pib-mb', icon: '🧾', description: 'Centralni registar PIB i matičnih brojeva ključnih entiteta Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Šifra Delatnosti', href: '/digitalna-industrija-sifra-delatnosti', icon: '🏷️', description: 'Centralni registar šifara delatnosti ključnih entiteta Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Regulatorni Rokovi', href: '/digitalna-industrija-regulatorni-rokovi', icon: '📅', description: 'Centralni registar regulatornih rokova ključnih entiteta Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Izvoz Faktura', href: '/digitalna-industrija-izvoz-faktura', icon: '🧾', description: 'Centralni registar izvoznih faktura ključnih entiteta Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Devizni Prilivi', href: '/digitalna-industrija-devizni-prilivi', icon: '💱', description: 'Centralni registar deviznih priliva ključnih entiteta Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Devizni Odlivi', href: '/digitalna-industrija-devizni-odlivi', icon: '💸', description: 'Centralni registar deviznih odliva ključnih entiteta Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Devizni Saldo', href: '/digitalna-industrija-devizni-saldo', icon: '⚖️', description: 'Centralni registar neto deviznog salda ključnih entiteta Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Kursna Lista', href: '/digitalna-industrija-kursna-lista', icon: '💱', description: 'Centralni FX registar kursne liste ključnih valutnih parova Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Kursne Razlike', href: '/digitalna-industrija-kursne-razlike', icon: '📉', description: 'Centralni FX obračun kursnih razlika ključnih dokumenata Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Inflacije', href: '/digitalna-industrija-inflacije', icon: '📈', description: 'Centralni makroekonomski registar inflacije (CPI, mesečna, godišnja i bazna stopa) Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Valutni Rizik', href: '/digitalna-industrija-valutni-rizik', icon: '📊', description: 'Centralni registar valutne izloženosti i limita ključnih FX portfolija Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Hedzing', href: '/digitalna-industrija-hedzing', icon: '🛡️', description: 'Centralni registar hedzing ugovora za zaštitu od valutnog rizika Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Kamatni Rizik', href: '/digitalna-industrija-kamatni-rizik', icon: '📊', description: 'Centralni registar kamatnog rizika (fiksne, varijabilne i mešovite pozicije) Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Kreditni Rizik', href: '/digitalna-industrija-kreditni-rizik', icon: '🏦', description: 'Centralni registar kreditne izloženosti, PD/LGD i kolateralne pokrivenosti Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Likvidnosni Rizik', href: '/digitalna-industrija-likvidnosni-rizik', icon: '💧', description: 'Centralni registar likvidnosnog rizika, pokrića obaveza i neto tokova Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Operativni Rizik', href: '/digitalna-industrija-operativni-rizik', icon: '🧭', description: 'Centralni registar operativnog rizika (procesni, tehnološki, ljudski faktor i usklađenost) Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Reputacioni Rizik', href: '/digitalna-industrija-reputacioni-rizik', icon: '🏛️', description: 'Centralni registar reputacionog rizika (medijski, socijalni, regulatorni i partnerski) Digitalne Industrije u Srbiji' },
  { label: 'BAR KOD', href: '/bar-kod', icon: '🔢', description: 'Centralni BAR KOD registar svih platformi i generatorskog obrtaja po jedinici funkcije za digitalno fakturisanje' },
  { label: 'MIKROFILE', href: '/mikrofile', icon: '📁', description: 'Centralni mikro-digitalni registar fajlova i metapodataka za fakture, licence, ugovore i izveštaje' },
  { label: 'Digitalna Industrija Strateški Rizik', href: '/digitalna-industrija-strateski-rizik', icon: '🎯', description: 'Centralni registar strateškog rizika (konkurentski, tržišni, inovacioni i regulatorni) Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Pravni Rizik', href: '/digitalna-industrija-pravni-rizik', icon: '⚖️', description: 'Centralni registar pravnog rizika (ugovorni, sudski, intelektualna svojina i regulatorni) Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Poreski Rizik', href: '/digitalna-industrija-poreski-rizik', icon: '🧾', description: 'Centralni registar poreskog rizika (PDV, poreske prijave, transferne cene i kaznena izloženost) Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Compliance Rizik', href: '/digitalna-industrija-compliance-rizik', icon: '🛡️', description: 'Centralni registar compliance rizika (regulatorna usklađenost, kontrolne procedure, interni audit i kaznena izloženost) Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija ESG Rizik', href: '/digitalna-industrija-esg-rizik', icon: '🌱', description: 'Centralni registar ESG rizika (ekološki, socijalni i upravljački rizici sa kaznenom izloženošću) Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Diskriminacija', href: '/digitalna-industrija-diskriminacija', icon: '⚖️', description: 'Centralni registar diskriminacionog rizika u zapošljavanju, zaradama, benefitima, partnerstvima i AI automatizaciji Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Sajber Rizik', href: '/digitalna-industrija-sajber-rizik', icon: '🛡️', description: 'Centralni registar sajber rizika (mrežna bezbednost, zaštita podataka, pristupi i incidentni odgovor) Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Kapitalni Rizik', href: '/digitalna-industrija-kapitalni-rizik', icon: '🏛️', description: 'Centralni registar adekvatnosti kapitala (CAR, CET1, Tier1/Tier2 i kapitalnih bafera) Digitalne Industrije u Republici Srbiji' },
  { label: 'Digitalna Industrija Pozicije', href: '/digitalna-industrija-pozicije', icon: '👥', description: 'Centralni registar pozicija, popunjenosti i kadrovskih potreba Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Plate', href: '/digitalna-industrija-plate', icon: '💰', description: 'Centralni registar plata, fondova i poreskih obaveza Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Beneficije', href: '/digitalna-industrija-beneficije', icon: '🎁', description: 'Centralni registar beneficija i paketa pogodnosti Digitalne Industrije u Srbiji' },
  { label: 'Digitalna Industrija Nagrade', href: '/digitalna-industrija-nagrade', icon: '🏆', description: 'Centralni registar nagrada, bonusa i premija Digitalne Industrije u Srbiji' },
  { label: 'Poslovni Novčanik', href: '/poslovni-novcanik', icon: '💼', description: 'Wallet modul povezan sa AI IQ World Bank tokovima' },
  { label: 'Generator Poslovnih Računa', href: '/generator-za-poslovne-racune', icon: '🧾', description: 'AI IQ World Bank generator poslovnih računa za korisnike (RSD/EUR/USD)' },
  { label: 'Validator Poslovnih Računa', href: '/validator-poslovnih-racuna', icon: '✅', description: 'AI IQ World Bank validator izlaza generatora kroz format, compliance i operativne provere' },
  { label: 'AI IQ WORLD BANK Licencna Analiza', href: '/ai-iq-world-bank-licencna-analiza', icon: '📑', description: 'Centralni registar licenci po delatnostima, gap analiza i prioritetna nabavka' },
  { label: 'Licencni Budžet Srbija', href: '/licencni-budzet-srbija', icon: '💰', description: 'Budžetski plan nabavke svih licenci u AI IQ World Bank Srbija procurement režimu — troškovi, kategorije i faze' },
  { label: 'Licencni Portfolio Digitalne Industrije', href: '/digitalna-industrija-licencni-portfolio', icon: '📋', description: 'Centralni 4-nivoski registar svih licenci za legalan rad Digitalne Industrije — regulatorne, softverske, operativne i enterprise-ugovor' },
  { label: 'Issuer License Control Center', href: '/issuer-license-control-center', icon: '🪪', description: 'Kontrolni centar ovlašćenja za izdavanje licenci: odobravanje, blokatori, izdavanje i compliance' },
  { label: 'Digitalna Industrija PIB/M/B', href: '/digitalna-industrija-pib-mb', icon: '🧾', description: 'Centralni PIB/M/B registar sa hitnom procedurom za APR i Poresku upravu po svim entitetima Digitalne Industrije' },
  { label: 'Menjačnica', href: '/menjacnica', icon: '💱', description: 'SPAJA Menjačnica platforma' },
  { label: 'Pro Novčanik', href: '/menjacnica-novcanik', icon: '💼', description: 'AI IQ MENJAČNICA Profesionalni Novčanik — portfolio, P&L, orderbook, settlement' },
  { label: 'Kripto Trezor', href: '/kripto-trezor', icon: '🔐', description: 'SPAJA Kripto Trezor — cold storage, multi-sig i time-lock zaštita za sva digitalna sredstva' },
  { label: 'Kompanija SPAJA', href: '/kompanija', icon: '🏗️', description: 'O matičnoj kompaniji SPAJA' },
  { label: 'Organizacija SPAJA', href: '/organizacija', icon: '🏛️', description: 'Interna organizaciona struktura SPAJA' },
  { label: 'Proksi GitHub', href: '/proksi-github-deploy', icon: '🐙', description: 'Proksi GitHub Deploy sistem' },
  { label: 'WiFi Antena', href: '/proksi-wifi-antena', icon: '📶', description: 'Proksi WiFi Antena sistem' },
  { label: 'SPAJA Prompt', href: '/spaja-univerzalni-prompt', icon: '🎯', description: 'SPAJA Univerzalni Prompt' },
  { label: 'Glavni Endžin', href: '/glavni-endzin', icon: '🏭', description: 'Glavni Endžin Digitalne Industrije — SVE endžine spojene u jedan' },
  { label: 'MOZAK LOGIKA', href: '/mozak-logika', icon: '🧠', description: 'Inteligentni podsistem Glavnog Endžina — non-stop analiza, ideje, planovi i povratni odaziv' },
  { label: 'Generator Endžina', href: '/spaja-generator-engine', icon: '🔧', description: 'SPAJA Generator za Endžine — engine generator' },
  { label: 'Digitalni Brouvzer', href: '/spaja-digitalni-brouvzer', icon: '🌐', description: 'SPAJA Digitalni Brouvzer — EKSTREMNI — sopstveni motor, bekend, providni frontend, deploy, import, export' },
  { label: 'Laboratorija', href: '/io-openui-ao-laboratorija', icon: '🔬', description: 'IOOpenUIAO Laboratorija za Simulacije' },
  { label: 'Digitalna Observatorija', href: '/digitalna-observatorija', icon: '🔭', description: 'Standalone observatorijum modul — instrumenti, mete, sesije i alarmi' },
  { label: 'Render Medija', href: '/spaja-render-medija', icon: '🎬', description: 'SPAJA Render za Slike i Video' },
  { label: 'Gaming Platforma', href: '/io-openui-ao-gaming-platforma', icon: '🎮', description: 'IO/OPENUI/AO Gaming - SPAJA Univerzalni Endzin nad 97 igrica (io-openui-ao.vercel.app)' },
  { label: 'IO/OPENUI/AO Analitika', href: '/io-openui-ao-analitika', icon: '📊', description: 'IO/OPENUI/AO Analitika — kombinovani pregled gaming platforme i laboratorije' },
  { label: 'Pricing & Login', href: '/pricing', icon: '💰', description: 'Pricing planovi i registracija — Stripe integracija' },
  { label: 'Digitalni Televizor', href: '/digitalni-televizor', icon: '📺', description: 'SPAJA Univerzalni Digitalni Televizor — 12 kanala, live TV' },
  { label: 'Distribucija', href: '/distribucija', icon: '📡', description: 'Centralni read-only modul distribucije: čvorovi, kanali, KPI i readiness' },
  { label: 'Monitoring Live', href: '/monitoring-live', icon: '🎥', description: 'SPAJA Monitoring Live — Twitch-like streaming platforma' },
  { label: 'AI IQ Monitoring', href: '/ai-iq-monitoring', icon: '🔍', description: 'SPAJA AI IQ Monitoring — Sentry-like praćenje grešaka' },
  { label: 'Blog & FAQ', href: '/blog', icon: '📝', description: 'SPAJA Blog & FAQ — članci, vodiči, pitanja' },
  { label: 'Unit Testovi', href: '/unit-testovi', icon: '🧪', description: 'SPAJA Unit Testovi — 12 suita, 94.8% pokrivenost' },
  { label: 'OMEGA AI Suport', href: '/omega-ai-suport', icon: '📞', description: 'OMEGA AI Maksimalni Suport — 21 persona, telefoni, mejlovi, dispeč' },
  { label: 'OMEGA Plasiranje', href: '/omega-projekat-plasiranje', icon: '🚀', description: 'OMEGA PROJEKAT — automatsko plasiranje u opticaj, 10 faza, 10 sistema' },
  { label: 'LAUREATSKI ENKODER', href: '/laureatski-enkoder', icon: '🔐', description: 'Enkoderska matrica laureatskog centra kroz enkodersku vezu i koherentnost enkodera' },
  { label: 'LAUREATSKI TRANSKODER', href: '/laureatski-transkoder', icon: '🔄', description: 'Transkoderska matrica laureatskog centra kroz transkodersku vezu i koherentnost transkodera' },
  { label: 'LAUREATSKI REKODER', href: '/laureatski-rekoder', icon: '♻️', description: 'Rekoderska matrica laureatskog centra kroz rekodersku vezu i koherentnost rekodera' },
  { label: 'LAUREATSKI KODER', href: '/laureatski-koder', icon: '🧬', description: 'Koderska matrica laureatskog centra kroz kodersku vezu i koherentnost kodera' },
  { label: 'LAUREATSKI KODEK', href: '/laureatski-kodek', icon: '🎞️', description: 'Kodek matrica laureatskog centra kroz kodek vezu i koherentnost kodeka' },
  { label: 'LAUREATSKI KODEKS', href: '/laureatski-kodeks', icon: '📜', description: 'Kodeks matrica laureatskog centra kroz kodeks vezu i koherentnost kodeksa' },
  { label: 'LAUREATSKI DEKODER', href: '/laureatski-dekoder', icon: '🧩', description: 'Dekoderska matrica laureatskog centra kroz dekodersku vezu i koherentnost dekodera' },
  { label: 'LAUREATSKI DEMODULATOR', href: '/laureatski-demodulator', icon: '📻', description: 'Demodulatorska matrica laureatskog centra kroz demodulatorsku vezu i koherentnost demodulatora' },
  { label: 'LAUREATSKI MODULATOR', href: '/laureatski-modulator', icon: '🎚️', description: 'Modulatorska matrica laureatskog centra kroz modulatorsku vezu i koherentnost modulatora' },
  { label: 'LAUREATSKI OSCILATOR', href: '/laureatski-oscilator', icon: '🌀', description: 'Oscilatorska matrica laureatskog centra kroz oscilatorsku vezu i koherentnost oscilatora' },
  { label: 'LAUREATSKI REZONATOR', href: '/laureatski-rezonator', icon: '🎛️', description: 'Rezonatorska matrica laureatskog centra kroz impulsnu vezu i koherentnost rezonatora' },
  { label: 'LAUREATSKI EHO', href: '/laureatski-eho', icon: '📣', description: 'Eho matrica laureatskog centra kroz povratnu spregu impulsa i koherentnost eha' },
  { label: 'LAUREATSKI ODJEK', href: '/laureatski-odjek', icon: '🔊', description: 'Odječna matrica laureatskog centra kroz rezonantne impulse i koherentnost odjeka' },
  { label: 'LAUREATSKI TALAS', href: '/laureatski-talas', icon: '🌊', description: 'Talasna matrica laureatskog centra kroz frekvencijske čvorove i koherentnost talasa' },
  { label: 'LAUREATSKI SIGNAL', href: '/laureatski-signal', icon: '📡', description: 'Signalna matrica laureatskog centra kroz impulse i koherentnost signala' },
  { label: 'LAUREATSKI TAKT', href: '/laureatski-takt', icon: '🥁', description: 'Taktička matrica laureatskog centra kroz segmentisani metar i koherentnost takta' },
  { label: 'LAUREATSKI RITAM', href: '/laureatski-ritam', icon: '🥁', description: 'Ritmička matrica laureatskog centra kroz metronomske faze i tempo koherentnost' },
  { label: 'LAUREATSKI PULS', href: '/laureatski-puls', icon: '🫀', description: 'Pulsna dinamika laureatskog centra kroz harmonijsku rezonancu i vremenske otkucaje' },
  { label: 'LAUCENTRICNI SPEKTAR', href: '/laucentricni-spektar', icon: '🌊', description: 'Spektralna analiza laucentričnog sistema — harmoničko razlaganje četiri koncentrična sloja oko laureatskog centra' },
  { label: 'DIGATALNA EUREKA', href: '/digatalna-eureka', icon: '💡', description: 'Ektridonalna eksinometrijska ekstaza — epicentrični eklubrion — simetrsko digitalno jedinjenje u oktavnom sistemu' },
  { label: 'EKSPONAT GLAVNOG JEZGRA', href: '/eksponat-glavnog-jezgra', icon: '🔬', description: 'Eksponicionalni oblik cinemetričnog jedinjenja u oktavi — ilustrovani oktavni sistem — eksponat glavnog jezgra' },
  { label: 'DIGITALNI VORTEKS', href: '/digitalni-vorteks', icon: '🌀', description: 'Vorteksna dinamika digitalnog sistema — rotacioni model oktavnih energija u spiralnom jedinjenju ka centru Digitalne Industrije' },
  { label: 'Eksponencijalne Funkcije', href: '/oktavne-eksponencijalne-funkcije', icon: '📈', description: 'Oktavni monolog + eksponencionalne geometrijske razmere (12 oktava, 360D–5760D) — figuracioni centar — OMEGA PROJEKAT' },
  { label: 'Zvanično Otvaranje', href: '/omega-projekat-zvanicno-otvaranje', icon: '🎉', description: 'OMEGA PROJEKAT — zvanično otvaranje prema monolizmima, verifikacija, saglasnost osnivača' },
  { label: 'Digitalni Kompjuter', href: '/spaja-digitalni-kompjuter', icon: '🖥️', description: 'SPAJA Digitalni Kompjuter — GPU 8.700.000, RAM 276.000 GB, zakup kao usluga' },
  { label: 'Oktavni GPU/RAM', href: '/oktavni-gpu-ram', icon: '🎮', description: 'Oktavni sistem u rasponu ekvalaturnog galaksipoznog sektora u matričnom jedinjenju — GPU i RAM za igrice' },
  { label: 'Registracija', href: '/registracija', icon: '📝', description: 'Registracija korisnika — kreiranje naloga za pristup platformi' },
  { label: 'Bezbednost', href: '/security', icon: '🔒', description: 'OMEGA Bezbednosni sistem — zaštita i enkripcija podataka' },
  { label: 'Nabavka', href: '/glavni-sistem-nabavka', icon: '💰', description: 'Glavni Sistem Nabavke — 50 digitalnih varijacija kupljeno iz AI IQ World Bank' },
  { label: 'Blockchain', href: '/blockchain', icon: '🔗', description: 'AI IQ World Bank pametni ugovor — Polygon blockchain, javno proverljive transakcije' },
  { label: 'Reklame & Partnerstva', href: '/reklame-i-partnerstva', icon: '📢', description: 'Reklamne kampanje, partnerstva iz svih branši i monetizacija' },
  { label: 'Dnevna Raspodela', href: '/dnevna-raspodela-zarade', icon: '💰', description: 'Dnevna raspodela zarade — 96% ERSTE + 4% AI IQ World Bank' },
  { label: 'SpajaUltra REPL', href: '/spaja-ultra-repl', icon: '⌨️', description: 'SpajaUltraOmegaCore REPL — DSL parser, transpajler, runtime audit log' },
  { label: 'Digitalna Platforma', href: '/digitalna-platforma', icon: '🌐', description: 'AI IQ SUPER PLATFORMA — kompletni digitalni ekosistem Kompanije SPAJA' },
  { label: 'Analiza Svega', href: '/analiza-svega', icon: '🔭', description: 'Celokupna analiza ekosistema — ekosistem, infrastruktura, finansije, bezbednost, operativa, autofinish i protokoli' },
  { label: 'Potencijal Svega Ovoga Do Sada', href: '/potencijal-svega-ovoga-do-sada', icon: '🧭', description: 'Stanje sada vs potencijal posle sledećih koraka — blokeri, unlock faktori i expected uplift po domenima' },
  { label: 'Procesuiranje Svega', href: '/procesuiranje-svega', icon: '⚙️', description: 'Aktivni pipeline procesiranja svih domena — bankarski, AI, finansijski, licencni, ekosistem, autofinish, bezbednosni i analitički' },
  { label: 'Procesuiranje 3', href: '/procesuiranje-3', icon: '⚙️', description: 'Kanonski v3 processing signal: dual-run kompatibilnost sa v2, SLA pragovi, trend i history snapshot-i' },
  { label: 'Maksimus Svega', href: '/maksimus-svega', icon: '🚀', description: 'Master signal svih ključnih svega domena — analiza, potencijal, procesuiranje i autofinish orkestracija' },
  { label: 'Maksimus 2', href: '/maksimus-2', icon: '🚀', description: 'V2 master signal sa 6 domena — analiza, potencijal, procesuiranje, ekstremno procesuiranje, operativna spremnost i autofinish' },
  { label: 'Maksimus 3', href: '/maksimus-3', icon: '🚀', description: 'V3 master signal — 8 domena sa SLA pragovima i istorijom' },
  { label: 'MOŽE SVE — Super Hub', href: '/moze-sve', icon: '💥', description: 'Svih 6 core modula u jednom pogledu: SpajaPro, OMEGA AI, Proksi, Mobilna, Auto-Popravka i Evolucija' },
  { label: 'SVE OD SVEGA', href: '/sve-od-svega', icon: '🌌', description: 'Ultimativni mega-signal koji agregira sve svega domene: analiza, potencijal, procesuiranje i autofinish' },
  { label: 'Autofinish', href: '/autofinish', icon: '🤖', description: 'Autofinish Dashboard — napredak, iteracije, kategorije, SLA i trend metrike' },
  { label: 'Autofinish Nexus', href: '/autofinish-nexus', icon: '🔗', description: 'Operativni sažetak autofinish stanja — health score, release readiness, error budget i DORA metrike' },
  { label: 'Protokoli', href: '/protokoli', icon: '📋', description: 'Centralni registar protokola i verifikacija operativnih procedura' },
  { label: 'Pametni Ugovori', href: '/pametni-ugovori', icon: '📜', description: 'Pametni ugovori i blockchain integracija' },
  { label: 'Digitalni Prozor', href: '/digitalni-prozor', icon: '🪟', description: 'Digitalni prozor platforme — pregled i navigacija kroz digitalne resurse' },
  { label: 'Spaja Baza Control', href: '/spaja-baza-control', icon: '🗄️', description: 'Kontrolni centar Spaja baze znanja — status indeksiranja i zdravlje' },
  { label: 'Vercel Priključenje', href: '/vercel-priklucenje', icon: '▲', description: 'Vercel priključenje i deploy konfiguracija platforme' },
  { label: 'Ekstrimli Ekstrem', href: '/ekstrimli-ekstrem', icon: '⚡', description: 'Ekstremno procesuiranje i operativna spremnost — signal koji preseca sve limite' },
  { label: 'Pentracija', href: '/pentracija', icon: '🔍', description: 'Pentracija — dubinska analiza i probe test ekosistema' },
  { label: 'Panetracija 2', href: '/panetracija-2', icon: '🔬', description: 'V2 panetracija — proširena dijagnostika sa SLA i trend praćenjem' },
  { label: 'Prijava', href: '/login', icon: '🔑', description: 'Prijava na platformu — pristup Digitalnoj Industriji' },
  { label: 'Zaboravljena Lozinka', href: '/zaboravljena-lozinka', icon: '🔓', description: 'Resetovanje lozinke za pristup platformi' },
];
