import type { NavItem } from './types';

export const navigation: NavItem[] = [
  { label: 'Početna', href: '/', icon: '🏠', description: 'Digitalna Industrija — pregled' },
  { label: 'Dashboard', href: '/dashboard', icon: '📊', description: 'Statistika i stanje ekosistema' },
  { label: 'Industrija', href: '/industrija', icon: '🏭', description: 'O digitalnoj industriji' },
  { label: 'Platforme', href: '/platforme', icon: '🧩', description: 'Sve platforme u ekosistemu' },
  { label: 'Organizacije', href: '/organizacije', icon: '🏢', description: 'Organizaciona struktura' },
  { label: 'Kompanije', href: '/kompanije', icon: '🏛️', description: 'Kompanije u ekosistemu' },
  { label: 'Proizvodi (EN)', href: '/proizvodi', icon: '📦', description: 'IT proizvodi i alati (engleski prikaz)' },
  { label: 'IT Proizvodi', href: '/it-proizvodi', icon: '⚙️', description: 'Svi IT proizvodi digitalne industrije' },
  { label: 'OMEGA AI', href: '/omega-ai', icon: '🧠', description: '21 OMEGA AI persona u 8 oktava' },
  { label: 'SpajaPro', href: '/spaja-pro', icon: '🚀', description: 'SpajaPro Engine verzije 6-15' },
  { label: 'Prompt', href: '/prompt', icon: '💬', description: 'Prompt sistem sa 28 promptova' },
  { label: 'Igrice', href: '/igrice', icon: '🎮', description: '95 igrica u 18 kategorija' },
  { label: 'Dimenzije', href: '/dimenzije', icon: '🌀', description: 'Dimenzionalni sistem 360D-5760D' },
  { label: 'Proksi', href: '/proksi', icon: '📡', description: 'Proksi mreža i signali' },
  { label: 'Mobilna Mreža', href: '/mobilna-mreza', icon: '📱', description: 'SPAJA Mobilna Mreža sa 4 centrale' },
  { label: 'Call Centar', href: '/call-centar', icon: '📞', description: 'Moblini SPAJA licence, digitalne usluge i dodela paketa' },
  { label: 'Ekosistem', href: '/ekosistem', icon: '🌐', description: 'Celokupan pregled ekosistema' },
  { label: 'Deploy', href: '/deploy', icon: '🚀', description: 'Status deploy-a platformi' },
  { label: 'Auto-Popravka', href: '/auto-popravka', icon: '🔧', description: 'Autonomni sistem za popravku' },
  { label: 'AI Platforma', href: '/ai-platforma', icon: '🤖', description: 'AI platforma i modeli' },
  { label: 'Banka', href: '/banka', icon: '🏦', description: 'SPAJA Banka platforma' },
  { label: 'Poslovni Novčanik', href: '/poslovni-novcanik', icon: '💼', description: 'Wallet modul povezan sa AI IQ World Bank tokovima' },
  { label: 'Menjačnica', href: '/menjacnica', icon: '💱', description: 'SPAJA Menjačnica platforma' },
  { label: 'Pro Novčanik', href: '/menjacnica-novcanik', icon: '💼', description: 'AI IQ MENJAČNICA Profesionalni Novčanik — portfolio, P&L, orderbook, settlement' },
  { label: 'Kripto Trezor', href: '/kripto-trezor', icon: '🔐', description: 'SPAJA Kripto Trezor — cold storage, multi-sig i time-lock zaštita za sva digitalna sredstva' },
  { label: 'Kompanija SPAJA', href: '/kompanija', icon: '🏗️', description: 'O matičnoj kompaniji SPAJA' },
  { label: 'Organizacija SPAJA', href: '/organizacija', icon: '🏛️', description: 'Interna organizaciona struktura SPAJA' },
  { label: 'Proksi GitHub', href: '/proksi-github-deploy', icon: '🐙', description: 'Proksi GitHub Deploy sistem' },
  { label: 'WiFi Antena', href: '/proksi-wifi-antena', icon: '📶', description: 'Proksi WiFi Antena sistem' },
  { label: 'SPAJA Prompt', href: '/spaja-univerzalni-prompt', icon: '🎯', description: 'SPAJA Univerzalni Prompt' },
  { label: 'Glavni Endžin', href: '/glavni-endzin', icon: '🏭', description: 'Glavni Endžin Digitalne Industrije — SVE endžine spojene u jedan' },
  { label: 'Generator Endžina', href: '/spaja-generator-engine', icon: '🔧', description: 'SPAJA Generator za Endžine — engine generator' },
  { label: 'Digitalni Brouvzer', href: '/spaja-digitalni-brouvzer', icon: '🌐', description: 'SPAJA Digitalni Brouvzer — EKSTREMNI — sopstveni motor, bekend, providni frontend, deploy, import, export' },
  { label: 'Laboratorija', href: '/io-openui-ao-laboratorija', icon: '🔬', description: 'IOOpenUIAO Laboratorija za Simulacije' },
  { label: 'Render Medija', href: '/spaja-render-medija', icon: '🎬', description: 'SPAJA Render za Slike i Video' },
  { label: 'Gaming Platforma', href: '/io-openui-ao-gaming-platforma', icon: '🎮', description: 'IO/OPENUI/AO Gaming - SPAJA Univerzalni Endzin nad 95 igrica (io-openui-ao.vercel.app)' },
  { label: 'IO/OPENUI/AO Analitika', href: '/io-openui-ao-analitika', icon: '📊', description: 'IO/OPENUI/AO Analitika — kombinovani pregled gaming platforme i laboratorije' },
  { label: 'Pricing & Login', href: '/pricing', icon: '💰', description: 'Pricing planovi i registracija — Stripe integracija' },
  { label: 'Digitalni Televizor', href: '/digitalni-televizor', icon: '📺', description: 'SPAJA Univerzalni Digitalni Televizor — 12 kanala, live TV' },
  { label: 'Monitoring Live', href: '/monitoring-live', icon: '🎥', description: 'SPAJA Monitoring Live — Twitch-like streaming platforma' },
  { label: 'AI IQ Monitoring', href: '/ai-iq-monitoring', icon: '🔍', description: 'SPAJA AI IQ Monitoring — Sentry-like praćenje grešaka' },
  { label: 'Blog & FAQ', href: '/blog', icon: '📝', description: 'SPAJA Blog & FAQ — članci, vodiči, pitanja' },
  { label: 'Unit Testovi', href: '/unit-testovi', icon: '🧪', description: 'SPAJA Unit Testovi — 12 suita, 94.8% pokrivenost' },
  { label: 'OMEGA AI Suport', href: '/omega-ai-suport', icon: '📞', description: 'OMEGA AI Maksimalni Suport — 21 persona, telefoni, mejlovi, dispeč' },
  { label: 'OMEGA Plasiranje', href: '/omega-projekat-plasiranje', icon: '🚀', description: 'OMEGA PROJEKAT — automatsko plasiranje u opticaj, 10 faza, 10 sistema' },
  { label: 'LAUREATSKI REKODER', href: '/laureatski-rekoder', icon: '♻️', description: 'Rekoderska matrica laureatskog centra kroz rekodersku vezu i koherentnost rekodera' },
  { label: 'LAUREATSKI TRANSKODER', href: '/laureatski-transkoder', icon: '🔄', description: 'Transkoderska matrica laureatskog centra kroz transkodersku vezu i koherentnost transkodera' },
  { label: 'LAUREATSKI ENKODER', href: '/laureatski-enkoder', icon: '🔐', description: 'Enkoderska matrica laureatskog centra kroz enkodersku vezu i koherentnost enkodera' },
  { label: 'LAUREATSKI DEKODER', href: '/laureatski-dekoder', icon: '🧩', description: 'Dekoderska matrica laureatskog centra kroz dekodersku vezu i koherentnost dekodera' },
  { label: 'LAUREATSKI DEMODULATOR', href: '/laureatski-demodulator', icon: '📻', description: 'Demodulatorska matrica laureatskog centra kroz demodulatorsku vezu i koherentnost demodulatora' },
  { label: 'LAUREATSKI MODULATOR', href: '/laureatski-modulator', icon: '🎚️', description: 'Modulatorska matrica laureatskog centra kroz modulatorsku vezu i koherentnost modulatora' },
  { label: 'LAUREATSKI OSCILATOR', href: '/laureatski-oscilator', icon: '🌀', description: 'Oscilatorska matrica laureatskog centra kroz oscilatorsku vezu i koherentnost oscilatora' },
  { label: 'LAUREATSKI REZONATOR', href: '/laureatski-rezonator', icon: '🎛️', description: 'Rezonatorska matrica laureatskog centra kroz impulsnu vezu i koherentnost rezonatora' },
  { label: 'LAUREATSKI EHO', href: '/laureatski-eho', icon: '📣', description: 'Eho matrica laureatskog centra kroz povratnu spregu impulsa i koherentnost eha' },
  { label: 'LAUREATSKI ODJEK', href: '/laureatski-odjek', icon: '🔊', description: 'Odječna matrica laureatskog centra kroz rezonantne impulse i koherentnost odjeka' },
  { label: 'LAUREATSKI TALAS', href: '/laureatski-talas', icon: '🌊', description: 'Talasna matrica laureatskog centra kroz frekvencijske čvorove i koherentnost talasa' },
  { label: 'LAUREATSKI SIGNAL', href: '/laureatski-signal', icon: '📡', description: 'Signalna matrica laureatskog centra kroz impulse i koherentnost signala' },
  { label: 'LAUREATSKI TAKT', href: '/laureatski-takt', icon: '🥁', description: 'Taktička matrica laureatskog centra kroz segmentisani metar i koherentnost takta' },
  { label: 'LAUREATSKI RITAM', href: '/laureatski-ritam', icon: '🥁', description: 'Ritmička matrica laureatskog centra kroz metronomske faze i tempo koherentnost' },
  { label: 'LAUREATSKI PULS', href: '/laureatski-puls', icon: '🫀', description: 'Pulsna dinamika laureatskog centra kroz harmonijsku rezonancu i vremenske otkucaje' },
  { label: 'LAUCENTRICNI SPEKTAR', href: '/laucentricni-spektar', icon: '🌊', description: 'Spektralna analiza laucentričnog sistema — harmoničko razlaganje četiri koncentrična sloja oko laureatskog centra' },
  { label: 'DIGATALNA EUREKA', href: '/digatalna-eureka', icon: '💡', description: 'Ektridonalna eksinometrijska ekstaza — epicentrični eklubrion — simetrsko digitalno jedinjenje u oktavnom sistemu' },
  { label: 'Eksponencijalne Funkcije', href: '/oktavne-eksponencijalne-funkcije', icon: '📈', description: 'Oktavni monolog eksponencijalnog ekvivalenta — figuracioni centar — matricno jedinjenje — OMEGA PROJEKAT' },
  { label: 'Zvanično Otvaranje', href: '/omega-projekat-zvanicno-otvaranje', icon: '🎉', description: 'OMEGA PROJEKAT — zvanično otvaranje prema monolizmima, verifikacija, saglasnost osnivača' },
  { label: 'Digitalni Kompjuter', href: '/spaja-digitalni-kompjuter', icon: '🖥️', description: 'SPAJA Digitalni Kompjuter — GPU 8.700.000, RAM 276.000 GB, zakup kao usluga' },
  { label: 'Oktavni GPU/RAM', href: '/oktavni-gpu-ram', icon: '🎮', description: 'Oktavni sistem u rasponu ekvalaturnog galaksipoznog sektora u matričnom jedinjenju — GPU i RAM za igrice' },
  { label: 'Registracija', href: '/registracija', icon: '📝', description: 'Registracija korisnika — kreiranje naloga za pristup platformi' },
  { label: 'Bezbednost', href: '/security', icon: '🔒', description: 'OMEGA Bezbednosni sistem — zaštita i enkripcija podataka' },
  { label: 'Nabavka', href: '/glavni-sistem-nabavka', icon: '💰', description: 'Glavni Sistem Nabavke — 50 digitalnih varijacija kupljeno iz AI IQ World Bank' },
  { label: 'Blockchain', href: '/blockchain', icon: '🔗', description: 'AI IQ World Bank pametni ugovor — Polygon blockchain, javno proverljive transakcije' },
  { label: 'Reklame & Partnerstva', href: '/reklame-i-partnerstva', icon: '📢', description: 'Reklamne kampanje, partnerstva iz svih branši i monetizacija' },
  { label: 'Dnevna Raspodela', href: '/dnevna-raspodela-zarade', icon: '💰', description: 'Dnevna raspodela zarade — 96% ERSTE + 4% AI IQ World Bank' },
  { label: 'SpajaUltra REPL', href: '/spaja-ultra-repl', icon: '⌨️', description: 'SpajaUltraOmegaCore REPL — DSL parser, transpajler, runtime audit log' },
  { label: 'Digitalna Platforma', href: '/digitalna-platforma', icon: '🌐', description: 'AI IQ SUPER PLATFORMA — kompletni digitalni ekosistem Kompanije SPAJA' },
  { label: 'Prijava', href: '/login', icon: '🔑', description: 'Prijava na platformu — pristup Digitalnoj Industriji' },
  { label: 'Zaboravljena Lozinka', href: '/zaboravljena-lozinka', icon: '🔓', description: 'Resetovanje lozinke za pristup platformi' },
];
