import { Organization } from './types';

export const organizations: Organization[] = [
  {
    id: 'ai-iq-world-bank',
    name: 'AI IQ World Bank',
    description: 'The best bank in the world, maximally professional, cooperating with all banks globally.',
    descriptionSr: 'Najbolja banka na svetu — maksimalno profesionalna, saradnju ima sa svim bankama sveta. Pokretana Omega AI tehnologijom.',
    type: 'bank',
    icon: '🏦',
    features: [
      'AI pametne kartice',
      'Međunarodni transferi (SWIFT/SEPA)',
      'AI investicioni portfolio',
      'Hipotekarni krediti',
      'Štedni računi',
      'Kriptografska sigurnost',
      'Omega AI tehnologija',
      'Fraud Detection 99.99%',
      'Smederevo ekspanzija',
    ],
    status: 'active',
    url: '/banka',
  },
  {
    id: 'ai-iq-menjacnica',
    name: 'AI IQ Menjačnica',
    description: 'The best exchange in the world with the most cryptocurrencies. World-class exchange.',
    descriptionSr: 'Najbolja kripto i fiat menjačnica na svetu. Live kursevi, BUY/SELL, BTC, ETH, USDT, EUR, RSD. Fee: 2%.',
    type: 'exchange',
    icon: '💱',
    features: [
      'Kripto trading (BTC, ETH, USDT...)',
      'Fiat valute (EUR, RSD, USD)',
      'Live kursevi (CoinGecko)',
      'BUY/SELL orderi',
      '2% transparentna provizija',
      'AI analiza tržišta',
      '1000+ kriptovaluta',
      'Mobilna aplikacija',
    ],
    status: 'active',
    url: '/menjacnica',
  },
  {
    id: 'kompanija-spaja',
    name: 'Kompanija SPAJA',
    description: 'Professional IT company building the future with web development, AI integrations, and cloud architecture.',
    descriptionSr: 'Profesionalna IT kompanija koja gradi budućnost. Web razvoj, AI integracije, cloud arhitektura i poslovne aplikacije.',
    type: 'company',
    icon: '🏢',
    features: [
      'Web razvoj',
      'AI integracije',
      'Cloud arhitektura',
      'Poslovne aplikacije',
      'IT konsalting',
      'DevOps usluge',
    ],
    status: 'active',
    url: '/kompanija',
  },
  {
    id: 'io-openui-ao',
    name: 'IO OpenUI AO',
    description: 'AI Real-time platform with WebRTC voice chat and Socket.IO, powered by OpenAI.',
    descriptionSr: 'WebRTC + OpenAI Realtime API — glasovni razgovor sa AI u realnom vremenu. Profesionalna platforma za saradnju.',
    type: 'ai-platform',
    icon: '🤖',
    features: [
      'Glasovni AI Chat (WebRTC)',
      'Real-time komunikacija',
      'Socket.IO chat',
      'OpenAI Realtime API',
      'Efemerni API ključevi',
      'Igrice & Zabava',
      'End-to-end enkripcija',
    ],
    status: 'active',
    url: '/ai-platforma',
  },
  {
    id: 'svetska-organizacija',
    name: 'SVETSKA ORGANIZACIJA',
    description: 'World Organization for the well-being of humanity.',
    descriptionSr: 'SVETSKA ORGANIZACIJA za dobrobit čovečanstva. Globalna organizacija za humanitarne ciljeve.',
    type: 'organization',
    icon: '🌍',
    features: [
      'Globalni humanitarni ciljevi',
      'Dobrobit čovečanstva',
      'Međunarodna saradnja',
      'Edukativni programi',
    ],
    status: 'planned',
    url: '/organizacija',
  },
  {
    id: 'openai-platform',
    name: 'OpenAI Platforma',
    description: 'Professional platform for business, movies, images, games and much more.',
    descriptionSr: 'Profesionalna platforma za poslovanje, filmove, slike, igrice i još mnogo toga.',
    type: 'ai-platform',
    icon: '🎬',
    features: [
      'Poslovne aplikacije',
      'Filmovi i video',
      'Generisanje slika',
      'AI igrice',
      'Kreativni alati',
    ],
    status: 'planned',
    url: '/ai-platforma',
  },
];

export function getOrganizationsByType(type: Organization['type']): Organization[] {
  return organizations.filter(o => o.type === type);
}
