import type { Platforma, KategorijaPlatforme } from './types';
import { EKOSISTEM_URLS } from './ekosistem-urls';

export const platforme: Platforma[] = [
  {
    id: 'ai-iq-super-platforma',
    naziv: 'AI IQ SUPER PLATFORMA',
    opis: 'Centralna platforma za upravljanje celim ekosistemom. SPAJA Generator za Endžine prevlači engine-e preko celog repozitorijuma. Link: https://chatgpt.com/c/697aae0b-4984-8385-a9b6-1e762b39d7de',
    kategorija: 'jezgro',
    repo: 'spaja86/AI-IQ-SUPER-PLATFORMA',
    url: EKOSISTEM_URLS.AI_IQ_SUPER_PLATFORMA,
    ikona: '🏢',
    status: 'spremna',
    progres: 100,
    tehnologije: ['Next.js 16', 'TypeScript', 'Tailwind CSS 4', 'Vercel'],
    funkcije: ['Dashboard', 'Monitoring', 'Deploy Management', 'Sekvence', 'SPAJA Generator za Endžine'],
    deploy: { status: 'aktivan', domen: 'ai-iq-super-platforma.vercel.app', vercelProjekt: 'ai-iq-super-platforma', framework: 'Next.js 16', buildKomanda: 'next build' },
  },
  {
    id: 'io-openui-ao',
    naziv: 'IO OPENUI AO — SpajaPro Engine + Laboratorija',
    opis: 'Unified frontend sa SpajaPro 6-15 engine-om (zamena za ChatGPT), Prompt sistemom, fizičkom laboratorijom i B2B softverom. Razvoj B2B softvera za IO/OpenUI/AO sa vezanim fizičkim laboratorijama. Laboratorija link: https://chatgpt.com/c/688e73aa-ecf8-8006-a7bd-b7d796498ae7. Igrice Dota 1350, TRANSFORMERS 1350, BUBLI BABLI 1250, SPAJA POKER imaju linkove u ovom repozitorijumu.',
    kategorija: 'jezgro',
    repo: 'spaja86/IO-OPENUI-AO',
    url: EKOSISTEM_URLS.IO_OPENUI_AO,
    ikona: '🖥️',
    status: 'spremna',
    progres: 100,
    tehnologije: ['React', 'SpajaPro Engine', 'Prompt System', 'WebRTC', 'Socket.IO', 'Vercel', 'B2B Software'],
    funkcije: ['SpajaPro Prompt Chat', 'Banka modul', 'Menjacnica modul', 'AI modul sa Prompt-om', 'SpajaPro 6-15 integracija', 'Fizička laboratorija', 'Razvoj B2B softvera', 'Dota 1350', 'TRANSFORMERS 1350', 'BUBLI BABLI 1250', 'SPAJA POKER'],
    deploy: { status: 'aktivan', domen: 'io-openui-ao.vercel.app', vercelProjekt: 'io-openui-ao', framework: 'React + SpajaPro', buildKomanda: 'npm run build' },
  },
  {
    id: 'ai-iq-menjacnica',
    naziv: 'Ai Iq Menjacnica',
    opis: 'Kripto i fiat menjacnica sa AI optimizacijom. Linkovi u repozitorijumu sadrže sve potrebno za rad i ONLINE proceduru.',
    kategorija: 'finansije',
    repo: 'spaja86/Ai-Iq-Menja-nica',
    url: EKOSISTEM_URLS.AI_IQ_MENJACNICA,
    ikona: '💱',
    status: 'spremna',
    progres: 100,
    tehnologije: ['Next.js', 'TypeScript', 'TradingView', 'API'],
    funkcije: ['Kripto trading', 'Fiat konverzija', 'AI predikcije', 'Portfolio', 'ONLINE rad i procedura'],
    deploy: { status: 'aktivan', domen: 'ai-iq-menja-nica-6cnf-git-copi-0e2b0a-nikolas-projects-b8a8458f.vercel.app', vercelProjekt: 'ai-iq-menjacnica', framework: 'Next.js', buildKomanda: 'next build' },
  },
  {
    id: 'ai-iq-world-bank',
    naziv: 'Ai Iq World Bank',
    opis: 'Digitalna banka sa globalnim dometom. Linkovi u repozitorijumu sadrže sve potrebno za rad i ONLINE proceduru.',
    kategorija: 'finansije',
    repo: 'spaja86/Ai-Iq-World-Bank',
    url: EKOSISTEM_URLS.AI_IQ_WORLD_BANK,
    ikona: '🏦',
    status: 'spremna',
    progres: 100,
    tehnologije: ['Next.js', 'TypeScript', 'Stripe', 'PostgreSQL'],
    funkcije: ['Racuni', 'Transferi', 'Krediti', 'Investicije', 'ONLINE rad i procedura'],
    deploy: { status: 'aktivan', domen: 'ai-iq-world-bank-git-copilot-n-697903-nikolas-projects-b8a8458f.vercel.app', vercelProjekt: 'ai-iq-world-bank', framework: 'Next.js', buildKomanda: 'next build' },
  },
  {
    id: 'svetska-organizacija',
    naziv: 'SVETSKA ORGANIZACIJA',
    opis: 'Globalna organizacija za koordinaciju projekata. Linkovi u repozitorijumu sadrže sve potrebno za rad i ONLINE proceduru.',
    kategorija: 'globalno',
    repo: 'spaja86/SVETSKA-ORGANIZACIJA',
    url: 'https://svetska-organizacija-git-copil-0ce22a-nikolas-projects-b8a8458f.vercel.app/',
    ikona: '🌍',
    status: 'spremna',
    progres: 100,
    tehnologije: ['Next.js', 'TypeScript', 'i18n', 'API'],
    funkcije: ['Upravljanje projektima', 'Koordinacija timova', 'Izvestaji', 'ONLINE rad i procedura'],
    deploy: { status: 'aktivan', domen: 'svetska-organizacija-git-copil-0ce22a-nikolas-projects-b8a8458f.vercel.app', vercelProjekt: 'svetska-organizacija', framework: 'Next.js', buildKomanda: 'next build' },
  },
  {
    id: 'omega-ai-github',
    naziv: 'OMEGA AI za GitHub',
    opis: 'AI agent za automatizaciju GitHub operacija sa SpajaPro Prompt engine-om',
    kategorija: 'ai',
    repo: 'spaja86/OMEGA-AI-za-GIT-HUB',
    url: 'https://github.com/spaja86/OMEGA-AI-za-GIT-HUB',
    ikona: '🧠',
    status: 'spremna',
    progres: 92,
    tehnologije: ['TypeScript', 'GitHub API', 'SpajaPro Engine', 'Prompt System', 'Vercel'],
    funkcije: ['SpajaPro Prompt code review', 'PR automation', 'Issue triage', 'CI/CD', 'Prompt-based suggestions'],
    deploy: { status: 'aktivan', framework: 'Node.js + SpajaPro', buildKomanda: 'tsc' },
  },
  {
    id: 'omega-ai-vercel',
    naziv: 'OMEGA AI za Vercel',
    opis: 'AI agent za Vercel deploy i monitoring',
    kategorija: 'ai',
    repo: 'spaja86/OMEGA-AI-za-Vercel-',
    url: 'https://omega-ai-vercel.vercel.app',
    ikona: '🚀',
    status: 'spremna',
    progres: 100,
    tehnologije: ['TypeScript', 'Vercel API', 'OpenAI'],
    funkcije: ['Auto deploy', 'Performance monitoring', 'Error tracking'],
    deploy: { status: 'aktivan', domen: 'omega-ai-vercel.vercel.app', vercelProjekt: 'omega-ai-vercel', framework: 'Node.js', buildKomanda: 'tsc' },
  },
  {
    id: 'omega-ai-google',
    naziv: 'OMEGA AI za Google',
    opis: 'AI agent za Google Cloud i Analytics',
    kategorija: 'ai',
    repo: 'spaja86/-OMEGA-AI-za-Google-',
    url: 'https://omega-ai-google.vercel.app',
    ikona: '🔍',
    status: 'spremna',
    progres: 100,
    tehnologije: ['TypeScript', 'Google Cloud', 'BigQuery', 'Analytics'],
    funkcije: ['SEO optimizacija', 'Analytics izvestaji', 'Cloud funkcije'],
    deploy: { status: 'aktivan', domen: 'omega-ai-google.vercel.app', vercelProjekt: 'omega-ai-google', framework: 'Node.js', buildKomanda: 'tsc' },
  },
  {
    id: 'omega-ai-5-persona',
    naziv: 'OMEGA AI 5 Persona',
    opis: 'Sistem od 5 specijalizovanih AI persona za Facebook, Instagram, TikTok, Threads i YouTube sa Prompt-ovima',
    kategorija: 'ai',
    repo: 'spaja86/-OMEGA-AI-5-persona-za-Facebook-i-Instagram-i-TikTok-i-Threads-i-YoutYube-',
    url: 'https://omega-ai-5-persona.vercel.app',
    ikona: '👥',
    status: 'spremna',
    progres: 100,
    tehnologije: ['TypeScript', 'SpajaPro Engine', 'Prompt System', 'LangChain'],
    funkcije: ['Multi-persona Prompt AI', 'SpajaPro Prompt agenti', 'Prompt kolaboracija', 'Facebook AI', 'Instagram AI', 'TikTok AI', 'Threads AI', 'YouTube AI'],
    deploy: { status: 'aktivan', domen: 'omega-ai-5-persona.vercel.app', vercelProjekt: 'omega-ai-5-persona', framework: 'Node.js + SpajaPro', buildKomanda: 'tsc' },
  },
  {
    id: 'spajapro-platforma',
    naziv: 'SpajaPro Platforma',
    opis: 'SpajaPro 6-15 engine — zamena za ChatGPT sa naprednim Prompt sistemom. Aktivni Promptovi za programiranje dostupni u IO-OPENUI-AO repo.',
    kategorija: 'ai',
    repo: 'spaja86/IO-OPENUI-AO',
    url: 'https://spajapro-platforma.vercel.app',
    ikona: '🌟',
    status: 'spremna',
    progres: 100,
    tehnologije: ['TypeScript', 'SpajaPro 6-15', 'Prompt Engine', 'Kompanija-SPAJA'],
    funkcije: ['SpajaPro Prompt Engine', '10 verzija (6-15)', 'Univerzalni Prompt', 'Multi-language Prompt', 'Fine-tuning', 'Aktivni Promptovi za programiranje'],
    deploy: { status: 'aktivan', domen: 'spajapro-platforma.vercel.app', vercelProjekt: 'spajapro-platforma', framework: 'Next.js + SpajaPro', buildKomanda: 'next build' },
  },
  {
    id: 'input-output-copilot',
    naziv: 'Input/Output za Copilot',
    opis: 'I/O interfejs za GitHub Copilot integraciju sa SpajaPro Prompt-om. Aktivni Promptovi za komunikaciju sa korisnicima.',
    kategorija: 'alati',
    repo: 'spaja86/Input-Output-za-kopilota-da-mo-e-da-komunicira-sa-korsnicima-akticno',
    url: 'https://io-copilot.vercel.app',
    ikona: '⚙️',
    status: 'spremna',
    progres: 100,
    tehnologije: ['TypeScript', 'GitHub Copilot API', 'SpajaPro Prompt', 'Python'],
    funkcije: ['SpajaPro Prompt suggestions', 'Context management', 'Custom Prompt šabloni', 'SpajaPro 10 integracija', 'Aktivna komunikacija sa korisnicima'],
    deploy: { status: 'aktivan', domen: 'io-copilot.vercel.app', vercelProjekt: 'io-copilot', framework: 'Node.js + SpajaPro', buildKomanda: 'tsc' },
  },
  {
    id: 'openai-platforma',
    naziv: 'OpenAI Platforma — Digitalna Industrija',
    opis: 'SOPSTVENA platforma Digitalne Industrije — nije partner, nego interna platforma Kompanije SPAJA koja non-stop evolvira. OpenAI API integracija sa SpajaPro v6-15 endžinima i OMEGA AI sistemom. Umesto ChatGPT-a koristi se SpajaPro v6-15 engine sa naprednim Prompt sistemom. API ključ postavljen u openai-platform repozitorijumu (spaja86/openai-platform). Planovi: Starter $29/mes, Profesionalni $79/mes, Biznis $199/mes, Enterprise $499/mes, Unlimited VIP $999/mes. Povezana sa celim sistemom Digitalne Industrije za kontinuiranu evoluciju.',
    kategorija: 'ai',
    repo: 'spaja86/openai-platform',
    url: 'https://openai.com/',
    ikona: '🤖',
    status: 'spremna',
    progres: 100,
    tehnologije: ['TypeScript', 'OpenAI API', 'SpajaPro v6-15 Engine', 'OMEGA AI', 'Vercel', 'Digitalna Industrija'],
    funkcije: ['SpajaPro v6-15 umesto ChatGPT-a', 'OpenAI API integracija', 'OMEGA AI povezivanje', 'SpajaPro Prompt sistem', 'AI servisi za ekosistem', 'Vercel deploy integracija', 'Planovi: Starter/Pro/Biznis/Enterprise/Unlimited VIP', 'API ključ u repo', 'Non-stop evolucija u Digitalnoj Industriji', 'Povezana sa celim sistemom'],
    deploy: { status: 'aktivan', domen: 'openai.com', vercelProjekt: 'openai-platform', framework: 'Node.js + SpajaPro v6-15', buildKomanda: 'tsc' },
  },
  {
    id: 'omega-ai-sistem',
    naziv: 'OMEGA AI Sistem',
    opis: 'OMEGA AI centralni sistem sa 40.000.562 persona za masovno skaliranje. Link: https://chatgpt.com/c/686787a3-1168-8006-8d37-418e3e220e69. 21 persona, 8 oktava, autonomna evolucija. Koristi se svuda u ekosistemu.',
    kategorija: 'ai',
    repo: 'spaja86/AI-IQ-SUPER-PLATFORMA',
    url: 'https://ai-iq-super-platforma.vercel.app',
    ikona: '🧬',
    status: 'spremna',
    progres: 100,
    tehnologije: ['TypeScript', 'OMEGA AI', 'SpajaPro 6-15', 'Evolucija Engine', '40M persona'],
    funkcije: ['21 OMEGA AI persona', '8 oktava interakcije', 'Autonomna evolucija', '40.000.562 OMEGA AI persona', 'Masovno skaliranje', 'Cross-repo integracija'],
    deploy: { status: 'aktivan', domen: 'ai-iq-super-platforma.vercel.app', vercelProjekt: 'ai-iq-super-platforma', framework: 'Next.js 16 + OMEGA AI', buildKomanda: 'next build' },
  },
];

export function getUkupniProgres(): number {
  if (platforme.length === 0) return 0;
  const ukupno = platforme.reduce((acc, p) => acc + p.progres, 0);
  return Math.round(ukupno / platforme.length);
}

export function getPlatformePoKategoriji(kategorija: KategorijaPlatforme): Platforma[] {
  return platforme.filter((p) => p.kategorija === kategorija);
}

export function getBojaProgresa(progres: number): string {
  if (progres >= 90) return 'bg-green-500';
  if (progres >= 70) return 'bg-blue-500';
  if (progres >= 50) return 'bg-yellow-500';
  return 'bg-red-500';
}

export function getBrojAktivnih(): number {
  return platforme.filter((p) => p.status === 'aktivna' || p.status === 'spremna').length;
}
