import type { Product } from './types';

export const products: Product[] = [
  // ── Acceleration ──────────────────────────────────────────────────────
  {
    id: 'turbo-cache',
    name: 'TurboCache',
    description: 'Ultra-brzi caching layer za sve platforme u ekosistemu.',
    category: 'acceleration',
    status: 'active',
    icon: '⚡',
    version: '1.2.0',
    platformId: 'ai-iq-super',
    features: ['Edge caching', 'Cache invalidation', 'Multi-layer cache'],
    techStack: ['Redis', 'CDN', 'Edge Functions'],
  },
  {
    id: 'speed-optimizer',
    name: 'SpeedOptimizer',
    description: 'Alat za optimizaciju performansi web aplikacija.',
    category: 'acceleration',
    status: 'active',
    icon: '🚀',
    version: '2.0.0',
    features: ['Code splitting', 'Image optimization', 'Lazy loading', 'Bundle analysis'],
    techStack: ['Webpack', 'Sharp', 'Lighthouse'],
  },
  {
    id: 'load-balancer',
    name: 'LoadBalancer Pro',
    description: 'Inteligentni load balancer sa health check-ovima i auto-scaling-om.',
    category: 'acceleration',
    status: 'active',
    icon: '⚖️',
    version: '1.0.0',
    features: ['Round-robin', 'Health checks', 'Auto-scaling', 'Rate limiting'],
    techStack: ['Go', 'Docker', 'Kubernetes'],
  },
  // ── Monitoring ────────────────────────────────────────────────────────
  {
    id: 'watchdog',
    name: 'Watchdog',
    description: 'Centralizovani monitoring sistem za sve servise i platforme.',
    category: 'monitoring',
    status: 'active',
    icon: '👁️',
    version: '1.5.0',
    platformId: 'devops-tools',
    features: ['Real-time monitoring', 'Alerts', 'Dashboards', 'Log aggregation'],
    techStack: ['Grafana', 'Prometheus', 'Loki'],
  },
  {
    id: 'health-checker',
    name: 'HealthChecker',
    description: 'Automatski health check servis za praćenje dostupnosti svih platformi.',
    category: 'monitoring',
    status: 'active',
    icon: '💚',
    version: '1.1.0',
    platformId: 'devops-tools',
    features: ['Endpoint monitoring', 'Uptime tracking', 'Status pages', 'Incident alerts'],
    techStack: ['Node.js', 'Cron', 'WebSocket'],
  },
  // ── Security ──────────────────────────────────────────────────────────
  {
    id: 'shield',
    name: 'Shield',
    description: 'Security layer sa WAF-om, rate limiting-om i DDoS zaštitom.',
    category: 'security',
    status: 'active',
    icon: '🛡️',
    version: '2.1.0',
    features: ['WAF', 'Rate limiting', 'DDoS protection', 'IP blocking'],
    techStack: ['Cloudflare', 'Vercel Edge', 'Custom rules'],
  },
  {
    id: 'auth-service',
    name: 'AuthService',
    description: 'Centralizovani authentication i authorization servis.',
    category: 'security',
    status: 'active',
    icon: '🔐',
    version: '1.0.0',
    features: ['OAuth 2.0', 'JWT', 'RBAC', 'MFA', 'SSO'],
    techStack: ['Next-Auth', 'PostgreSQL', 'Redis'],
  },
  {
    id: 'vault',
    name: 'Vault',
    description: 'Sigurno skladište za API ključeve, tajne i konfiguracije.',
    category: 'security',
    status: 'active',
    icon: '🔒',
    version: '1.0.0',
    features: ['Secret management', 'Key rotation', 'Encryption at rest', 'Audit logs'],
    techStack: ['HashiCorp Vault', 'AWS KMS'],
  },
  // ── AI ────────────────────────────────────────────────────────────────
  {
    id: 'smart-assistant',
    name: 'Smart Assistant',
    description: 'AI-powered asistent za korisničku podršku i automatizaciju zadataka.',
    category: 'ai',
    status: 'active',
    icon: '🧞',
    version: '1.0.0',
    platformId: 'ai-engine',
    features: ['Chatbot', 'Task automation', 'Knowledge base', 'Multi-language'],
    techStack: ['OpenAI API', 'LangChain', 'Vector DB'],
  },
  // ── Deployment ────────────────────────────────────────────────────────
  {
    id: 'deploy-engine',
    name: 'DeployEngine',
    description: 'Automatizovani deployment pipeline za sve platforme.',
    category: 'deployment',
    status: 'active',
    icon: '🚀',
    version: '1.3.0',
    platformId: 'devops-tools',
    features: ['Auto deploy', 'Rollback', 'Preview environments', 'Blue-green deploy'],
    techStack: ['Vercel', 'GitHub Actions', 'Docker'],
  },
  {
    id: 'container-manager',
    name: 'ContainerManager',
    description: 'Upravljanje Docker kontejnerima i orkestracija servisa.',
    category: 'deployment',
    status: 'active',
    icon: '📦',
    version: '1.0.0',
    platformId: 'devops-tools',
    features: ['Container orchestration', 'Service discovery', 'Health monitoring', 'Auto-restart'],
    techStack: ['Docker', 'Kubernetes', 'Helm'],
  },
  // ── Integration ───────────────────────────────────────────────────────
  {
    id: 'api-gateway',
    name: 'API Gateway',
    description: 'Centralni API gateway za sve mikroservise u ekosistemu.',
    category: 'integration',
    status: 'active',
    icon: '🔗',
    version: '1.4.0',
    platformId: 'ai-iq-super',
    features: ['Routing', 'Auth', 'Rate limiting', 'Logging', 'Versioning'],
    techStack: ['Next.js API Routes', 'Middleware', 'Edge Functions'],
  },
  {
    id: 'event-bus',
    name: 'EventBus',
    description: 'Event-driven messaging sistem za komunikaciju između servisa.',
    category: 'integration',
    status: 'active',
    icon: '📡',
    version: '1.0.0',
    features: ['Pub/Sub', 'Event sourcing', 'Dead letter queue', 'Retry logic'],
    techStack: ['Redis Streams', 'WebSocket', 'NATS'],
  },
  {
    id: 'data-sync',
    name: 'DataSync',
    description: 'Sinhronizacija podataka između platformi i servisa u realnom vremenu.',
    category: 'integration',
    status: 'active',
    icon: '🔄',
    version: '1.0.0',
    features: ['Real-time sync', 'Conflict resolution', 'Offline support', 'Webhooks'],
    techStack: ['CRDTs', 'WebSocket', 'PostgreSQL'],
  },
  // ── Data ──────────────────────────────────────────────────────────────
  {
    id: 'spaja-baza',
    name: 'SPAJA BAZA',
    description: 'Beskonačna baza podataka Kompanije SPAJA — korisnik može da manevriše i ispisuje do iznemoglosti kroz 16 kategorija znanja. Kapacitet: ∞.',
    category: 'data',
    status: 'active',
    icon: '🗃️',
    version: '1.0.0',
    platformId: 'ai-iq-super',
    features: [
      'Beskonačan kapacitet (∞)',
      '16 kategorija znanja',
      '16 indeksa sa ∞ zapisa',
      'Dubina pretrage do 512 nivoa',
      'SPAJA-∞-Kompresija',
      'Brzina pretrage <1ms',
      'Integracija sa SpajaPro v6-v15',
      'Manevrisanje do iznemoglosti',
      'Beskonačne sesije',
    ],
    techStack: ['SPAJA-∞-Engine', 'Distributed Storage', 'CRDT', 'Vector DB', 'Graph DB'],
  },
  {
    id: 'data-warehouse',
    name: 'DataWarehouse',
    description: 'Centralno skladište podataka za analitiku i izveštavanje.',
    category: 'data',
    status: 'active',
    icon: '🗄️',
    version: '1.0.0',
    features: ['ETL pipelines', 'Data modeling', 'Query optimization', 'Partitioning'],
    techStack: ['PostgreSQL', 'BigQuery', 'dbt'],
  },
  // ── Communication ─────────────────────────────────────────────────────
  {
    id: 'messenger',
    name: 'Messenger',
    description: 'Real-time messaging servis za komunikaciju unutar ekosistema.',
    category: 'communication',
    status: 'active',
    icon: '💬',
    version: '1.0.0',
    platformId: 'social-network',
    features: ['1-on-1 chat', 'Group chat', 'File sharing', 'Video calls'],
    techStack: ['WebRTC', 'Socket.IO', 'Redis'],
  },
  // ── Analytics ─────────────────────────────────────────────────────────
  {
    id: 'analytics-engine',
    name: 'AnalyticsEngine',
    description: 'Motor za prikupljanje i analizu korisničkih i poslovnih podataka.',
    category: 'analytics',
    status: 'active',
    icon: '📈',
    version: '1.0.0',
    platformId: 'ai-analytics',
    features: ['Event tracking', 'Funnels', 'Cohort analysis', 'Custom dashboards'],
    techStack: ['ClickHouse', 'Next.js', 'D3.js'],
  },
  // ── Digitalni Hardver (as-a-Service) ──────────────────────────────────
  {
    id: 'digitalni-kompjuter',
    name: 'Digitalni Kompjuter',
    description: 'Kompletni digitalni kompjuter kao usluga — uključuje GPU, RAM, matičnu ploču, skladištenje. Zakup: nedeljno, mesečno, godišnje.',
    category: 'hardware',
    status: 'active',
    icon: '🖥️',
    version: '1.0.0',
    features: [
      'Ekstremni GPU 8.700.000 jezgara',
      'RAM memorija 276.000 GB',
      'Digitalna eksterna matična ploča',
      'Digitalna grafička kartica',
      'Nedeljni zakup',
      'Mesečni zakup',
      'Godišnji zakup',
      'Igrice preko platforme',
      'Programiranje preko SpajaPro',
    ],
    techStack: ['SPAJA Cloud', 'GPU Cluster', 'Virtualizacija', 'Edge Computing'],
  },
  {
    id: 'digitalni-gpu',
    name: 'Digitalni GPU 8.700.000',
    description: 'Ekstremni digitalni GPU sa 8.700.000 jezgara za grafiku, AI, igrice i programiranje. Zakup kao usluga.',
    category: 'hardware',
    status: 'active',
    icon: '🎮',
    version: '1.0.0',
    features: [
      '8.700.000 GPU jezgara',
      'AI/ML obrada',
      'Real-time rendering',
      'Igrice na maksimalnim podešavanjima',
      'Nedeljni zakup',
      'Mesečni zakup',
      'Godišnji zakup',
    ],
    techStack: ['SPAJA GPU Cloud', 'CUDA', 'Vulkan', 'DirectX'],
  },
  {
    id: 'digitalni-ram',
    name: 'Digitalni RAM 276.000 GB',
    description: 'Ekstremna digitalna RAM memorija 276.000 GB za brze operacije i masovne kalkulacije.',
    category: 'hardware',
    status: 'active',
    icon: '💾',
    version: '1.0.0',
    features: [
      '276.000 GB kapacitet',
      'Ultra-brza memorija',
      'ECC zaštita',
      'Dinamičko skaliranje',
      'Nedeljni zakup',
      'Mesečni zakup',
      'Godišnji zakup',
    ],
    techStack: ['SPAJA Memory Cloud', 'DDR6', 'HBM3', 'NUMA'],
  },
  {
    id: 'digitalna-graficka-kartica',
    name: 'Digitalna Grafička Kartica',
    description: 'Eksterna digitalna grafička kartica za rendering, AI i igrice. Povezuje se sa Digitalnim Kompjuterom.',
    category: 'hardware',
    status: 'active',
    icon: '🎨',
    version: '1.0.0',
    features: [
      'Eksterna GPU za cloud',
      'Ray tracing',
      '8K rendering',
      'AI upscaling',
      'Nedeljni zakup',
      'Mesečni zakup',
      'Godišnji zakup',
    ],
    techStack: ['SPAJA Render Cloud', 'Ray Tracing', 'DLSS', 'Tensor Cores'],
  },
  {
    id: 'digitalna-maticna-ploca',
    name: 'Digitalna Eksterna Matična Ploča',
    description: 'Digitalna eksterna matična ploča koja povezuje sve komponente Digitalnog Kompjutera.',
    category: 'hardware',
    status: 'active',
    icon: '🔌',
    version: '1.0.0',
    features: [
      'Povezivanje svih digitalnih komponenti',
      'PCIe 6.0 virtualni slotovi',
      'Thunderbolt 5 konekcija',
      'BIOS/UEFI upravljanje',
      'Nedeljni zakup',
      'Mesečni zakup',
      'Godišnji zakup',
    ],
    techStack: ['SPAJA Board Cloud', 'PCIe 6.0', 'Thunderbolt 5', 'USB 4'],
  },
  {
    id: 'digitalni-brauzer',
    name: 'Digitalni Brauzer',
    description: 'SPAJA Digitalni Brauzer — brauzer kao usluga za bezbedan pristup internetu preko Digitalne Industrije.',
    category: 'hardware',
    status: 'active',
    icon: '🌐',
    version: '1.0.0',
    features: [
      'Bezbedan cloud brauzer',
      'Izolacija pretnji',
      'Ad-blocking',
      'VPN integracija',
      'Nedeljni zakup',
      'Mesečni zakup',
      'Godišnji zakup',
      'Pristup igricama',
      'SpajaPro Prompt u brauzeru',
    ],
    techStack: ['Chromium', 'SPAJA Proxy', 'WebRTC', 'SPAJA VPN'],
  },
  // ── Digitalni Brouvzer, Laboratorija, Render ──────────────────────────
  {
    id: 'spaja-digitalni-brouvzer',
    name: 'SPAJA Digitalni Brouvzer',
    description: 'SPAJA Digitalni Brouvzer — digitalna brauzer platforma na koju se postavlja celokupna SPAJA industrija (platforme, organizacije, korporacije, kompanije, prodavnice). Pokretan od SPAJA Generatora za Endžine.',
    category: 'integration',
    status: 'active',
    icon: '🌐',
    version: '1.0.0',
    platformId: 'ai-iq-super-platforma',
    features: [
      'Plasiranje celokupne industrije',
      'Platforme na brouvzeru',
      'Organizacije na brouvzeru',
      'Korporacije na brouvzeru',
      'Kompanije na brouvzeru',
      'Prodavnice na brouvzeru',
      'SPAJA Generator za Endžine integracija',
      'Rendering Engine',
      'VPN i Ad-Block',
    ],
    techStack: ['SPAJA Generator Engine', 'Chromium', 'Next.js', 'Edge Functions', 'WebRTC'],
  },
  {
    id: 'io-openui-ao-gaming-platforma',
    name: 'IO/OPENUI/AO Gaming Platforma',
    description: 'IO/OPENUI/AO Gaming Platforma — 95 igrica sa SPAJA Univerzalnim Endžinom u 18 kategorija. Dimenzionalno renderovanje 360D-5760D. Pokretana od SPAJA Generatora za Endžine.',
    category: 'integration',
    status: 'active',
    icon: '🎮',
    version: '1.0.0',
    platformId: 'io-openui-ao',
    features: [
      '95 igrica u 18 kategorija',
      'SPAJA Univerzalni Endžin 100% pokrivenost',
      'Dimenzionalno renderovanje 360D-5760D',
      'Akcija, Avantura, RPG, Strategija, MMO kategorije',
      'OMEGA AI persona integracija',
      'SpajaPro 6-15 Prompt podrška',
      'Proksi mreža optimizacija',
      'Digitalni Kompjuter + Brauzer podrška',
      'SPAJA Generator za Endžine integracija',
    ],
    techStack: ['SPAJA Universal Engine', 'WebGL', 'WebGPU', 'React', 'Next.js', 'Vercel'],
  },
  {
    id: 'io-openui-ao-laboratorija',
    name: 'IOOpenUIAO Laboratorija za Simulacije',
    description: 'IOOpenUIAO Laboratorija za Simulacije — naučna i tehnička simulaciona laboratorija sa 8 kategorija simulacija. Pokretana od SPAJA Generatora za Endžine.',
    category: 'ai',
    status: 'active',
    icon: '🔬',
    version: '1.0.0',
    platformId: 'io-openui-ao',
    features: [
      'Kvantna fizika simulacije',
      'Hemijske reakcije',
      'Biološka evolucija',
      'AI neuronska mreža trening',
      'Ekonomski modeli',
      'Inženjersko testiranje',
      'Laboratorijski alati',
      'Vizualizacija 3D',
      'SPAJA Generator za Endžine integracija',
    ],
    techStack: ['SPAJA Generator Engine', 'WebGL', 'TensorFlow', 'Three.js', 'Python'],
  },
  {
    id: 'spaja-render-medija',
    name: 'SPAJA Render za Slike i Video',
    description: 'SPAJA Render za Slike i Video — render sistem za slike, video, animacije, 3D modele, vektorsku grafiku, holograme i VR/AR. Manifestovan kroz SPAJA Generator za Endžine.',
    category: 'integration',
    status: 'active',
    icon: '🎬',
    version: '1.0.0',
    platformId: 'ai-iq-super-platforma',
    features: [
      'Slike HD/4K/8K rendering',
      'Video rendering do 16K',
      'Animacioni render',
      '3D model render',
      'Vektorska grafika',
      'Hologramski render',
      'VR/AR render',
      'AI upscaling',
      'Dimenzionalni render 360D-5760D',
      'SPAJA Generator za Endžine integracija',
    ],
    techStack: ['SPAJA Generator Engine', 'WebGL', 'Vulkan', 'CUDA', 'FFmpeg', 'Sharp'],
  },
  // ── Digitalne Varijacije — Nabavka iz AI IQ World Bank ────────────────
  {
    id: 'digitalni-biskop',
    name: 'Digitalni Biskop',
    description: 'Dijagonalni AI advisor za strateško planiranje — analizira sve putanje i daje dijagonalne preporuke.',
    category: 'ai',
    status: 'active',
    icon: '♗',
    version: '1.0.0',
    platformId: 'ai-iq-super',
    features: ['Strateško planiranje', 'Dijagonalna analitika', 'AI savetovanje', 'Pattern recognition'],
    techStack: ['OMEGA AI', 'SpajaPro', 'TensorFlow'],
  },
  {
    id: 'digitalni-top',
    name: 'Digitalni Top (Rook)',
    description: 'Linearni procesni engine za vertikalne i horizontalne operacije — prava linija efikasnosti.',
    category: 'acceleration',
    status: 'active',
    icon: '♖',
    version: '1.0.0',
    features: ['Linearni procesing', 'Vertikalna optimizacija', 'Horizontalna optimizacija', 'Pipeline management'],
    techStack: ['Go', 'Kubernetes', 'gRPC'],
  },
  {
    id: 'digitalni-konj',
    name: 'Digitalni Konj (Knight)',
    description: 'L-pattern analitika za nepredvidljive tokove podataka — skače gde drugi ne mogu.',
    category: 'ai',
    status: 'active',
    icon: '♞',
    version: '1.0.0',
    features: ['L-pattern analitika', 'Nepredvidljivi tokovi', 'Kreativno rešavanje', 'Jump processing'],
    techStack: ['Python', 'PyTorch', 'OMEGA AI'],
  },
  {
    id: 'digitalna-kraljica',
    name: 'Digitalna Kraljica',
    description: 'Univerzalni multi-direkcioni engine — kombinacija svih pravaca, najmoćnija figura u sistemu.',
    category: 'ai',
    status: 'active',
    icon: '♛',
    version: '1.0.0',
    features: ['Multi-direkcioni procesing', 'Univerzalna optimizacija', 'Svi pravci', 'Maximum power'],
    techStack: ['OMEGA AI', 'SpajaPro v15', 'Kvantni procesor'],
  },
  {
    id: 'digitalni-kralj',
    name: 'Digitalni Kralj',
    description: 'Centralni zaštitni sloj sistema — poslednja linija odbrane, najvažniji entitet.',
    category: 'security',
    status: 'active',
    icon: '♚',
    version: '1.0.0',
    features: ['Centralna zaštita', 'Poslednja odbrana', 'Sistemska bezbednost', 'Royal guard'],
    techStack: ['AES-256-GCM', 'PBKDF2-SHA512', 'Zero Trust'],
  },
  {
    id: 'digitalni-pesak',
    name: 'Digitalni Pešak (Pawn)',
    description: 'Micro-servisi koji se promovišu u veće module — mali ali potencijalno moćni.',
    category: 'deployment',
    status: 'active',
    icon: '♟',
    version: '1.0.0',
    features: ['Micro-servisi', 'Auto-promocija', 'Distribuirana obrada', 'Modularnost'],
    techStack: ['Docker', 'Kubernetes', 'Serverless'],
  },
  {
    id: 'digitalni-arkade-engine',
    name: 'Digitalni Arkade Engine',
    description: 'Retro gaming platforma — klasične arkadne igrice u digitalnom formatu.',
    category: 'integration',
    status: 'active',
    icon: '🕹️',
    version: '1.0.0',
    features: ['Retro gaming', 'Arkadne igrice', 'Nostalgija platforma', 'Pixel art'],
    techStack: ['WebGL', 'Canvas API', 'SPAJA Engine'],
  },
  {
    id: 'digitalni-vr-simulacija',
    name: 'Digitalni VR Simulacija',
    description: 'Virtual Reality integracija za sve igrice i simulacije u ekosistemu.',
    category: 'integration',
    status: 'active',
    icon: '🥽',
    version: '1.0.0',
    features: ['VR igrice', 'Simulacije', 'Immersive iskustvo', '360° rendering'],
    techStack: ['WebXR', 'Three.js', 'OpenVR'],
  },
  {
    id: 'digitalni-esports-arena',
    name: 'Digitalni E-Sports Arena',
    description: 'Kompetitivni gaming modul za takmičenja, turnire i e-sports lige.',
    category: 'integration',
    status: 'active',
    icon: '🏟️',
    version: '1.0.0',
    features: ['E-sports', 'Turniri', 'Rang liste', 'Live streaming'],
    techStack: ['WebRTC', 'Socket.IO', 'Redis'],
  },
  {
    id: 'digitalni-radio',
    name: 'Digitalni Radio',
    description: 'Streaming audio platforma — radio stanice, podkastovi, muzika na zahtev.',
    category: 'communication',
    status: 'active',
    icon: '📻',
    version: '1.0.0',
    features: ['Audio streaming', 'Radio stanice', 'Podkastovi', 'Muzika na zahtev'],
    techStack: ['Web Audio API', 'HLS', 'FFmpeg'],
  },
  {
    id: 'digitalni-telegram',
    name: 'Digitalni Telegram',
    description: 'Instant messaging sistem sa end-to-end enkripcijom.',
    category: 'communication',
    status: 'active',
    icon: '✈️',
    version: '1.0.0',
    features: ['Instant messaging', 'E2E enkripcija', 'Grupni chat', 'File sharing'],
    techStack: ['WebSocket', 'Signal Protocol', 'Redis'],
  },
  {
    id: 'digitalni-forum',
    name: 'Digitalni Forum',
    description: 'Community diskusiona platforma — forum za korisnike i developere.',
    category: 'communication',
    status: 'active',
    icon: '🗣️',
    version: '1.0.0',
    features: ['Community', 'Diskusije', 'Q&A', 'Moderacija'],
    techStack: ['Next.js', 'PostgreSQL', 'Full-text search'],
  },
  {
    id: 'digitalni-podcast',
    name: 'Digitalni Podcast',
    description: 'Audio sadržaj platforma — snimanje, editovanje, distribucija podkasta.',
    category: 'communication',
    status: 'active',
    icon: '🎙️',
    version: '1.0.0',
    features: ['Podkast produkcija', 'Distribucija', 'RSS', 'Analitika'],
    techStack: ['FFmpeg', 'RSS', 'CDN'],
  },
  {
    id: 'digitalni-cloud-fabric',
    name: 'Digitalni Cloud Fabric',
    description: 'Multi-cloud orchestration — upravljanje resursima preko više cloud provajdera.',
    category: 'deployment',
    status: 'active',
    icon: '☁️',
    version: '1.0.0',
    features: ['Multi-cloud', 'Resource management', 'Auto-scaling', 'Cost optimization'],
    techStack: ['Terraform', 'Kubernetes', 'Pulumi'],
  },
  {
    id: 'digitalni-edge-node',
    name: 'Digitalni Edge Node',
    description: 'Edge computing čvor mreža — distribuirana obrada na rubovima mreže.',
    category: 'acceleration',
    status: 'active',
    icon: '🌍',
    version: '1.0.0',
    features: ['Edge computing', 'Distribuirana obrada', 'Niža latencija', 'CDN integracija'],
    techStack: ['Vercel Edge', 'Cloudflare Workers', 'Deno Deploy'],
  },
  {
    id: 'digitalni-dns-engine',
    name: 'Digitalni DNS Engine',
    description: 'Interni DNS resolver — brzo razrešavanje domena unutar ekosistema.',
    category: 'acceleration',
    status: 'active',
    icon: '🔗',
    version: '1.0.0',
    features: ['DNS resolving', 'Interni routing', 'Domen management', 'GeoDNS'],
    techStack: ['CoreDNS', 'BIND', 'Redis'],
  },
  {
    id: 'digitalni-cdn',
    name: 'Digitalni CDN',
    description: 'Content Delivery Network — brza isporuka sadržaja korisnicima širom sveta.',
    category: 'acceleration',
    status: 'active',
    icon: '🌐',
    version: '1.0.0',
    features: ['Content delivery', 'Globalna distribucija', 'Cache', 'Image optimization'],
    techStack: ['Vercel CDN', 'Cloudflare', 'Edge Functions'],
  },
  {
    id: 'digitalni-load-balancer-plus',
    name: 'Digitalni Load Balancer Plus',
    description: 'Napredni traffic management sa AI predviđanjem opterećenja.',
    category: 'acceleration',
    status: 'active',
    icon: '⚖️',
    version: '1.0.0',
    features: ['AI load balancing', 'Predviđanje', 'Auto-scaling', 'Health checks'],
    techStack: ['Go', 'Kubernetes', 'Prometheus'],
  },
  {
    id: 'digitalna-akademija',
    name: 'Digitalna Akademija',
    description: 'E-learning platforma — kursevi, certifikati, mentorstvo.',
    category: 'integration',
    status: 'active',
    icon: '🎓',
    version: '1.0.0',
    features: ['E-learning', 'Kursevi', 'Certifikati', 'Video lekcije'],
    techStack: ['Next.js', 'Mux', 'Stripe'],
  },
  {
    id: 'digitalni-mentor',
    name: 'Digitalni Mentor',
    description: 'AI tutoring sistem — personalizovano mentorstvo za svakog korisnika.',
    category: 'ai',
    status: 'active',
    icon: '👨‍🏫',
    version: '1.0.0',
    features: ['AI tutoring', 'Personalizovano učenje', 'Adaptivna edukacija', 'Praćenje napretka'],
    techStack: ['OpenAI', 'SpajaPro', 'Vector DB'],
  },
  {
    id: 'digitalna-biblioteka',
    name: 'Digitalna Biblioteka',
    description: 'Digitalni arhiv i dokumentacija — beskonačna baza znanja.',
    category: 'data',
    status: 'active',
    icon: '📚',
    version: '1.0.0',
    features: ['Digitalni arhiv', 'Baza znanja', 'Dokumentacija', 'Full-text pretraga'],
    techStack: ['Elasticsearch', 'PostgreSQL', 'S3'],
  },
  {
    id: 'digitalni-certifikat-engine',
    name: 'Digitalni Certifikat Engine',
    description: 'Sertifikacioni modul — kreiranje i izdavanje digitalnih certifikata.',
    category: 'security',
    status: 'active',
    icon: '📜',
    version: '1.0.0',
    features: ['Digitalni certifikati', 'Verifikacija', 'Blockchain potpis', 'QR kodovi'],
    techStack: ['Blockchain', 'X.509', 'PDF generation'],
  },
  {
    id: 'digitalni-crm',
    name: 'Digitalni CRM',
    description: 'Customer Relationship Management — upravljanje odnosima sa klijentima.',
    category: 'integration',
    status: 'active',
    icon: '👥',
    version: '1.0.0',
    features: ['CRM', 'Pipeline', 'Analitika', 'Email automatizacija'],
    techStack: ['Next.js', 'PostgreSQL', 'Redis', 'Stripe'],
  },
  {
    id: 'digitalni-erp',
    name: 'Digitalni ERP',
    description: 'Enterprise Resource Planning — upravljanje svim resursima Digitalne Industrije.',
    category: 'integration',
    status: 'active',
    icon: '🏢',
    version: '1.0.0',
    features: ['ERP', 'Finansije', 'HR', 'Logistika', 'Inventar'],
    techStack: ['Next.js', 'PostgreSQL', 'Kubernetes'],
  },
  {
    id: 'digitalni-invoice-generator',
    name: 'Digitalni Invoice Generator',
    description: 'Automatsko fakturisanje — generisanje, slanje i praćenje faktura.',
    category: 'integration',
    status: 'active',
    icon: '🧾',
    version: '1.0.0',
    features: ['Fakturisanje', 'PDF generisanje', 'Praćenje plaćanja', 'Automatizacija'],
    techStack: ['PDF.js', 'Stripe', 'SMTP'],
  },
  {
    id: 'digitalni-hr-platforma',
    name: 'Digitalni HR Platforma',
    description: 'Upravljanje ljudskim resursima — HR, regrutacija, plate.',
    category: 'integration',
    status: 'active',
    icon: '👔',
    version: '1.0.0',
    features: ['HR management', 'Regrutacija', 'Plate', 'Timski rad'],
    techStack: ['Next.js', 'PostgreSQL', 'Stripe'],
  },
  {
    id: 'digitalni-tender-engine',
    name: 'Digitalni Tender Engine',
    description: 'Sistem za digitalne tendere — kreiranje i evaluacija tendera.',
    category: 'integration',
    status: 'active',
    icon: '📋',
    version: '1.0.0',
    features: ['Digitalni tenderi', 'Evaluacija ponuda', 'Javne nabavke', 'Dokumentacija'],
    techStack: ['Next.js', 'PostgreSQL', 'PDF generation'],
  },
  {
    id: 'digitalni-smart-contract',
    name: 'Digitalni Ugovor (Smart Contract)',
    description: 'Blockchain ugovori — digitalno potpisivanje i izvršavanje ugovora.',
    category: 'security',
    status: 'active',
    icon: '📝',
    version: '1.0.0',
    features: ['Smart contracts', 'Blockchain', 'Digitalno potpisivanje', 'Automatsko izvršavanje'],
    techStack: ['Ethereum', 'Solidity', 'Web3.js'],
  },
  {
    id: 'digitalni-firewall',
    name: 'Digitalni Firewall',
    description: 'Napredni WAF modul — zaštita od napada, filtriranje saobraćaja.',
    category: 'security',
    status: 'active',
    icon: '🔥',
    version: '1.0.0',
    features: ['WAF', 'Firewall', 'DDoS zaštita', 'IP filtriranje'],
    techStack: ['Cloudflare', 'iptables', 'ModSecurity'],
  },
  {
    id: 'digitalni-vpn-gateway',
    name: 'Digitalni VPN Gateway',
    description: 'Šifrovani tunel za podatke — bezbedan pristup sa bilo kog mesta.',
    category: 'security',
    status: 'active',
    icon: '🔐',
    version: '1.0.0',
    features: ['VPN', 'Šifrovani tunel', 'Remote access', 'Split tunneling'],
    techStack: ['WireGuard', 'OpenVPN', 'IPsec'],
  },
  {
    id: 'digitalni-antivirus',
    name: 'Digitalni Antivirus Engine',
    description: 'AI-powered detekcija pretnji i malvera.',
    category: 'security',
    status: 'active',
    icon: '🦠',
    version: '1.0.0',
    features: ['AI detekcija', 'Skeniranje pretnji', 'Real-time zaštita', 'Malware analiza'],
    techStack: ['YARA', 'ClamAV', 'TensorFlow'],
  },
  {
    id: 'digitalna-forenzika',
    name: 'Digitalna Forenzika',
    description: 'Digitalna forenzička analitika — istraga incidenata i analiza tragova.',
    category: 'security',
    status: 'active',
    icon: '🔎',
    version: '1.0.0',
    features: ['Digitalna forenzika', 'Istraga incidenata', 'Log analiza', 'Evidencija'],
    techStack: ['ELK Stack', 'Volatility', 'Autopsy'],
  },
  {
    id: 'digitalni-dizajn-studio',
    name: 'Digitalni Dizajn Studio',
    description: 'UI/UX alat za dizajniranje interfejsa i prototipova.',
    category: 'integration',
    status: 'active',
    icon: '🎨',
    version: '1.0.0',
    features: ['UI/UX dizajn', 'Wireframe', 'Prototipovanje', 'Stilski vodič'],
    techStack: ['Figma API', 'Canvas', 'SVG'],
  },
  {
    id: 'digitalni-video-editor',
    name: 'Digitalni Video Editor',
    description: 'Video produkcija — snimanje, editovanje, efekti, rendering.',
    category: 'integration',
    status: 'active',
    icon: '🎬',
    version: '1.0.0',
    features: ['Video editovanje', 'Efekti', 'Rendering', '4K/8K podrška'],
    techStack: ['FFmpeg', 'WebCodecs', 'Canvas'],
  },
  {
    id: 'digitalni-muzicki-studio',
    name: 'Digitalni Muzički Studio',
    description: 'Audio produkcija — snimanje, miksovanje, mastering.',
    category: 'integration',
    status: 'active',
    icon: '🎵',
    version: '1.0.0',
    features: ['Audio produkcija', 'Miksovanje', 'Mastering', 'MIDI'],
    techStack: ['Web Audio API', 'Tone.js', 'FFmpeg'],
  },
  {
    id: 'digitalni-3d-modelar',
    name: 'Digitalni 3D Modelar',
    description: '3D vizualizacija — modeliranje, renderovanje, animacija.',
    category: 'integration',
    status: 'active',
    icon: '🗿',
    version: '1.0.0',
    features: ['3D modeliranje', 'Renderovanje', 'Animacija', 'VR/AR export'],
    techStack: ['Three.js', 'WebGPU', 'Blender API'],
  },
  {
    id: 'digitalna-klinika',
    name: 'Digitalna Klinika',
    description: 'Telemedicina platforma — onlajn konsultacije, dijagnostika.',
    category: 'integration',
    status: 'active',
    icon: '🏥',
    version: '1.0.0',
    features: ['Telemedicina', 'Onlajn konsultacije', 'Dijagnostika', 'E-recepti'],
    techStack: ['WebRTC', 'HL7 FHIR', 'PostgreSQL'],
  },
  {
    id: 'digitalni-apotekar',
    name: 'Digitalni Apotekar',
    description: 'Online farmacija — naručivanje lekova i zdravstvenih proizvoda.',
    category: 'integration',
    status: 'active',
    icon: '💊',
    version: '1.0.0',
    features: ['Online farmacija', 'Naručivanje lekova', 'Delivery', 'Recepti'],
    techStack: ['Next.js', 'Stripe', 'PostgreSQL'],
  },
  {
    id: 'digitalni-fitnes-trener',
    name: 'Digitalni Fitnes Trener',
    description: 'Health & Fitness AI — personalizovani treninzi i ishrana.',
    category: 'ai',
    status: 'active',
    icon: '💪',
    version: '1.0.0',
    features: ['Fitnes', 'Treninzi', 'Ishrana', 'Praćenje napretka'],
    techStack: ['TensorFlow', 'HealthKit', 'SpajaPro'],
  },
  {
    id: 'digitalni-ambasador',
    name: 'Digitalni Ambasador',
    description: 'Diplomatski komunikacioni modul — globalno predstavljanje industrije.',
    category: 'integration',
    status: 'active',
    icon: '🌎',
    version: '1.0.0',
    features: ['Diplomatija', 'Globalno predstavljanje', 'Partnerstva', 'PR'],
    techStack: ['Next.js', 'i18n', 'CRM'],
  },
  {
    id: 'digitalni-prevodilac',
    name: 'Digitalni Prevodilac',
    description: 'Multi-jezički AI prevodilac — prevođenje na 100+ jezika.',
    category: 'ai',
    status: 'active',
    icon: '🌐',
    version: '1.0.0',
    features: ['AI prevođenje', '100+ jezika', 'Real-time', 'Lokalizacija'],
    techStack: ['OpenAI', 'DeepL API', 'SpajaPro'],
  },
  {
    id: 'digitalni-turisticki-vodic',
    name: 'Digitalni Turistički Vodič',
    description: 'Turizam platforma — virtuelni obilasci i preporuke.',
    category: 'integration',
    status: 'active',
    icon: '🗺️',
    version: '1.0.0',
    features: ['Turizam', 'Virtuelni obilasci', 'Preporuke', 'Rezervacije'],
    techStack: ['Maps API', 'Three.js', 'Stripe'],
  },
  {
    id: 'digitalna-posta',
    name: 'Digitalna Pošta',
    description: 'Digital mail i delivery — slanje paketa i digitalnih pošiljki.',
    category: 'communication',
    status: 'active',
    icon: '📮',
    version: '1.0.0',
    features: ['Digitalna pošta', 'Paketi', 'Tracking', 'E-pismo'],
    techStack: ['SMTP', 'S3', 'Tracking API'],
  },
  {
    id: 'digitalna-berza',
    name: 'Digitalna Berza',
    description: 'Stock exchange modul — trgovanje digitalnim akcijama i tokenima.',
    category: 'integration',
    status: 'active',
    icon: '📊',
    version: '1.0.0',
    features: ['Berza', 'Digitalno trgovanje', 'Akcije', 'Tokeni'],
    techStack: ['WebSocket', 'Redis', 'PostgreSQL', 'Chart.js'],
  },
  {
    id: 'digitalna-laboratorija-plus',
    name: 'Digitalna Laboratorija Plus',
    description: 'Proširena simulaciona lab — napredni eksperimenti.',
    category: 'ai',
    status: 'active',
    icon: '🔬',
    version: '1.0.0',
    features: ['Napredne simulacije', 'AI istraživanja', 'Eksperimenti', 'Vizualizacija'],
    techStack: ['TensorFlow', 'Three.js', 'Python'],
  },
  {
    id: 'digitalna-observatorija',
    name: 'Digitalna Observatorija',
    description: 'Astronomski AI modul — posmatranje svemira i simulacija nebeskih tela.',
    category: 'ai',
    status: 'active',
    icon: '🔭',
    version: '1.0.0',
    features: ['Astronomija', 'Simulacija svemira', 'Nebeska tela', 'Teleskop AI'],
    techStack: ['Three.js', 'WebGL', 'NASA API'],
  },
  {
    id: 'digitalni-genom-analizator',
    name: 'Digitalni Genom Analizator',
    description: 'Bioinformatika engine — analiza genoma i DNK sekvenciranje.',
    category: 'ai',
    status: 'active',
    icon: '🧬',
    version: '1.0.0',
    features: ['Bioinformatika', 'Genom analiza', 'DNK sekvenciranje', 'Medicinska genetika'],
    techStack: ['Python', 'BioPython', 'TensorFlow'],
  },
  {
    id: 'digitalni-kvantni-simulator',
    name: 'Digitalni Kvantni Simulator',
    description: 'Kvantna simulacija — simuliranje kvantnih sistema i eksperimenata.',
    category: 'ai',
    status: 'active',
    icon: '⚛️',
    version: '1.0.0',
    features: ['Kvantna simulacija', 'Kvantni eksperimenti', 'Kvantna kriptografija', 'Qubiti'],
    techStack: ['Qiskit', 'Cirq', 'PennyLane'],
  },
  {
    id: 'digitalni-logistika-engine',
    name: 'Digitalni Logistika Engine',
    description: 'Supply chain management — upravljanje lancem snabdevanja.',
    category: 'integration',
    status: 'active',
    icon: '🚚',
    version: '1.0.0',
    features: ['Logistika', 'Supply chain', 'Dostava', 'Skladištenje'],
    techStack: ['Next.js', 'Maps API', 'PostgreSQL'],
  },
  {
    id: 'digitalni-fleet-manager',
    name: 'Digitalni Fleet Manager',
    description: 'Upravljanje voznim parkom — praćenje vozila i optimizacija ruta.',
    category: 'integration',
    status: 'active',
    icon: '🚗',
    version: '1.0.0',
    features: ['Fleet management', 'GPS praćenje', 'Optimizacija ruta', 'Troškovi'],
    techStack: ['Maps API', 'IoT', 'PostgreSQL'],
  },
];

export const productCategories: Record<string, { label: string; icon: string }> = {
  acceleration: { label: 'Ubrzanje', icon: '⚡' },
  monitoring: { label: 'Monitoring', icon: '👁️' },
  security: { label: 'Bezbednost', icon: '🛡️' },
  ai: { label: 'AI & ML', icon: '🤖' },
  deployment: { label: 'Deployment', icon: '🚀' },
  integration: { label: 'Integracija', icon: '🔗' },
  data: { label: 'Podaci', icon: '🗄️' },
  communication: { label: 'Komunikacija', icon: '💬' },
  analytics: { label: 'Analitika', icon: '📈' },
  automation: { label: 'Automatizacija', icon: '⚙️' },
  hardware: { label: 'Digitalni Hardver', icon: '🖥️' },
};

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getActiveProducts(): Product[] {
  return products.filter((p) => p.status === 'active');
}

export function getProductsByPlatform(platformId: string): Product[] {
  return products.filter((p) => p.platformId === platformId);
}
