import type { Product } from './types';

export const products: Product[] = [
  // ── Acceleration ──────────────────────────────────────────────────────
  {
    id: 'turbo-cache',
    name: 'TurboCache',
    description: 'Ultra-brzi caching layer za sve platforme u ekosistemu.',
    category: 'acceleration',
    status: 'active',
    icon: '⚡',
    version: '1.2.0',
    platformId: 'ai-iq-super',
    features: ['Edge caching', 'Cache invalidation', 'Multi-layer cache'],
    techStack: ['Redis', 'CDN', 'Edge Functions'],
  },
  {
    id: 'speed-optimizer',
    name: 'SpeedOptimizer',
    description: 'Alat za optimizaciju performansi web aplikacija.',
    category: 'acceleration',
    status: 'active',
    icon: '🚀',
    version: '2.0.0',
    features: ['Code splitting', 'Image optimization', 'Lazy loading', 'Bundle analysis'],
    techStack: ['Webpack', 'Sharp', 'Lighthouse'],
  },
  {
    id: 'load-balancer',
    name: 'LoadBalancer Pro',
    description: 'Inteligentni load balancer sa health check-ovima i auto-scaling-om.',
    category: 'acceleration',
    status: 'active',
    icon: '⚖️',
    version: '1.0.0',
    features: ['Round-robin', 'Health checks', 'Auto-scaling', 'Rate limiting'],
    techStack: ['Go', 'Docker', 'Kubernetes'],
  },
  // ── Monitoring ────────────────────────────────────────────────────────
  {
    id: 'watchdog',
    name: 'Watchdog',
    description: 'Centralizovani monitoring sistem za sve servise i platforme.',
    category: 'monitoring',
    status: 'active',
    icon: '👁️',
    version: '1.5.0',
    platformId: 'devops-tools',
    features: ['Real-time monitoring', 'Alerts', 'Dashboards', 'Log aggregation'],
    techStack: ['Grafana', 'Prometheus', 'Loki'],
  },
  {
    id: 'health-checker',
    name: 'HealthChecker',
    description: 'Automatski health check servis za praćenje dostupnosti svih platformi.',
    category: 'monitoring',
    status: 'active',
    icon: '💚',
    version: '1.1.0',
    platformId: 'devops-tools',
    features: ['Endpoint monitoring', 'Uptime tracking', 'Status pages', 'Incident alerts'],
    techStack: ['Node.js', 'Cron', 'WebSocket'],
  },
  // ── Security ──────────────────────────────────────────────────────────
  {
    id: 'shield',
    name: 'Shield',
    description: 'Security layer sa WAF-om, rate limiting-om i DDoS zaštitom.',
    category: 'security',
    status: 'active',
    icon: '🛡️',
    version: '2.1.0',
    features: ['WAF', 'Rate limiting', 'DDoS protection', 'IP blocking'],
    techStack: ['Cloudflare', 'Vercel Edge', 'Custom rules'],
  },
  {
    id: 'auth-service',
    name: 'AuthService',
    description: 'Centralizovani authentication i authorization servis.',
    category: 'security',
    status: 'active',
    icon: '🔐',
    version: '1.0.0',
    features: ['OAuth 2.0', 'JWT', 'RBAC', 'MFA', 'SSO'],
    techStack: ['Next-Auth', 'PostgreSQL', 'Redis'],
  },
  {
    id: 'vault',
    name: 'Vault',
    description: 'Sigurno skladište za API ključeve, tajne i konfiguracije.',
    category: 'security',
    status: 'active',
    icon: '🔒',
    version: '1.0.0',
    features: ['Secret management', 'Key rotation', 'Encryption at rest', 'Audit logs'],
    techStack: ['HashiCorp Vault', 'AWS KMS'],
  },
  // ── AI ────────────────────────────────────────────────────────────────
  {
    id: 'smart-assistant',
    name: 'Smart Assistant',
    description: 'AI-powered asistent za korisničku podršku i automatizaciju zadataka.',
    category: 'ai',
    status: 'active',
    icon: '🧞',
    version: '1.0.0',
    platformId: 'ai-engine',
    features: ['Chatbot', 'Task automation', 'Knowledge base', 'Multi-language'],
    techStack: ['OpenAI API', 'LangChain', 'Vector DB'],
  },
  // ── Deployment ────────────────────────────────────────────────────────
  {
    id: 'deploy-engine',
    name: 'DeployEngine',
    description: 'Automatizovani deployment pipeline za sve platforme.',
    category: 'deployment',
    status: 'active',
    icon: '🚀',
    version: '1.3.0',
    platformId: 'devops-tools',
    features: ['Auto deploy', 'Rollback', 'Preview environments', 'Blue-green deploy'],
    techStack: ['Vercel', 'GitHub Actions', 'Docker'],
  },
  {
    id: 'container-manager',
    name: 'ContainerManager',
    description: 'Upravljanje Docker kontejnerima i orkestracija servisa.',
    category: 'deployment',
    status: 'active',
    icon: '📦',
    version: '1.0.0',
    platformId: 'devops-tools',
    features: ['Container orchestration', 'Service discovery', 'Health monitoring', 'Auto-restart'],
    techStack: ['Docker', 'Kubernetes', 'Helm'],
  },
  // ── Integration ───────────────────────────────────────────────────────
  {
    id: 'api-gateway',
    name: 'API Gateway',
    description: 'Centralni API gateway za sve mikroservise u ekosistemu.',
    category: 'integration',
    status: 'active',
    icon: '🔗',
    version: '1.4.0',
    platformId: 'ai-iq-super',
    features: ['Routing', 'Auth', 'Rate limiting', 'Logging', 'Versioning'],
    techStack: ['Next.js API Routes', 'Middleware', 'Edge Functions'],
  },
  {
    id: 'event-bus',
    name: 'EventBus',
    description: 'Event-driven messaging sistem za komunikaciju između servisa.',
    category: 'integration',
    status: 'active',
    icon: '📡',
    version: '1.0.0',
    features: ['Pub/Sub', 'Event sourcing', 'Dead letter queue', 'Retry logic'],
    techStack: ['Redis Streams', 'WebSocket', 'NATS'],
  },
  {
    id: 'data-sync',
    name: 'DataSync',
    description: 'Sinhronizacija podataka između platformi i servisa u realnom vremenu.',
    category: 'integration',
    status: 'active',
    icon: '🔄',
    version: '1.0.0',
    features: ['Real-time sync', 'Conflict resolution', 'Offline support', 'Webhooks'],
    techStack: ['CRDTs', 'WebSocket', 'PostgreSQL'],
  },
  // ── Data ──────────────────────────────────────────────────────────────
  {
    id: 'spaja-baza',
    name: 'SPAJA BAZA',
    description: 'Beskonačna baza podataka Kompanije SPAJA — korisnik može da manevriše i ispisuje do iznemoglosti kroz 16 kategorija znanja. Kapacitet: ∞.',
    category: 'data',
    status: 'active',
    icon: '🗃️',
    version: '1.0.0',
    platformId: 'ai-iq-super',
    features: [
      'Beskonačan kapacitet (∞)',
      '16 kategorija znanja',
      '16 indeksa sa ∞ zapisa',
      'Dubina pretrage do 512 nivoa',
      'SPAJA-∞-Kompresija',
      'Brzina pretrage <1ms',
      'Integracija sa SpajaPro v6-v15',
      'Manevrisanje do iznemoglosti',
      'Beskonačne sesije',
    ],
    techStack: ['SPAJA-∞-Engine', 'Distributed Storage', 'CRDT', 'Vector DB', 'Graph DB'],
  },
  {
    id: 'data-warehouse',
    name: 'DataWarehouse',
    description: 'Centralno skladište podataka za analitiku i izveštavanje.',
    category: 'data',
    status: 'active',
    icon: '🗄️',
    version: '1.0.0',
    features: ['ETL pipelines', 'Data modeling', 'Query optimization', 'Partitioning'],
    techStack: ['PostgreSQL', 'BigQuery', 'dbt'],
  },
  // ── Communication ─────────────────────────────────────────────────────
  {
    id: 'messenger',
    name: 'Messenger',
    description: 'Real-time messaging servis za komunikaciju unutar ekosistema.',
    category: 'communication',
    status: 'active',
    icon: '💬',
    version: '1.0.0',
    platformId: 'social-network',
    features: ['1-on-1 chat', 'Group chat', 'File sharing', 'Video calls'],
    techStack: ['WebRTC', 'Socket.IO', 'Redis'],
  },
  // ── Analytics ─────────────────────────────────────────────────────────
  {
    id: 'analytics-engine',
    name: 'AnalyticsEngine',
    description: 'Motor za prikupljanje i analizu korisničkih i poslovnih podataka.',
    category: 'analytics',
    status: 'active',
    icon: '📈',
    version: '1.0.0',
    platformId: 'ai-analytics',
    features: ['Event tracking', 'Funnels', 'Cohort analysis', 'Custom dashboards'],
    techStack: ['ClickHouse', 'Next.js', 'D3.js'],
  },
  // ── Digitalni Hardver (as-a-Service) ──────────────────────────────────
  {
    id: 'digitalni-kompjuter',
    name: 'Digitalni Kompjuter',
    description: 'Kompletni digitalni kompjuter kao usluga — uključuje GPU, RAM, matičnu ploču, skladištenje. Zakup: nedeljno, mesečno, godišnje.',
    category: 'hardware',
    status: 'active',
    icon: '🖥️',
    version: '1.0.0',
    features: [
      'Ekstremni GPU 8.700.000 jezgara',
      'RAM memorija 276.000 GB',
      'Digitalna eksterna matična ploča',
      'Digitalna grafička kartica',
      'Nedeljni zakup',
      'Mesečni zakup',
      'Godišnji zakup',
      'Igrice preko platforme',
      'Programiranje preko SpajaPro',
    ],
    techStack: ['SPAJA Cloud', 'GPU Cluster', 'Virtualizacija', 'Edge Computing'],
  },
  {
    id: 'digitalni-gpu',
    name: 'Digitalni GPU 8.700.000',
    description: 'Ekstremni digitalni GPU sa 8.700.000 jezgara za grafiku, AI, igrice i programiranje. Zakup kao usluga.',
    category: 'hardware',
    status: 'active',
    icon: '🎮',
    version: '1.0.0',
    features: [
      '8.700.000 GPU jezgara',
      'AI/ML obrada',
      'Real-time rendering',
      'Igrice na maksimalnim podešavanjima',
      'Nedeljni zakup',
      'Mesečni zakup',
      'Godišnji zakup',
    ],
    techStack: ['SPAJA GPU Cloud', 'CUDA', 'Vulkan', 'DirectX'],
  },
  {
    id: 'digitalni-ram',
    name: 'Digitalni RAM 276.000 GB',
    description: 'Ekstremna digitalna RAM memorija 276.000 GB za brze operacije i masovne kalkulacije.',
    category: 'hardware',
    status: 'active',
    icon: '💾',
    version: '1.0.0',
    features: [
      '276.000 GB kapacitet',
      'Ultra-brza memorija',
      'ECC zaštita',
      'Dinamičko skaliranje',
      'Nedeljni zakup',
      'Mesečni zakup',
      'Godišnji zakup',
    ],
    techStack: ['SPAJA Memory Cloud', 'DDR6', 'HBM3', 'NUMA'],
  },
  {
    id: 'digitalna-graficka-kartica',
    name: 'Digitalna Grafička Kartica',
    description: 'Eksterna digitalna grafička kartica za rendering, AI i igrice. Povezuje se sa Digitalnim Kompjuterom.',
    category: 'hardware',
    status: 'active',
    icon: '🎨',
    version: '1.0.0',
    features: [
      'Eksterna GPU za cloud',
      'Ray tracing',
      '8K rendering',
      'AI upscaling',
      'Nedeljni zakup',
      'Mesečni zakup',
      'Godišnji zakup',
    ],
    techStack: ['SPAJA Render Cloud', 'Ray Tracing', 'DLSS', 'Tensor Cores'],
  },
  {
    id: 'digitalna-maticna-ploca',
    name: 'Digitalna Eksterna Matična Ploča',
    description: 'Digitalna eksterna matična ploča koja povezuje sve komponente Digitalnog Kompjutera.',
    category: 'hardware',
    status: 'active',
    icon: '🔌',
    version: '1.0.0',
    features: [
      'Povezivanje svih digitalnih komponenti',
      'PCIe 6.0 virtualni slotovi',
      'Thunderbolt 5 konekcija',
      'BIOS/UEFI upravljanje',
      'Nedeljni zakup',
      'Mesečni zakup',
      'Godišnji zakup',
    ],
    techStack: ['SPAJA Board Cloud', 'PCIe 6.0', 'Thunderbolt 5', 'USB 4'],
  },
  {
    id: 'digitalni-brauzer',
    name: 'Digitalni Brauzer',
    description: 'SPAJA Digitalni Brauzer — brauzer kao usluga za bezbedan pristup internetu preko Digitalne Industrije.',
    category: 'hardware',
    status: 'active',
    icon: '🌐',
    version: '1.0.0',
    features: [
      'Bezbedan cloud brauzer',
      'Izolacija pretnji',
      'Ad-blocking',
      'VPN integracija',
      'Nedeljni zakup',
      'Mesečni zakup',
      'Godišnji zakup',
      'Pristup igricama',
      'SpajaPro Prompt u brauzeru',
    ],
    techStack: ['Chromium', 'SPAJA Proxy', 'WebRTC', 'SPAJA VPN'],
  },
];

export const productCategories: Record<string, { label: string; icon: string }> = {
  acceleration: { label: 'Ubrzanje', icon: '⚡' },
  monitoring: { label: 'Monitoring', icon: '👁️' },
  security: { label: 'Bezbednost', icon: '🛡️' },
  ai: { label: 'AI & ML', icon: '🤖' },
  deployment: { label: 'Deployment', icon: '🚀' },
  integration: { label: 'Integracija', icon: '🔗' },
  data: { label: 'Podaci', icon: '🗄️' },
  communication: { label: 'Komunikacija', icon: '💬' },
  analytics: { label: 'Analitika', icon: '📈' },
  automation: { label: 'Automatizacija', icon: '⚙️' },
  hardware: { label: 'Digitalni Hardver', icon: '🖥️' },
};

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getActiveProducts(): Product[] {
  return products.filter((p) => p.status === 'active');
}

export function getProductsByPlatform(platformId: string): Product[] {
  return products.filter((p) => p.platformId === platformId);
}
