import { Repository } from './types';

export const repositories: Repository[] = [
  {
    id: 'ai-iq-super-platforma',
    name: 'AI-IQ-SUPER-PLATFORMA',
    fullName: 'spaja86/AI-IQ-SUPER-PLATFORMA',
    description: 'Platforma za spajanje ekstremno mnogo platformi koja u budućnosti treba da izraste u korporaciju.',
    url: 'https://github.com/spaja86/AI-IQ-SUPER-PLATFORMA',
    language: 'TypeScript',
    status: 'active',
    category: 'platform',
    technologies: ['Next.js 16', 'TypeScript', 'Tailwind CSS 4', 'React 19', 'Vercel'],
    features: ['Unified dashboard', 'All platforms integrated', 'API routes', 'SEO optimized', 'Production deployment'],
  },
  {
    id: 'io-openui-ao',
    name: 'IO-OPENUI-AO',
    fullName: 'spaja86/IO-OPENUI-AO',
    description: 'Platforma za profesionalnu saradnju, igrice i mnogo toga. Unified SPAJA ecosystem frontend sa 4 modula.',
    url: 'https://github.com/spaja86/IO-OPENUI-AO',
    language: 'HTML',
    status: 'active',
    category: 'platform',
    technologies: ['Vite', 'TypeScript', 'React', 'WebRTC', 'Socket.IO', 'OpenAI API', 'Vercel'],
    features: ['Bank module (/bank/)', 'Exchange module (/exchange/)', 'AI module (/ai/)', 'WebRTC real-time server', 'Socket.IO chat server', 'Company module (/company/)'],
  },
  {
    id: 'ai-iq-world-bank',
    name: 'Ai-Iq-World-Bank',
    fullName: 'spaja86/Ai-Iq-World-Bank',
    description: 'Najbolja banka na svetu, maksimalno profesionalna, saradnju ima sa svim bankama.',
    url: 'https://github.com/spaja86/Ai-Iq-World-Bank',
    language: 'HTML',
    status: 'active',
    category: 'finance',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    features: ['Home page', 'About section', 'Services', 'Omega AI Technology', 'Smederevo expansion', 'Partners', 'Statistics', 'Contact'],
  },
  {
    id: 'ai-iq-menjacnica',
    name: 'Ai-Iq-Menja-nica',
    fullName: 'spaja86/Ai-Iq-Menja-nica',
    description: 'Najbolja menjačnica na svetu sa najviše kripto valuta. Svetska menjačnica.',
    url: 'https://github.com/spaja86/Ai-Iq-Menja-nica',
    language: 'JavaScript',
    status: 'active',
    category: 'finance',
    technologies: ['HTML', 'CSS', 'JavaScript', 'CoinGecko API', 'ExchangeRate API'],
    features: ['BUY/SELL trading', 'EUR/RSD fiat', 'Live crypto prices', 'Search + Load More mode', 'Searchable dropdown mode', '2% fee', '1000+ cryptocurrencies'],
  },
  {
    id: 'openai-platform',
    name: 'openai-platform',
    fullName: 'spaja86/openai-platform',
    description: 'Profesionalna platforma za poslovanje, filmove, slike, igrice i još mnogo toga.',
    url: 'https://github.com/spaja86/openai-platform',
    status: 'concept',
    category: 'ai',
    technologies: ['OpenAI'],
    features: ['Business platform', 'Movies', 'Images', 'Games'],
  },
  {
    id: 'svetska-organizacija',
    name: 'SVETSKA-ORGANIZACIJA',
    fullName: 'spaja86/SVETSKA-ORGANIZACIJA',
    description: 'SVETSKA ORGANIZACIJA za dobrobit čovečanstva.',
    url: 'https://github.com/spaja86/SVETSKA-ORGANIZACIJA',
    status: 'concept',
    category: 'platform',
    technologies: [],
    features: ['Global organization', 'Humanitarian goals'],
  },
  {
    id: 'input-output-kopilot',
    name: 'Input-Output-za-kopilota',
    fullName: 'spaja86/Input-Output-za-kopilota-da-mo-e-da-komunicira-sa-korsnicima-akticno',
    description: 'Profesionalni patch za GitHub — multi-channel notification system.',
    url: 'https://github.com/spaja86/Input-Output-za-kopilota-da-mo-e-da-komunicira-sa-korsnicima-akticno',
    language: 'Python',
    status: 'active',
    category: 'tools',
    technologies: ['Python', 'GitHub Issues', 'Email', 'Discord', 'Telegram', 'Slack'],
    features: ['Multi-channel notifications', 'GitHub Issues integration', 'Email notifications', 'Discord integration', 'Telegram integration', 'Slack integration', 'Autofinis automation'],
  },
  {
    id: 'omega-ai-github',
    name: 'OMEGA-AI-za-GIT-HUB',
    fullName: 'spaja86/OMEGA-AI-za-GIT-HUB',
    description: 'Omega AI za GitHub — beskonačno evolvuirajuće unapređenje.',
    url: 'https://github.com/spaja86/OMEGA-AI-za-GIT-HUB',
    status: 'concept',
    category: 'omega',
    technologies: ['AI'],
    features: ['GitHub improvement', 'Infinite evolution'],
  },
  {
    id: 'omega-ai-vercel',
    name: 'OMEGA-AI-za-Vercel',
    fullName: 'spaja86/OMEGA-AI-za-Vercel-',
    description: 'Omega AI koji treba da unapredi i poboljšava Vercel non-stop da evolvuira.',
    url: 'https://github.com/spaja86/-OMEGA-AI-za-Vercel-',
    status: 'concept',
    category: 'omega',
    technologies: ['AI', 'Vercel'],
    features: ['Vercel improvement', 'Continuous evolution'],
  },
  {
    id: 'omega-ai-google',
    name: 'OMEGA-AI-za-Google',
    fullName: 'spaja86/-OMEGA-AI-za-Google-',
    description: 'Omega AI koji treba da unapređuje i da evolvuira Google ka beskonačnostima.',
    url: 'https://github.com/spaja86/-OMEGA-AI-za-Google-',
    status: 'concept',
    category: 'omega',
    technologies: ['AI', 'Google'],
    features: ['Google improvement', 'Infinite evolution'],
  },
  {
    id: 'omega-ai-social',
    name: 'OMEGA-AI-5-persona-Social',
    fullName: 'spaja86/-OMEGA-AI-5-persona-za-Facebook-i-Instagram-i-TikTok-i-Threads-i-YoutYube-',
    description: 'OMEGA AI 5 persona za Facebook, Instagram, TikTok, Threads i YouTube.',
    url: 'https://github.com/spaja86/-OMEGA-AI-5-persona-za-Facebook-i-Instagram-i-TikTok-i-Threads-i-YoutYube-',
    status: 'concept',
    category: 'omega',
    technologies: ['AI'],
    features: ['Facebook AI', 'Instagram AI', 'TikTok AI', 'Threads AI', 'YouTube AI'],
  },
  {
    id: 'hello-world',
    name: 'hello-world',
    fullName: 'spaja86/hello-world',
    description: 'Just another repository.',
    url: 'https://github.com/spaja86/hello-world',
    status: 'skeleton',
    category: 'legacy',
    technologies: [],
    features: [],
  },
  {
    id: 'heloo-world',
    name: 'HelooWorld',
    fullName: 'spaja86/HelooWorld',
    description: 'Hello World test repository.',
    url: 'https://github.com/spaja86/HelooWorld',
    status: 'skeleton',
    category: 'legacy',
    technologies: [],
    features: [],
  },
  {
    id: 'java-swing-db',
    name: 'Read-data-from-database',
    fullName: 'spaja86/Read-data-from-database-and-write-to-excel-by-using-java-Swing-GUI',
    description: 'Read data from database and write to Excel using Java Swing GUI.',
    url: 'https://github.com/spaja86/Read-data-from-database-and-write-to-excel-by-using-java-Swing-GUI',
    language: 'Java',
    status: 'skeleton',
    category: 'legacy',
    technologies: ['Java', 'Swing', 'Excel'],
    features: ['Database reading', 'Excel export', 'GUI interface'],
  },
];

export function getActiveRepositories(): Repository[] {
  return repositories.filter(r => r.status === 'active');
}

export function getRepositoriesByCategory(category: Repository['category']): Repository[] {
  return repositories.filter(r => r.category === category);
}
