import { NextResponse } from 'next/server';
import { APP_VERSION } from '@/lib/constants';

export async function GET() {
  return NextResponse.json({
    sistem: 'AI IQ Menjacnica — Svetska Menjacnica',
    appVerzija: APP_VERSION,
    status: 'aktivan',
    opis: 'Svetska menjacnica koja drzi kurseve svega — BTC, SPAJA BTC i 150+ kripto valuta',
    spajaBtcPrompt: {
      naziv: 'SPAJA BTC',
      simbol: 'SPAJA',
      cena: '$892,500',
      opis: 'Ekskluzivna kripto valuta Kompanije SPAJA — mnogo skuplja od obicnog BTC-a',
      karakteristike: [
        'Sopstveni SPAJA Blockchain',
        'AI optimizacija',
        'Garantovana stabilnost',
        'Premium bezbednost',
        'Ekskluzivno na AI IQ Menjacnici',
      ],
    },
    kriptoKursevi: [
      { valuta: 'SPAJA BTC', simbol: 'SPAJA', cena: '$892,500', promena24h: '+3.8%' },
      { valuta: 'Bitcoin', simbol: 'BTC', cena: '$67,450', promena24h: '+2.4%' },
      { valuta: 'Ethereum', simbol: 'ETH', cena: '$3,820', promena24h: '+1.8%' },
      { valuta: 'Solana', simbol: 'SOL', cena: '$185', promena24h: '+5.1%' },
      { valuta: 'BNB', simbol: 'BNB', cena: '$612', promena24h: '+1.2%' },
      { valuta: 'USDT', simbol: 'USDT', cena: '$1.00', promena24h: '0.0%' },
    ],
    fiatKursevi: [
      { valuta: 'Evro', kod: 'EUR', kursRSD: '117.15', kursUSD: '$1.0845' },
      { valuta: 'Americki dolar', kod: 'USD', kursRSD: '108.05', kursUSD: '$1.00' },
      { valuta: 'Britanska funta', kod: 'GBP', kursRSD: '136.80', kursUSD: '$1.2660' },
      { valuta: 'Svajcarski franak', kod: 'CHF', kursRSD: '121.50', kursUSD: '$1.1245' },
      { valuta: 'Srpski dinar', kod: 'RSD', kursRSD: '1.00', kursUSD: '$0.0093' },
    ],
    statistika: {
      kriptoValute: '500+',
      fiatValute: '30+',
      dnevniPromet: '$100B+',
      aiTacnost: '94%',
      trgovackiParovi: '250+',
      korisnika: '10M+',
      zemalja: '190+',
      uptime: '99.9%',
      godinaOsnivanja: 2020,
    },
    funkcije: [
      'SPAJA BTC — ekskluzivna kripto valuta',
      'Kripto trading (BTC, ETH, SOL, 500+ valuta)',
      'Fiat konverzija (30+ valuta)',
      'AI predikcije sa 94% tacnoscu',
      'Portfolio menadzment sa AI asistentom',
      'Real-time analitika',
      'Trading platforma sa Order Book i Canvas Chart',
      'Kripto novcanik sa portfolio pracenjem',
      'Copy Trading — kopirajte uspesne tradere',
      'Edukacija — Bitcoin, Ethereum, Blockchain, DeFi, AI',
      'P&L Kalkulator za izracun profita/gubitka',
      'AI Sentiment analiza (Bullish/Bearish)',
    ],
    planovi: [
      { naziv: 'Starter', cena: '$0/mes', naknada: '0.2%', aiPredikcija: false, copyTrading: false, konsalting: false },
      { naziv: 'Pro', cena: '$29/mes', naknada: '0.1%', aiPredikcija: true, copyTrading: true, konsalting: false },
      { naziv: 'Enterprise', cena: 'Custom', naknada: '0%', aiPredikcija: true, copyTrading: true, konsalting: true },
    ],
    tim: [
      { ime: 'Nikola Spajic', uloga: 'Osnivac & CEO', opis: 'Vizionar kripto industrije i AI entuzijasta' },
      { ime: 'AI Tim', uloga: 'AI & Machine Learning', opis: 'Napredni AI modeli za predvidjanje cena i automatizovano trejdovanje' },
      { ime: 'Security Tim', uloga: 'Cybersecurity', opis: 'Bank-level sigurnost sa 2FA, enkripcijom i cold storage' },
      { ime: 'Trading Tim', uloga: 'Markets & Analytics', opis: 'Trzisni analiticari za kripto trendove i trading strategije' },
    ],
    kontakt: {
      vlasnik: 'Nikola Spajic',
      mejlovi: ['spajicn@yahoo.com', 'spajicn@gmail.com'],
      drustvneMreze: [
        { naziv: 'Facebook', url: 'https://www.facebook.com/Spaja86' },
        { naziv: 'Facebook (Digitalna Industrija)', url: 'https://www.facebook.com/profile.php?id=61583240952997' },
        { naziv: 'Instagram', url: 'https://www.instagram.com/spaja.1986' },
        { naziv: 'TikTok', url: 'https://www.tiktok.com/@spaja.1986' },
        { naziv: 'YouTube', url: 'https://www.youtube.com/@spajanikopenevolution' },
      ],
    },
    bankaIntegracija: {
      status: 'aktivan',
      banka: 'AI IQ World Bank',
      partner: 'ERSTE Banka DOO Smederevo',
      opis: 'Menjacnica i Banka rade zajedno kao savrseni finansijski ekosistem',
    },
    analiza: 'Ekstremno jaka menjacnica — sve se moze proveriti i analizirati',
    url: 'https://ai-iq-menja-nica-6cnf-git-copi-0e2b0a-nikolas-projects-b8a8458f.vercel.app/index.html',
    repo: 'spaja86/Ai-Iq-Menja-nica',
    timestamp: new Date().toISOString(),
  });
}
