import type { MetadataRoute } from 'next';
import { BASE_URL } from '@/lib/constants';

export default function sitemap(): MetadataRoute.Sitemap {
  const highPriority = ['/', '/dashboard', '/ekosistem'];
  const mediumHighPriority = ['/platforme', '/palasterizacija', '/perkolizonik', '/polimerzacija', '/eksosistzdacija', '/omega-ai', '/spaja-pro', '/igrice', '/gejming-industrija', '/gejming-likovi', '/it-proizvodi'];

  // Dynamic lastModified dates per page category
  const recentlyUpdated = new Date('2026-04-20');
  const corePages = new Date('2026-04-19');
  const standardPages = new Date('2026-04-14');

  const recentRoutes = ['/', '/dashboard', '/ai-iq-world-bank', '/omega-projekat-plasiranje', '/omega-projekat-zvanicno-otvaranje', '/oktavne-eksponencijalne-funkcije', '/blog', '/glavni-endzin', '/mozak-logika', '/glavni-sistem-nabavka', '/reklame-i-partnerstva', '/dnevna-raspodela-zarade', '/spaja-ultra-repl', '/digitalna-platforma', '/login', '/zaboravljena-lozinka', '/oktavni-gpu-ram', '/spaja-digitalni-kompjuter', '/digitalni-prozor', '/eksponat-glavnog-jezgra', '/digitalni-vorteks', '/generator-za-poslovne-racune', '/validator-poslovnih-racuna', '/licencni-budzet-srbija', '/digitalna-industrija-pib-mb', '/digitalna-industrija-sifra-delatnosti', '/digitalna-industrija-regulatorni-rokovi', '/digitalna-industrija-izvoz-faktura', '/digitalna-industrija-devizni-prilivi', '/digitalna-industrija-devizni-odlivi', '/digitalna-industrija-devizni-saldo', '/digitalna-industrija-kursna-lista', '/digitalna-industrija-kursne-razlike', '/digitalna-industrija-inflacije', '/digitalna-industrija-valutni-rizik', '/digitalna-industrija-hedzing', '/digitalna-industrija-kamatni-rizik', '/digitalna-industrija-kreditni-rizik', '/digitalna-industrija-likvidnosni-rizik', '/digitalna-industrija-operativni-rizik', '/digitalna-industrija-reputacioni-rizik', '/bar-kod', '/digitalna-industrija-strateski-rizik', '/digitalna-industrija-pravni-rizik', '/digitalna-industrija-poreski-rizik', '/digitalna-industrija-compliance-rizik', '/digitalna-industrija-esg-rizik', '/digitalna-industrija-diskriminacija', '/digitalna-industrija-sajber-rizik', '/digitalna-industrija-pozicije', '/digitalna-industrija-plate', '/digitalna-industrija-beneficije', '/digitalna-industrija-nagrade', '/digitalna-industrija-licencni-portfolio', '/issuer-license-control-center', '/perkolizonik', '/distribucija', '/api/distribucija', '/procesuiranje-3', '/api/procesuiranje-3'];
  const coreRoutes = ['/ekosistem', '/eksosistzdacija', '/omega-ai', '/spaja-pro', '/industrija', '/platforme', '/palasterizacija', '/pricing', '/it-proizvodi', '/igrice', '/gejming-industrija', '/omega-ai-suport', '/spaja-digitalni-brouvzer'];

  const routes = [
    '/',
    '/dashboard',
    '/industrija',
    '/platforme',
    '/palasterizacija',
    '/perkolizonik',
    '/polimerzacija',
    '/eksosistzdacija',
    '/it-proizvodi',
    '/banka',
    '/ai-iq-world-bank',
    '/menjacnica',
    '/kompanija',
    '/kompanije',
    '/ai-platforma',
    '/organizacija',
    '/organizacije',
    '/deploy',
    '/ekosistem',
    '/omega-ai',
    '/prompt',
    '/spaja-pro',
    '/spaja-univerzalni-prompt',
    '/auto-popravka',
    '/proksi',
    '/proksi-github-deploy',
    '/proksi-wifi-antena',
    '/mobilna-mreza',
    '/call-centar',
    '/igrice',
    '/gejming-industrija',
    '/gejming-likovi',
    '/api/gejming-likovi',
    '/dimenzije',
    '/proizvodi',
    '/spaja-generator-engine',
    '/spaja-digitalni-brouvzer',
    '/digitalni-prozor',
    '/io-openui-ao-laboratorija',
    '/spaja-render-medija',
    '/io-openui-ao-gaming-platforma',
    '/io-openui-ao-analitika',
    '/pricing',
    '/digitalni-televizor',
    '/distribucija',
    '/api/distribucija',
    '/monitoring-live',
    '/ai-iq-monitoring',
    '/blog',
    '/unit-testovi',
    '/omega-ai-suport',
    '/omega-projekat-plasiranje',
    '/oktavne-eksponencijalne-funkcije',
    '/omega-projekat-zvanicno-otvaranje',
    '/spaja-digitalni-kompjuter',
     '/oktavni-gpu-ram',
     '/glavni-endzin',
     '/mozak-logika',
     '/glavni-sistem-nabavka',
      '/generator-za-poslovne-racune',
      '/validator-poslovnih-racuna',
       '/licencni-budzet-srbija',
       '/digitalna-industrija-pib-mb',
       '/digitalna-industrija-sifra-delatnosti',
       '/digitalna-industrija-regulatorni-rokovi',
        '/digitalna-industrija-izvoz-faktura',
        '/digitalna-industrija-devizni-prilivi',
        '/digitalna-industrija-devizni-odlivi',
        '/digitalna-industrija-devizni-saldo',
         '/digitalna-industrija-kursna-lista',
         '/digitalna-industrija-kursne-razlike',
         '/digitalna-industrija-inflacije',
         '/api/digitalna-industrija-inflacije',
         '/digitalna-industrija-valutni-rizik',
         '/digitalna-industrija-hedzing',
         '/digitalna-industrija-kamatni-rizik',
         '/api/digitalna-industrija-hedzing',
         '/api/digitalna-industrija-kamatni-rizik',
         '/digitalna-industrija-kreditni-rizik',
         '/api/digitalna-industrija-kreditni-rizik',
           '/digitalna-industrija-likvidnosni-rizik',
           '/api/digitalna-industrija-likvidnosni-rizik',
           '/digitalna-industrija-operativni-rizik',
           '/api/digitalna-industrija-operativni-rizik',
           '/digitalna-industrija-reputacioni-rizik',
           '/api/digitalna-industrija-reputacioni-rizik',
           '/bar-kod',
           '/api/bar-kod',
          '/digitalna-industrija-strateski-rizik',
          '/api/digitalna-industrija-strateski-rizik',
          '/digitalna-industrija-pravni-rizik',
          '/api/digitalna-industrija-pravni-rizik',
          '/digitalna-industrija-poreski-rizik',
          '/api/digitalna-industrija-poreski-rizik',
          '/digitalna-industrija-compliance-rizik',
          '/api/digitalna-industrija-compliance-rizik',
          '/digitalna-industrija-esg-rizik',
          '/api/digitalna-industrija-esg-rizik',
          '/digitalna-industrija-diskriminacija',
          '/api/digitalna-industrija-diskriminacija',
          '/digitalna-industrija-sajber-rizik',
          '/api/digitalna-industrija-sajber-rizik',
          '/digitalna-industrija-pozicije',
          '/api/digitalna-industrija-pozicije',
          '/digitalna-industrija-plate',
          '/api/digitalna-industrija-plate',
          '/digitalna-industrija-beneficije',
          '/api/digitalna-industrija-beneficije',
          '/digitalna-industrija-nagrade',
          '/api/digitalna-industrija-nagrade',
          '/digitalna-industrija-licencni-portfolio',
          '/issuer-license-control-center',
          '/api/digitalna-industrija-licencni-portfolio',
          '/api/digitalna-industrija-licencni-procurement-queue',
          '/api/digitalna-industrija-licencni-vendor-status',
          '/reklame-i-partnerstva',
    '/dnevna-raspodela-zarade',
    '/spaja-ultra-repl',
    '/digitalna-platforma',
    '/registracija',
    '/security',
    '/login',
    '/zaboravljena-lozinka',
    '/eksponat-glavnog-jezgra',
    '/digitalni-vorteks',
    '/analiza-svega',
    '/api/analiza-svega',
    '/potencijal-svega-ovoga-do-sada',
    '/api/potencijal-svega-ovoga-do-sada',
    '/ai-iq-world-bank-procesiranje',
    '/api/ai-iq-world-bank-procesiranje',
    '/procesuiranje-svega',
    '/api/procesuiranje-svega',
    '/procesuiranje-3',
    '/api/procesuiranje-3',
    '/api/ekstremno-procesuiranje-svega',
    '/maksimus-svega',
    '/api/maksimus-svega',
    '/maksimus-2',
    '/api/maksimus-2',
    '/maksimus-3',
    '/api/maksimus-3',
    '/harmonizacija',
    '/api/harmonizacija',
  ];
  return routes.map((route) => ({
    url: `${BASE_URL}${route}`,
    lastModified: recentRoutes.includes(route)
      ? recentlyUpdated
      : coreRoutes.includes(route)
        ? corePages
        : standardPages,
    changeFrequency: route === '/' ? 'daily' as const : 'weekly' as const,
    priority: highPriority.includes(route)
      ? 1
      : mediumHighPriority.includes(route)
        ? 0.9
        : 0.8,
    alternates: {
      languages: {
        'sr-Latn': `${BASE_URL}${route}`,
      },
    },
  }));
}
