// SpajaUltraOmegaCore -∞Ω+∞ — EXTRIMLI
// Kompanija SPAJA — Digitalna Industrija
// INSTRUKCIJA ZA SVE — Master registry svih modula

import type { InstrukcijaEntry } from './types';

export const INSTRUKCIJA_REGISTRY: InstrukcijaEntry[] = [
  {
    id: 'risk',
    naziv: 'Risk Engine',
    opis: 'Izračunava nivo rizika za ekstremni sport na osnovu iskustva atletičara, vremenskih uslova, teškoće terena i kvaliteta opreme.',
    inputType: 'RiskInput',
    outputType: 'RiskResult',
    endpointPath: '/api/extrimli/risk',
    methods: ['POST'],
    primerInput: {
      sportId: 'snowboarding',
      athleteExperience: 7,
      weatherScore: 4,
      terrainDifficulty: 6,
      gearQualityIndex: 8,
      referenceId: 'ref-001',
    },
    primerOutput: {
      referenceId: 'ref-001',
      sportId: 'snowboarding',
      riskScore: 42.5,
      riskLevel: 'MEDIUM',
      recommendation: 'Moderate risk. Ensure all protective gear is worn and check weather.',
      valid: true,
      warnings: [],
      durationMs: 1,
    },
    edgeCases: [
      'athleteExperience < 0 ili > 10 → invalid, riskScore = 0',
      'weatherScore NaN ili Infinity → invalid',
      'terrainDifficulty < 0 → invalid',
      'gearQualityIndex = 0 → HIGH multiplier',
      'nepoznati sportId → valid: false sa upozorenjem',
    ],
  },
  {
    id: 'destruction',
    naziv: 'Destruction Engine (DESTRUKCIJA)',
    opis: 'Procenjuje destruktivni potencijal fizičkog udarca na imovinu uz fizičke profile dimenzija (360D–5760D).',
    inputType: 'DestructionInput',
    outputType: 'DestructionResult | DestructionPreview',
    endpointPath: '/api/extrimli/destruction',
    methods: ['POST'],
    primerInput: {
      assetId: 'wall-concrete-01',
      dimension: '720D',
      impactForce: 500,
      resonanceIndex: 6,
      containmentLevel: 7,
      athleteExperience: 8,
      sportId: 'bmx',
      referenceId: 'destr-001',
    },
    primerOutput: {
      referenceId: 'destr-001',
      assetId: 'wall-concrete-01',
      dimension: '720D',
      severityScore: 45,
      severityLevel: 'MAJOR',
      fragmentCount: 12,
      shockwaveRadiusM: 8.5,
      rollbackRecommended: false,
      degraded: false,
      degradedMode: null,
      valid: true,
      warnings: [],
      durationMs: 2,
    },
    edgeCases: [
      'impactForce = 0 → severityScore = 0, MINOR',
      'impactForce > 1000 → invalid',
      'nepoznati assetId → valid: false',
      'nevalidna dimension → invalid',
      'resonanceIndex NaN → invalid',
      'containmentLevel = 10 → minimalni fragmentCount',
    ],
  },
  {
    id: 'gear',
    naziv: 'Gear Catalog',
    opis: 'Upravljanje katalogom opreme: dodavanje, pretraga, ažuriranje zaliha i affiliate kalkulacija.',
    inputType: 'GearItem',
    outputType: 'GearCatalogEntry | GearCatalogEntry[]',
    endpointPath: '/api/extrimli/gear',
    methods: ['GET', 'POST', 'PATCH'],
    primerInput: {
      sku: 'HLM-999',
      brand: 'TestBrand',
      name: 'Test Helmet',
      category: 'helmet',
      safetyRating: 4,
      price: 79.99,
      stock: 20,
      affiliateCommissionPct: 8,
      sportIds: ['bmx', 'skateboarding'],
    },
    primerOutput: {
      sku: 'HLM-999',
      brand: 'TestBrand',
      name: 'Test Helmet',
      category: 'helmet',
      safetyRating: 4,
      price: 79.99,
      stock: 20,
      affiliateCommissionPct: 8,
      sportIds: ['bmx', 'skateboarding'],
      affiliateCommission: 6.4,
    },
    edgeCases: [
      'price < 0 → greška validacije',
      'stock < 0 → greška validacije',
      'nevalidan SKU format → greška',
      'affiliateCommissionPct > 100 → greška',
      'safetyRating van [1,5] → greška',
      'updateStock negativna delta ispod 0 → greška',
    ],
  },
  {
    id: 'events',
    naziv: 'Event Engine',
    opis: 'Upravljanje životnim ciklusom ekstremnih sportskih događaja: kreiranje, registracija, čekanje i otkazivanje.',
    inputType: 'ExtrimliEvent',
    outputType: 'ExtrimliEvent | EventRegistrationResult',
    endpointPath: '/api/extrimli/events',
    methods: ['GET', 'POST'],
    primerInput: {
      id: 'evt-001',
      name: 'Mountain Biking Championship',
      location: 'Kopaonik',
      sportId: 'mountain-biking',
      date: 1800000000000,
      capacity: 50,
      registrations: [],
      waitlist: [],
      prizePool: 5000,
      minExperienceLevel: 5,
      minAge: 18,
      requiredGearCategories: ['helmet', 'pads', 'bike'],
      status: 'upcoming',
    },
    primerOutput: {
      eventId: 'evt-001',
      athleteId: 'athlete-42',
      registered: true,
      waitlisted: false,
      message: 'Successfully registered for event.',
    },
    edgeCases: [
      'kapacitet popunjen → waitlist',
      'minExperienceLevel not met → registration rejected',
      'otkazani event → cannot register',
      'duplikat registration → idempotent',
      'prizePool < 0 → greška',
    ],
  },
  {
    id: 'performance',
    naziv: 'Performance Tracker',
    opis: 'Beleži sesije atletičara, prati lične rekorde i generiše izveštaj o napretku.',
    inputType: 'AthleteSession',
    outputType: 'PerformanceReport',
    endpointPath: '/api/extrimli/performance',
    methods: ['GET', 'POST'],
    primerInput: {
      sessionId: 'sess-001',
      athleteId: 'athlete-42',
      sportId: 'snowboarding',
      timestamp: 1700000000000,
      speedKph: 85.5,
      altitudeM: 1800,
      distanceKm: 12.3,
      gForce: 2.1,
      heartRateBpm: 165,
    },
    primerOutput: {
      athleteId: 'athlete-42',
      sessions: [
        {
          sessionId: 'sess-001',
          athleteId: 'athlete-42',
          sportId: 'snowboarding',
          timestamp: 1700000000000,
          speedKph: 85.5,
          altitudeM: 1800,
          distanceKm: 12.3,
          gForce: 2.1,
          heartRateBpm: 165,
        },
      ],
      personalBests: [
        { metric: 'speedKph', value: 85.5, sessionId: 'sess-001', timestamp: 1700000000000 },
      ],
      improvementRate: 0,
      valid: true,
      warnings: [],
    },
    edgeCases: [
      'speedKph < 0 → ignorisano ili upozorenje',
      'heartRateBpm = 0 → valid sesija ali warning',
      'bez sesija → prazni personalBests',
      'NaN u metrikama → preskočeno',
      'duplikat sessionId → overwrite',
    ],
  },
  {
    id: 'sports',
    naziv: 'Sport Registry',
    opis: 'Katalog ekstremnih sportova sa filterima po kategoriji, klasi rizika i potrebnoj opremi.',
    inputType: '{ category?: SportCategory; riskClass?: RiskClass }',
    outputType: 'Sport[]',
    endpointPath: '/api/extrimli/sports',
    methods: ['GET'],
    primerInput: { category: 'air' },
    primerOutput: [
      {
        id: 'base-jumping',
        name: 'Base Jumping',
        category: 'air',
        riskClass: 'V',
        requiredGear: ['chute', 'helmet'],
        weatherSensitive: true,
      },
      {
        id: 'paragliding',
        name: 'Paragliding',
        category: 'air',
        riskClass: 'IV',
        requiredGear: ['wing', 'harness', 'helmet'],
        weatherSensitive: true,
      },
    ],
    edgeCases: [
      'nepoznata kategorija → prazan niz',
      'nepoznata riskClass → prazan niz',
      'bez filtera → sve 10 sportova',
      'getSportById nepostojećeg ID → undefined',
    ],
  },
  {
    id: 'weather',
    naziv: 'Weather Adapter',
    opis: 'Konvertuje surove vremenske podatke u faktore rizika za planiranje ekstremnih aktivnosti.',
    inputType: 'RawWeatherData',
    outputType: 'WeatherRiskFactors',
    endpointPath: '/api/extrimli/weather',
    methods: ['POST'],
    primerInput: {
      windSpeedKph: 45,
      precipitationMm: 5,
      temperatureC: -3,
      visibilityKm: 2,
    },
    primerOutput: {
      windRiskModifier: 6.5,
      terrainRiskModifier: 4.2,
      gearRecommendation: 'Wind-resistant outer layer recommended. Waterproof gear required.',
      overallWeatherScore: 6.1,
      valid: true,
      warnings: [],
    },
    edgeCases: [
      'windSpeedKph = 0 → windRiskModifier = 0',
      'visibilityKm = 0 → high terrainRiskModifier',
      'temperatureC = -40 → extreme warning',
      'NaN windSpeedKph → invalid',
      'negativna precipitationMm → invalid',
    ],
  },
  {
    id: 'read-voice',
    naziv: 'Read Voice',
    opis: 'Priprema i generiše EXTRIMLI glasovno čitanje sa HARD, ULTRA, RAGE i DILIT modifikatorima.',
    inputType: 'ReadVoiceInput',
    outputType: 'ReadVoicePreview | audio/mpeg',
    endpointPath: '/api/extrimli/read-voice',
    methods: ['POST'],
    primerInput: {
      text: 'Extreme exposure detected. Reduce speed and stabilize your landing zone.',
      modifiers: ['hard', 'ultra', 'rage', 'dilit'],
      locale: 'en',
      preview: true,
    },
    primerOutput: {
      requestLabel: 'EXTRIMLI HARD ULTRA RAGE DILIT',
      renderedText: 'EXTRIMLI HARD ULTRA RAGE DILIT voice read. Extreme exposure detected. Reduce speed and stabilize your landing zone.',
      selectedVoice: 'onyx',
      locale: 'en',
      modifiers: ['hard', 'ultra', 'rage', 'dilit'],
      valid: true,
      warnings: [],
      durationMs: 0,
    },
    edgeCases: [
      'text nedostaje ili je prazan → valid: false',
      'text duži od 4096 karaktera → valid: false',
      'nepoznati modifikatori se ignorišu',
      'preview = true vraća JSON preview bez TTS renderovanja',
      'preview = false zahteva autentifikaciju i OpenAI TTS konfiguraciju',
    ],
  },
  {
    id: 'health',
    naziv: 'Health Report',
    opis: 'Vraća zdravstveni izveštaj EXTRIMLI modula: evaluacije, poslednji rizik/destrukcija skor i KPI verzije.',
    inputType: 'void',
    outputType: 'ExtrimliHealthReport',
    endpointPath: '/api/extrimli/health',
    methods: ['GET'],
    primerInput: null,
    primerOutput: {
      personaId: 'extrimli-core',
      contractVersion: 'v1',
      moduleVersion: '1.0.0',
      riskEvaluations: 42,
      lastRiskScore: 61.5,
      lastRiskLevel: 'HIGH',
      destructionEvaluations: 7,
      previewEvaluations: 3,
      lastDestructionSeverityScore: 33,
      lastDestructionSeverityLevel: 'MINOR',
      performanceMaxMs: 50,
      apiResponseMaxMs: 200,
    },
    edgeCases: [
      'bez prethodnih evaluacija → sve nule / LOW',
    ],
  },
];

export function getInstrukcija(moduleId: unknown): InstrukcijaEntry | undefined {
  if (typeof moduleId !== 'string' || !moduleId) return undefined;
  return INSTRUKCIJA_REGISTRY.find((e) => e.id === moduleId);
}

export function listInstrukcije(): InstrukcijaEntry[] {
  return INSTRUKCIJA_REGISTRY.slice();
}
