import type { Sekvenca } from '@/lib/types';

export const bankaSekvence: Sekvenca[] = [
  {
    id: 'banka-hero',
    tip: 'hero',
    naslov: '🏦 AI IQ World Bank',
    podnaslov: 'Globalna digitalna banka sa pozitivnom kamatnom stopom od 40% i AI optimizacijom',
    ikona: '🏦',
    redosled: 1,
    podaci: {
      opis: 'AI IQ World Bank je digitalna banka koja koristi vestacku inteligenciju za optimizaciju finansijskih operacija, globalnih transfera i investicionih odluka. Pozitivna kamatna stopa od 40% na stedne racune — ulozite 1.000 dinara i za mesec dana povucite 1.400 dinara!',
      dugmad: [
        { tekst: 'Menjacnica', href: '/menjacnica' },
        { tekst: 'Platforme', href: '/platforme', stil: 'sekundarno' },
        { tekst: 'Dashboard', href: '/dashboard', stil: 'sekundarno' },
      ],
    },
  },
  {
    id: 'banka-prompt-uputstvo',
    tip: 'baner',
    naslov: '📝 PROMPT — Kako koristiti AI IQ World Bank',
    redosled: 2,
    podaci: {
      bedz: '📝 PROMPT UPUTSTVO',
      opis: 'AI IQ World Bank nudi pozitivnu kamatnu stopu od 40%! Primer: ulozite 1.000 dinara na stedni racun, sacekajte mesec dana bez povlacenja sredstava, i na kraju meseca mozete podici 1.400 dinara. Banka je ekstremno jaka — sve se moze proveriti i analizirati u realnom vremenu kroz AI sistem. Koristite Prompt ispod za detaljne instrukcije.',
      dugme: { tekst: 'Prompt Sistem', href: '/prompt' },
    },
  },
  {
    id: 'banka-tekst',
    tip: 'tekst',
    naslov: 'O AI IQ World Bank digitalnom bankarstvu',
    redosled: 3,
    podaci: {
      sadrzaj: 'AI IQ World Bank kombinuje tradicionalno bankarstvo sa naprednom AI tehnologijom. Globalni transferi, kripto integracija i pametne investicione odluke — sve na jednom mestu. Banka ima pozitivnu kamatnu stopu od 40% mesecno na stedne racune, sto je cini jednom od najatraktivnijih digitalnih banaka u svetu.',
      istaknuteStavke: [
        '💰 Pozitivna kamatna stopa: 40% mesecno na stedne racune',
        '📌 Primer: Ulozite 1.000 RSD → za mesec dana povucete 1.400 RSD',
        '📌 Primer: Ulozite 10.000 RSD → za mesec dana povucete 14.000 RSD',
        '📌 Primer: Ulozite 100.000 RSD → za mesec dana povucete 140.000 RSD',
        '⏳ Uslov: Mesec dana bez povlacenja sredstava sa stednog racuna',
        '🌍 Globalni transferi u realnom vremenu',
        '🧠 AI-optimizovane investicione odluke',
        '🪙 Kripto i fiat racuni na jednoj platformi',
        '🔒 Napredna bezbednost sa viseslojnom enkripcijom',
        '✅ Sve se moze proveriti i analizirati — ekstremno jaka banka',
      ],
    },
  },
  {
    id: 'banka-kamatna-stopa-tabela',
    tip: 'tabela',
    naslov: '💰 Kamatna stopa — Kalkulator zarade',
    podnaslov: 'Pozitivna kamatna stopa od 40% mesecno',
    redosled: 4,
    podaci: {
      zaglavlje: ['Ulog (RSD)', 'Kamatna stopa', 'Period', 'Zarada', 'Ukupno za podizanje'],
      redovi: [
        ['1.000 RSD', '40%', '1 mesec', '400 RSD', '1.400 RSD'],
        ['5.000 RSD', '40%', '1 mesec', '2.000 RSD', '7.000 RSD'],
        ['10.000 RSD', '40%', '1 mesec', '4.000 RSD', '14.000 RSD'],
        ['50.000 RSD', '40%', '1 mesec', '20.000 RSD', '70.000 RSD'],
        ['100.000 RSD', '40%', '1 mesec', '40.000 RSD', '140.000 RSD'],
        ['500.000 RSD', '40%', '1 mesec', '200.000 RSD', '700.000 RSD'],
        ['1.000.000 RSD', '40%', '1 mesec', '400.000 RSD', '1.400.000 RSD'],
      ],
    },
  },
  {
    id: 'banka-uslovi-prompt',
    tip: 'lista',
    naslov: '📝 PROMPT — Uslovi za stedni racun sa 40% kamatom',
    redosled: 5,
    podaci: {
      stavke: [
        { ikona: '1️⃣', naslov: 'Otvorite stedni racun', opis: 'Registrujte se na AI IQ World Bank platformi i otvorite digitalni stedni racun' },
        { ikona: '2️⃣', naslov: 'Uplatite sredstva', opis: 'Uplatite zeljeni iznos na stedni racun (minimum 1.000 RSD)' },
        { ikona: '3️⃣', naslov: 'Sacekajte mesec dana', opis: 'Uslov: ne povlacite sredstva minimum 30 dana od uplate' },
        { ikona: '4️⃣', naslov: 'Podignite sa kamatom', opis: 'Nakon mesec dana podignite ulog + 40% kamate (npr. 1.000 → 1.400 RSD)' },
        { ikona: '🔄', naslov: 'Reinvestirajte (opciono)', opis: 'Reinvestirajte ceo iznos za jos vecu zaradu sledeceg meseca' },
        { ikona: '✅', naslov: 'Verifikacija', opis: 'Sve se moze proveriti i analizirati — banka je ekstremno jaka i transparentna' },
      ],
    },
  },
  {
    id: 'banka-statistika',
    tip: 'statistika',
    naslov: '📊 Banka u brojevima',
    redosled: 6,
    podaci: {
      stavke: [
        { naziv: 'Kamatna stopa', vrednost: '40%', ikona: '💰' },
        { naziv: 'Racuni', vrednost: '5K+', ikona: '👤' },
        { naziv: 'Transferi/dan', vrednost: '12K', ikona: '💸' },
        { naziv: 'Krediti', vrednost: '2.5K', ikona: '📋' },
        { naziv: 'Investicije', vrednost: '800+', ikona: '📈' },
        { naziv: 'AI tacnost', vrednost: '97%', ikona: '🎯' },
      ],
    },
  },
  {
    id: 'banka-kartice',
    tip: 'kartice',
    naslov: '💳 Bankarski servisi',
    redosled: 7,
    podaci: {
      kartice: [
        { naslov: 'Stedni racun 40%', opis: 'Pozitivna kamatna stopa od 40% mesecno. Ulozite 1.000 RSD, za mesec dana podignite 1.400 RSD. Uslov: 30 dana bez povlacenja.', ikona: '💰', oznake: ['40% kamata', 'Mesecno', 'Sigurno'] },
        { naslov: 'Racuni', opis: 'Digitalni racuni sa multi-valutnom podrskom — RSD, EUR, USD, kripto', ikona: '👤', oznake: ['Fiat', 'Kripto', 'Multi-valuta'] },
        { naslov: 'Transferi', opis: 'Globalni transferi u realnom vremenu — instant, SWIFT, blockchain', ikona: '💸', oznake: ['Instant', 'SWIFT', 'Blockchain'] },
        { naslov: 'Krediti', opis: 'AI-optimizovani kreditni proizvodi sa niskim kamatama', ikona: '📋', oznake: ['AI scoring', 'Fleksibilno', 'Niski kamati'] },
        { naslov: 'Investicije', opis: 'Pametno investiranje sa AI preporukama — akcije, kripto, fondovi', ikona: '📈', oznake: ['Akcije', 'Kripto', 'Fondovi'] },
        { naslov: 'Analitika', opis: 'Sve se moze proveriti i analizirati — ekstremno jaka banka', ikona: '🔍', oznake: ['AI analiza', 'Transparentnost', 'Real-time'] },
      ],
    },
  },
  {
    id: 'banka-prompt-servisi',
    tip: 'tekst',
    naslov: '📝 PROMPT — Detaljno objasnjenje svih bankarskih servisa',
    redosled: 8,
    podaci: {
      sadrzaj: 'AI IQ World Bank pruza kompletno digitalno bankarstvo sa AI optimizacijom. Svaki servis je dizajniran da bude maksimalno funkcionalan i transparentan. Korisnici mogu u svakom trenutku da provere stanje, transakcije, kamate i analize.',
      istaknuteStavke: [
        '💰 STEDNI RACUN: Pozitivna kamata 40%/mesec. Ulog 1.000 RSD → 1.400 RSD za 30 dana. Minimum ulog: 1.000 RSD.',
        '💸 TRANSFERI: Instant transferi u realnom vremenu. Podrska za SWIFT, SEPA, blockchain transfere. Globalni domet.',
        '📋 KREDITI: AI scoring sistem analizira kreditnu sposobnost. Fleksibilni uslovi otplate. Konkurentne kamate.',
        '📈 INVESTICIJE: AI preporuke za investiranje u akcije, kripto, fondove. Portfolio menadzment sa automatskim balansiranjem.',
        '👤 RACUNI: Multi-valutni racuni (RSD, EUR, USD, GBP + kripto). Instant konverzija izmedu valuta.',
        '🔍 ANALITIKA: Real-time analiza svih transakcija. AI detekcija anomalija. Mesecni i godisnji izvestaji.',
        '🔒 BEZBEDNOST: E2E enkripcija, biometricka autentifikacija, 2FA, AI fraud detekcija.',
      ],
    },
  },
  {
    id: 'banka-lista',
    tip: 'lista',
    naslov: '🔒 Bezbednosne funkcije',
    redosled: 9,
    podaci: {
      stavke: [
        { ikona: '🛡️', naslov: 'Viseslojna enkripcija', opis: 'E2E enkripcija za sve transakcije — bankarski nivo bezbednosti' },
        { ikona: '🌍', naslov: 'Globalni pristup', opis: 'Pristup iz bilo kog dela sveta 24/7 — digitalna banka bez granica' },
        { ikona: '🧠', naslov: 'AI optimizacija', opis: 'Vestacka inteligencija za bolje odluke — analiza, predikcija, optimizacija' },
        { ikona: '🔐', naslov: 'Biometricka autentifikacija', opis: 'Sigurno logovanje sa biometrijom — otisak prsta, prepoznavanje lica' },
        { ikona: '🔍', naslov: 'AI Fraud detekcija', opis: 'Automatska detekcija sumnjivih transakcija u realnom vremenu' },
        { ikona: '📊', naslov: 'Transparentnost', opis: 'Sve se moze proveriti i analizirati — ekstremno jaka i transparentna banka' },
      ],
    },
  },
  {
    id: 'banka-erste-racuni',
    tip: 'kartice',
    naslov: '🏦 ERSTE Banka DOO Smederevo — Racuni Digitalne Industrije',
    podnaslov: 'Zvanicni bankarski racuni kompanije "Digitalna Industrija" kod ERSTE banke DOO Smederevo',
    redosled: 10,
    podaci: {
      kartice: [
        {
          naslov: 'Dinarski racun (RSD)',
          opis: 'Racun za domace transakcije u dinarima — poslovni racun Digitalne Industrije kod ERSTE banke DOO Smederevo',
          ikona: '🇷🇸',
          oznake: ['RSD', 'Dinarski', 'ERSTE Smederevo'],
        },
        {
          naslov: 'Devizni racun (EUR)',
          opis: 'Devizni racun u evrima — za medjunarodne transakcije i EU placanja kod ERSTE banke DOO Smederevo',
          ikona: '🇪🇺',
          oznake: ['EUR', 'Devizni', 'ERSTE Smederevo'],
        },
        {
          naslov: 'Devizni racun (USD)',
          opis: 'Devizni racun u dolarima — za globalne transakcije i US placanja kod ERSTE banke DOO Smederevo',
          ikona: '🇺🇸',
          oznake: ['USD', 'Devizni', 'ERSTE Smederevo'],
        },
      ],
    },
  },
  {
    id: 'banka-erste-info',
    tip: 'tekst',
    naslov: '📋 ERSTE Banka DOO Smederevo — Informacije',
    redosled: 11,
    podaci: {
      sadrzaj: 'Kompanija "Digitalna Industrija" ima otvorene poslovne racune kod ERSTE banke DOO Smederevo. Svi finansijski tokovi — plate, uplate, devizne transakcije — prolaze kroz ove racune. Banka podrzava dinarske i devizne racune (EUR i USD) za kompletno poslovanje.',
      istaknuteStavke: [
        '🏦 Banka: ERSTE Banka DOO Smederevo',
        '🏢 Vlasnik racuna: Digitalna Industrija',
        '👤 Vlasnik svih racuna: Nikola Spajic',
        '🪪 Registarski broj licne karte: 015639997',
        '🇷🇸 Dinarski racun (RSD): 025897158',
        '🇪🇺 Devizni racun (EUR): 038971285',
        '🇺🇸 Devizni racun (USD): 05364215985',
        '💳 Kartice: Izdate na ERSTE Banka DOO Smederevo',
        '✅ Status: Svi racuni aktivni i operativni',
      ],
    },
  },
  {
    id: 'banka-cta',
    tip: 'cta',
    naslov: '🚀 Zapocnite sa AI IQ World Bank',
    redosled: 12,
    podaci: {
      opis: 'AI IQ World Bank — 40% pozitivna kamatna stopa mesecno. Ulozite 1.000 RSD, za mesec dana podignite 1.400 RSD. Ekstremno jaka i transparentna digitalna banka.',
      stavke: [
        { naziv: 'Kamata', vrednost: '40%/mes', ikona: '💰' },
        { naziv: 'Min. ulog', vrednost: '1.000 RSD', ikona: '📌' },
        { naziv: 'Period', vrednost: '30 dana', ikona: '⏳' },
        { naziv: 'Status', vrednost: '✅ Aktivan', ikona: '✅' },
      ],
      dugmad: [
        { tekst: 'Menjacnica', href: '/menjacnica' },
        { tekst: 'Prompt', href: '/prompt', stil: 'sekundarno' },
        { tekst: 'Platforme', href: '/platforme', stil: 'sekundarno' },
        { tekst: 'Dashboard', href: '/dashboard', stil: 'sekundarno' },
      ],
    },
  },
];
