import type { Sekvenca } from '@/lib/types';

export const bankaSekvence: Sekvenca[] = [
  {
    id: 'banka-hero',
    tip: 'hero',
    naslov: '🏦 AI IQ World Bank',
    podnaslov: 'Globalna digitalna banka sa pozitivnom kamatnom stopom od 40% i AI optimizacijom',
    ikona: '🏦',
    redosled: 1,
    podaci: {
      opis: 'AI IQ World Bank je digitalna banka koja koristi vestacku inteligenciju za optimizaciju finansijskih operacija, globalnih transfera i investicionih odluka. Pozitivna kamatna stopa od 40% na stedne racune — ulozite 1.000 dinara i za mesec dana povucite 1.400 dinara!',
      dugmad: [
        { tekst: 'Menjacnica', href: '/menjacnica' },
        { tekst: 'Platforme', href: '/platforme', stil: 'sekundarno' },
        { tekst: 'Dashboard', href: '/dashboard', stil: 'sekundarno' },
      ],
    },
  },
  {
    id: 'banka-prompt-uputstvo',
    tip: 'baner',
    naslov: '📝 PROMPT — Kako koristiti AI IQ World Bank',
    redosled: 2,
    podaci: {
      bedz: '📝 PROMPT UPUTSTVO',
      opis: 'AI IQ World Bank nudi pozitivnu kamatnu stopu od 40%! Primer: ulozite 1.000 dinara na stedni racun, sacekajte mesec dana bez povlacenja sredstava, i na kraju meseca mozete podici 1.400 dinara. Banka je ekstremno jaka — sve se moze proveriti i analizirati u realnom vremenu kroz AI sistem. Koristite Prompt ispod za detaljne instrukcije.',
      dugme: { tekst: 'Prompt Sistem', href: '/prompt' },
    },
  },
  {
    id: 'banka-tekst',
    tip: 'tekst',
    naslov: 'O AI IQ World Bank digitalnom bankarstvu',
    redosled: 3,
    podaci: {
      sadrzaj: 'AI IQ World Bank kombinuje tradicionalno bankarstvo sa naprednom AI tehnologijom. Globalni transferi, kripto integracija i pametne investicione odluke — sve na jednom mestu. Banka ima pozitivnu kamatnu stopu od 40% mesecno na stedne racune, sto je cini jednom od najatraktivnijih digitalnih banaka u svetu.',
      istaknuteStavke: [
        '💰 Pozitivna kamatna stopa: 40% mesecno na stedne racune',
        '📌 Primer: Ulozite 1.000 RSD → za mesec dana povucete 1.400 RSD',
        '📌 Primer: Ulozite 10.000 RSD → za mesec dana povucete 14.000 RSD',
        '📌 Primer: Ulozite 100.000 RSD → za mesec dana povucete 140.000 RSD',
        '⏳ Uslov: Mesec dana bez povlacenja sredstava sa stednog racuna',
        '🌍 Globalni transferi u realnom vremenu',
        '🧠 AI-optimizovane investicione odluke',
        '🪙 Kripto i fiat racuni na jednoj platformi',
        '🔒 Napredna bezbednost sa viseslojnom enkripcijom',
        '✅ Sve se moze proveriti i analizirati — ekstremno jaka banka',
      ],
    },
  },
  {
    id: 'banka-kamatna-stopa-tabela',
    tip: 'tabela',
    naslov: '💰 Kamatna stopa — Kalkulator zarade',
    podnaslov: 'Pozitivna kamatna stopa od 40% mesecno',
    redosled: 4,
    podaci: {
      zaglavlje: ['Ulog (RSD)', 'Kamatna stopa', 'Period', 'Zarada', 'Ukupno za podizanje'],
      redovi: [
        ['1.000 RSD', '40%', '1 mesec', '400 RSD', '1.400 RSD'],
        ['5.000 RSD', '40%', '1 mesec', '2.000 RSD', '7.000 RSD'],
        ['10.000 RSD', '40%', '1 mesec', '4.000 RSD', '14.000 RSD'],
        ['50.000 RSD', '40%', '1 mesec', '20.000 RSD', '70.000 RSD'],
        ['100.000 RSD', '40%', '1 mesec', '40.000 RSD', '140.000 RSD'],
        ['500.000 RSD', '40%', '1 mesec', '200.000 RSD', '700.000 RSD'],
        ['1.000.000 RSD', '40%', '1 mesec', '400.000 RSD', '1.400.000 RSD'],
      ],
    },
  },
  {
    id: 'banka-uslovi-prompt',
    tip: 'lista',
    naslov: '📝 PROMPT — Uslovi za stedni racun sa 40% kamatom',
    redosled: 5,
    podaci: {
      stavke: [
        { ikona: '1️⃣', naslov: 'Otvorite stedni racun', opis: 'Registrujte se na AI IQ World Bank platformi i otvorite digitalni stedni racun' },
        { ikona: '2️⃣', naslov: 'Uplatite sredstva', opis: 'Uplatite zeljeni iznos na stedni racun (minimum 1.000 RSD)' },
        { ikona: '3️⃣', naslov: 'Sacekajte mesec dana', opis: 'Uslov: ne povlacite sredstva minimum 30 dana od uplate' },
        { ikona: '4️⃣', naslov: 'Podignite sa kamatom', opis: 'Nakon mesec dana podignite ulog + 40% kamate (npr. 1.000 → 1.400 RSD)' },
        { ikona: '🔄', naslov: 'Reinvestirajte (opciono)', opis: 'Reinvestirajte ceo iznos za jos vecu zaradu sledeceg meseca' },
        { ikona: '✅', naslov: 'Verifikacija', opis: 'Sve se moze proveriti i analizirati — banka je ekstremno jaka i transparentna' },
      ],
    },
  },
  {
    id: 'banka-statistika',
    tip: 'statistika',
    naslov: '📊 Banka u brojevima',
    redosled: 6,
    podaci: {
      stavke: [
        { naziv: 'Kamatna stopa', vrednost: '40%', ikona: '💰' },
        { naziv: 'Racuni', vrednost: '5K+', ikona: '👤' },
        { naziv: 'Transferi/dan', vrednost: '12K', ikona: '💸' },
        { naziv: 'Krediti', vrednost: '2.5K', ikona: '📋' },
        { naziv: 'Investicije', vrednost: '800+', ikona: '📈' },
        { naziv: 'AI tacnost', vrednost: '97%', ikona: '🎯' },
      ],
    },
  },
  {
    id: 'banka-kartice',
    tip: 'kartice',
    naslov: '💳 Bankarski servisi',
    redosled: 7,
    podaci: {
      kartice: [
        { naslov: 'Stedni racun 40%', opis: 'Pozitivna kamatna stopa od 40% mesecno. Ulozite 1.000 RSD, za mesec dana podignite 1.400 RSD. Uslov: 30 dana bez povlacenja.', ikona: '💰', oznake: ['40% kamata', 'Mesecno', 'Sigurno'] },
        { naslov: 'Racuni', opis: 'Digitalni racuni sa multi-valutnom podrskom — RSD, EUR, USD, kripto', ikona: '👤', oznake: ['Fiat', 'Kripto', 'Multi-valuta'] },
        { naslov: 'Transferi', opis: 'Globalni transferi u realnom vremenu — instant, SWIFT, blockchain', ikona: '💸', oznake: ['Instant', 'SWIFT', 'Blockchain'] },
        { naslov: 'Krediti', opis: 'AI-optimizovani kreditni proizvodi sa niskim kamatama', ikona: '📋', oznake: ['AI scoring', 'Fleksibilno', 'Niski kamati'] },
        { naslov: 'Investicije', opis: 'Pametno investiranje sa AI preporukama — akcije, kripto, fondovi', ikona: '📈', oznake: ['Akcije', 'Kripto', 'Fondovi'] },
        { naslov: 'Analitika', opis: 'Sve se moze proveriti i analizirati — ekstremno jaka banka', ikona: '🔍', oznake: ['AI analiza', 'Transparentnost', 'Real-time'] },
      ],
    },
  },
  {
    id: 'banka-prompt-servisi',
    tip: 'tekst',
    naslov: '📝 PROMPT — Detaljno objasnjenje svih bankarskih servisa',
    redosled: 8,
    podaci: {
      sadrzaj: 'AI IQ World Bank pruza kompletno digitalno bankarstvo sa AI optimizacijom. Svaki servis je dizajniran da bude maksimalno funkcionalan i transparentan. Korisnici mogu u svakom trenutku da provere stanje, transakcije, kamate i analize.',
      istaknuteStavke: [
        '💰 STEDNI RACUN: Pozitivna kamata 40%/mesec. Ulog 1.000 RSD → 1.400 RSD za 30 dana. Minimum ulog: 1.000 RSD.',
        '💸 TRANSFERI: Instant transferi u realnom vremenu. Podrska za SWIFT, SEPA, blockchain transfere. Globalni domet.',
        '📋 KREDITI: AI scoring sistem analizira kreditnu sposobnost. Fleksibilni uslovi otplate. Konkurentne kamate.',
        '📈 INVESTICIJE: AI preporuke za investiranje u akcije, kripto, fondove. Portfolio menadzment sa automatskim balansiranjem.',
        '👤 RACUNI: Multi-valutni racuni (RSD, EUR, USD, GBP + kripto). Instant konverzija izmedu valuta.',
        '🔍 ANALITIKA: Real-time analiza svih transakcija. AI detekcija anomalija. Mesecni i godisnji izvestaji.',
        '🔒 BEZBEDNOST: E2E enkripcija, biometricka autentifikacija, 2FA, AI fraud detekcija.',
      ],
    },
  },
  {
    id: 'banka-lista',
    tip: 'lista',
    naslov: '🔒 Bezbednosne funkcije',
    redosled: 9,
    podaci: {
      stavke: [
        { ikona: '🛡️', naslov: 'Viseslojna enkripcija', opis: 'E2E enkripcija za sve transakcije — bankarski nivo bezbednosti' },
        { ikona: '🌍', naslov: 'Globalni pristup', opis: 'Pristup iz bilo kog dela sveta 24/7 — digitalna banka bez granica' },
        { ikona: '🧠', naslov: 'AI optimizacija', opis: 'Vestacka inteligencija za bolje odluke — analiza, predikcija, optimizacija' },
        { ikona: '🔐', naslov: 'Biometricka autentifikacija', opis: 'Sigurno logovanje sa biometrijom — otisak prsta, prepoznavanje lica' },
        { ikona: '🔍', naslov: 'AI Fraud detekcija', opis: 'Automatska detekcija sumnjivih transakcija u realnom vremenu' },
        { ikona: '📊', naslov: 'Transparentnost', opis: 'Sve se moze proveriti i analizirati — ekstremno jaka i transparentna banka' },
      ],
    },
  },
  {
    id: 'banka-erste-racuni',
    tip: 'kartice',
    naslov: '🏦 ERSTE Banka DOO Smederevo — Racuni Digitalne Industrije',
    podnaslov: 'Zvanicni bankarski racuni kompanije "Digitalna Industrija" kod ERSTE banke DOO Smederevo',
    redosled: 10,
    podaci: {
      kartice: [
        {
          naslov: 'Dinarski racun (RSD)',
          opis: 'Racun za domace transakcije u dinarima — poslovni racun Digitalne Industrije kod ERSTE banke DOO Smederevo',
          ikona: '🇷🇸',
          oznake: ['RSD', 'Dinarski', 'ERSTE Smederevo'],
        },
        {
          naslov: 'Devizni racun (EUR)',
          opis: 'Devizni racun u evrima — za medjunarodne transakcije i EU placanja kod ERSTE banke DOO Smederevo',
          ikona: '🇪🇺',
          oznake: ['EUR', 'Devizni', 'ERSTE Smederevo'],
        },
        {
          naslov: 'Devizni racun (USD)',
          opis: 'Devizni racun u dolarima — za globalne transakcije i US placanja kod ERSTE banke DOO Smederevo',
          ikona: '🇺🇸',
          oznake: ['USD', 'Devizni', 'ERSTE Smederevo'],
        },
      ],
    },
  },
  {
    id: 'banka-erste-info',
    tip: 'tekst',
    naslov: '📋 ERSTE Banka DOO Smederevo — Informacije',
    redosled: 11,
    podaci: {
      sadrzaj: 'Kompanija "Digitalna Industrija" ima otvorene poslovne racune kod ERSTE banke DOO Smederevo. Svi finansijski tokovi — plate, uplate, devizne transakcije — prolaze kroz ove racune. Banka podrzava dinarske i devizne racune (EUR i USD) za kompletno poslovanje.',
      istaknuteStavke: [
        '🏦 Banka: ERSTE Banka DOO Smederevo',
        '🏢 Vlasnik racuna: Digitalna Industrija',
        '👤 Vlasnik svih racuna: Nikola Spajic',
        '🪪 Registarski broj licne karte: 015639997',
        '🆔 JMBG: 0312986850017',
        '🇷🇸 Dinarski racun (RSD): 025897158',
        '🇪🇺 Devizni racun (EUR): 038971285',
        '🇺🇸 Devizni racun (USD): 05364215985',
        '💳 Kartice: Izdate na ERSTE Banka DOO Smederevo',
        '✅ Status: Svi racuni aktivni i operativni',
      ],
    },
  },
  {
    id: 'banka-misija-vizija',
    tip: 'tekst',
    naslov: '🎯 Misija i vizija AI IQ World Bank',
    redosled: 12,
    podaci: {
      sadrzaj: 'AI IQ World Bank ima misiju da pruzi globalnu digitalnu banku sa naprednom vestackom inteligencijom koja optimizuje finansijske operacije za sve korisnike. Vizija je da postane vodeca digitalna banka koja spaja tradicionalno bankarstvo sa AI inovacijama.',
      istaknuteStavke: [
        '🎯 Misija: Globalna digitalna banka sa AI optimizacijom za sve korisnike',
        '🔭 Vizija: Vodeca svetska AI banka sa 40% pozitivnom kamatnom stopom',
        '💡 Inovacija: Spajanje tradicionalnog bankarstva sa naprednim AI tehnologijama',
        '🌍 Globalni domet: Pristupacna iz svakog dela sveta 24/7',
        '🤝 Vrednosti: Transparentnost, pouzdanost, sigurnost, pristupacnost',
        '📈 Rast: Kontinuirano unapredjenje servisa kroz AI analitiku',
      ],
    },
  },
  {
    id: 'banka-omega-ai-tehnologija',
    tip: 'kartice',
    naslov: '🧠 Omega AI Tehnologija',
    podnaslov: 'Kako Omega AI pokrece AI IQ World Bank',
    redosled: 13,
    podaci: {
      kartice: [
        { naslov: 'AI Scoring sistem', opis: 'Omega AI analizira kreditnu sposobnost korisnika u realnom vremenu sa tacnoscu od 97%', ikona: '🎯', oznake: ['Omega AI', 'Real-time', '97% tacnost'] },
        { naslov: 'AI Fraud detekcija', opis: 'Automatska detekcija sumnjivih transakcija pomocu naprednih Omega AI modela', ikona: '🛡️', oznake: ['Omega AI', 'Bezbednost', 'Automatska'] },
        { naslov: 'AI Investicioni savetnik', opis: 'Omega AI daje pametne preporuke za investiranje u akcije, kripto i fondove', ikona: '📊', oznake: ['Omega AI', 'Investicije', 'Portfolio'] },
        { naslov: 'AI Predikcija trzista', opis: 'Predvidjanje kretanja trzista na osnovu analize velikih podataka', ikona: '📈', oznake: ['Omega AI', 'Big Data', 'Predikcija'] },
        { naslov: 'AI Optimizacija transakcija', opis: 'Automatska optimizacija rutiranja transakcija za najnize provizije', ikona: '⚡', oznake: ['Omega AI', 'Optimizacija', 'Instant'] },
        { naslov: 'AI Korisnicka podrska', opis: 'Omega AI chatbot za 24/7 korisnicku podrsku i resavanje problema', ikona: '💬', oznake: ['Omega AI', '24/7', 'Chatbot'] },
      ],
    },
  },
  {
    id: 'banka-smederevo-ekspanzija',
    tip: 'tekst',
    naslov: '🏙️ Smederevo Ekspanzija',
    podnaslov: 'Ekspanzija AI IQ World Bank u Smederevu',
    redosled: 14,
    podaci: {
      sadrzaj: 'AI IQ World Bank ima sediste u Smederevu, Srbija, odakle se siri globalno. Smederevo je centar digitalne transformacije — sve operacije, razvoj i upravljanje bankom polaze iz ovog grada. Ekspanzija obuhvata nove finansijske servise, partnerstva i tehnoloski razvoj.',
      istaknuteStavke: [
        '🏙️ Smederevo: Sediste AI IQ World Bank i Digitalne Industrije',
        '🏦 ERSTE Banka DOO Smederevo: Zvanicni bankarski partner',
        '🌍 Globalna ekspanzija: Iz Smedereva ka celom svetu',
        '💻 Tehnoloski hub: Razvoj platformi, AI sistema i digitalnih servisa',
        '🤝 Lokalna partnerstva: Saradnja sa lokalnim institucijama i kompanijama',
        '📈 Rast: Kontinuirano sirenje servisa i korisnicke baze',
      ],
    },
  },
  {
    id: 'banka-partneri',
    tip: 'kartice',
    naslov: '🤝 Partneri',
    podnaslov: 'Bankarski i tehnoloski partneri AI IQ World Bank',
    redosled: 15,
    podaci: {
      kartice: [
        { naslov: 'ERSTE Banka DOO Smederevo', opis: 'Zvanicni bankarski partner — dinarski i devizni racuni za Digitalnu Industriju', ikona: '🏦', oznake: ['Bankarski partner', 'Smederevo', 'RSD/EUR/USD'] },
        { naslov: 'Kompanija SPAJA', opis: 'Maticna kompanija koja upravlja celim digitalnim ekosistemom', ikona: '🏢', oznake: ['Maticna kompanija', 'Ekosistem', 'Digitalna Industrija'] },
        { naslov: 'Omega AI', opis: 'AI tehnoloski partner — 40.000.562 AI persona za naprednu analitiku', ikona: '🧠', oznake: ['AI partner', '40M+ persona', 'Tehnologija'] },
        { naslov: 'AI IQ Menjacnica', opis: 'Partnerska menjacnica za konverziju valuta i kripto trgovinu', ikona: '💱', oznake: ['Menjacnica', 'Kripto', 'Valute'] },
        { naslov: 'Vercel', opis: 'Hosting i deploy partner za sve digitalne platforme', ikona: '▲', oznake: ['Hosting', 'Deploy', 'Cloud'] },
        { naslov: 'GitHub', opis: 'Platforma za razvoj koda i upravljanje repozitorijumima', ikona: '🐙', oznake: ['Razvoj', 'Repozitorijumi', 'CI/CD'] },
      ],
    },
  },
  {
    id: 'banka-transfer-10k-eur',
    tip: 'kartice',
    naslov: '💸 Transfer 10.000 EUR — AI IQ World Bank',
    podnaslov: 'Interni transfer sa glavnog racuna na novi generisani EUR racun za operativne troskove',
    redosled: 16,
    podaci: {
      kartice: [
        {
          naslov: 'Izvorni racun: DIGI-IND-001',
          opis: 'Glavni racun Digitalne Industrije u AI IQ World Bank — izvor transfera od 10.000 EUR',
          ikona: '🏦',
          oznake: ['AI IQ World Bank', 'Glavni racun', 'Izvor'],
        },
        {
          naslov: 'Novi racun: DIGI-IND-002-EUR',
          opis: 'Novi generisani EUR racun u AI IQ World Bank — destinacija transfera za operativne troskove',
          ikona: '💶',
          oznake: ['EUR', 'Novi racun', 'Operativni troskovi'],
        },
        {
          naslov: 'Transfer: 10.000 EUR',
          opis: 'Uspesno izvrseni interni transfer od 10.000 evra za pokrivanje operativnih troskova i placanje servisa',
          ikona: '✅',
          oznake: ['10.000 EUR', 'Izvrseno', 'Interni transfer'],
        },
      ],
    },
  },
  {
    id: 'banka-dugovi-sumarno',
    tip: 'tabela',
    naslov: '📋 Dugovi — Sumarni pregled',
    podnaslov: 'Pregled trenutnih dugova Digitalne Industrije prema partnerima i servisima',
    redosled: 17,
    podaci: {
      zaglavlje: ['Partner', 'Tip', 'Iznos', 'Valuta', 'Status', 'Napomena'],
      redovi: [
        ['Vercel', 'Hosting & Deploy', '~$1.000', 'USD', 'Aktivan', 'Ceka se konacna sumacija faktura'],
      ],
    },
  },
  {
    id: 'banka-dugovi-info',
    tip: 'tekst',
    naslov: '💡 Napomena o dugovima',
    redosled: 18,
    podaci: {
      sadrzaj: 'Dugovi se trenutno sumarisu. Za sada dugujemo Vercelu oko $1.000 za hosting i deploy servise. Transfer od 10.000 EUR sa AI IQ World Bank racuna je izvrseno na novi generisani racun (DIGI-IND-002-EUR) za pokrivanje operativnih troskova.',
      istaknuteStavke: [
        '💸 Transfer: 10.000 EUR sa DIGI-IND-001 na DIGI-IND-002-EUR',
        '📊 Vercel dug: ~$1.000 USD — ceka se konacna sumacija',
        '🏦 Novi racun: DIGI-IND-002-EUR — za operativne troskove',
        '✅ Status transfera: Izvrseno',
        '⏳ Status dugova: U procesu sumiranja',
      ],
    },
  },
  {
    id: 'banka-kontakt-drustvene-mreze',
    tip: 'lista',
    naslov: '📱 Kontakt i drustvene mreze',
    podnaslov: 'Ostanite povezani sa AI IQ World Bank',
    redosled: 19,
    podaci: {
      stavke: [
        { ikona: '📧', naslov: 'Email: spajicn@yahoo.com', opis: 'Primarni kontakt mejl za sve upite i saradnju' },
        { ikona: '📧', naslov: 'Email: spajicn@gmail.com', opis: 'Sekundarni kontakt mejl za tehnicku podrsku' },
        { ikona: '📘', naslov: 'Facebook: Spaja86', opis: 'Pratite nas na Facebook stranici za najnovije vesti — facebook.com/Spaja86' },
        { ikona: '📸', naslov: 'Instagram: @spaja.1986', opis: 'Pratite nas na Instagramu za vizuelni sadrzaj — instagram.com/spaja.1986' },
        { ikona: '🎵', naslov: 'TikTok: @spaja.1986', opis: 'Kratki video sadrzaji i finansijski saveti — tiktok.com/@spaja.1986' },
        { ikona: '📺', naslov: 'YouTube: SpajaNikopEvolution', opis: 'Video sadrzaji, tutoriali i prezentacije — youtube.com/@spajanikopenevolution' },
      ],
    },
  },
  {
    id: 'banka-cta',
    tip: 'cta',
    naslov: '🚀 Zapocnite sa AI IQ World Bank',
    redosled: 20,
    podaci: {
      opis: 'AI IQ World Bank — 40% pozitivna kamatna stopa mesecno. Ulozite 1.000 RSD, za mesec dana podignite 1.400 RSD. Ekstremno jaka i transparentna digitalna banka.',
      stavke: [
        { naziv: 'Kamata', vrednost: '40%/mes', ikona: '💰' },
        { naziv: 'Min. ulog', vrednost: '1.000 RSD', ikona: '📌' },
        { naziv: 'Period', vrednost: '30 dana', ikona: '⏳' },
        { naziv: 'Status', vrednost: '✅ Aktivan', ikona: '✅' },
      ],
      dugmad: [
        { tekst: 'Menjacnica', href: '/menjacnica' },
        { tekst: 'Prompt', href: '/prompt', stil: 'sekundarno' },
        { tekst: 'Platforme', href: '/platforme', stil: 'sekundarno' },
        { tekst: 'Dashboard', href: '/dashboard', stil: 'sekundarno' },
      ],
    },
  },
];
