import type { Sekvenca } from '@/lib/types';
import { OMEGA_AI_PERSONA_UKUPNO } from '@/lib/constants';

export const menjacnicaSekvence: Sekvenca[] = [
  {
    id: 'menjacnica-hero',
    tip: 'hero',
    naslov: '💱 AI IQ Menjacnica',
    podnaslov: 'Svetska menjacnica — BTC, SPAJA BTC, kripto i fiat valute sa AI predikcijama',
    ikona: '💱',
    redosled: 1,
    podaci: {
      opis: 'AI IQ Menjacnica je svetska menjacnica koja drzi kurseve svega — od klasicnog BTC-a do ekskluzivnog SPAJA BTC-a koji je mnogo skuplji od obicnog BTC-a. Podrzava kripto i fiat valute sa AI predikcijama za optimalne kurseve.',
      dugmad: [
        { tekst: 'Banka', href: '/banka' },
        { tekst: 'Platforme', href: '/platforme', stil: 'sekundarno' },
        { tekst: 'Dashboard', href: '/dashboard', stil: 'sekundarno' },
      ],
    },
  },
  {
    id: 'menjacnica-prompt-uputstvo',
    tip: 'baner',
    naslov: '📝 PROMPT — Kako koristiti AI IQ Menjacnicu',
    redosled: 2,
    podaci: {
      bedz: '📝 PROMPT UPUTSTVO',
      opis: 'AI IQ Menjacnica je svetska menjacnica koja drzi kurseve SVEGA. Ima BTC, ETH, SOL i ostale kripto valute, ali ima i ekskluzivni SPAJA BTC koji je mnogo skuplji od obicnog BTC-a! Menjacnica je ekstremno jaka — sve se moze proveriti i analizirati. Koristite Prompt za detaljne instrukcije o trgovanju.',
      dugme: { tekst: 'Prompt Sistem', href: '/prompt' },
    },
  },
  {
    id: 'menjacnica-tekst',
    tip: 'tekst',
    naslov: 'Kako radi AI IQ Menjacnica?',
    redosled: 3,
    podaci: {
      sadrzaj: 'AI IQ Menjacnica je svetska menjacnica koja koristi napredne algoritme vestacke inteligencije za analizu trzista, predikciju kurseva i automatizovano trgovanje. Posebna karakteristika je SPAJA BTC — ekskluzivna kripto valuta koja je mnogo skuplja od obicnog BTC-a. Menjacnica drzi kurseve za sve kripto i fiat valute na svetu.',
      istaknuteStavke: [
        '🪙 SPAJA BTC — ekskluzivna kripto valuta, mnogo skuplja od obicnog BTC-a',
        '₿ BTC (Bitcoin) — standardna kripto valuta sa real-time kursom',
        '🔷 ETH (Ethereum) — druga najveca kripto valuta',
        '☀️ SOL (Solana) — brza blockchain platforma',
        '💵 Fiat valute: RSD, EUR, USD, GBP, CHF, JPY i 30+ drugih',
        '🎯 AI predikcije kurseva sa 94% tacnoscu',
        '📊 Dnevni promet od $2M+',
        '🌍 Svetska menjacnica — drzi kurseve svega',
        '✅ Sve se moze proveriti i analizirati — ekstremno jaka menjacnica',
      ],
    },
  },
  {
    id: 'menjacnica-spaja-btc-baner',
    tip: 'baner',
    naslov: '🪙 SPAJA BTC — Ekskluzivna kripto valuta',
    redosled: 4,
    podaci: {
      bedz: '🪙 SPAJA BTC',
      opis: 'SPAJA BTC je ekskluzivna kripto valuta Kompanije SPAJA — mnogo skuplja od obicnog BTC-a! Dostupna iskljucivo na AI IQ Menjacnici. SPAJA BTC ima sopstveni blockchain, naprednu AI optimizaciju i garantovanu stabilnost. Svetska menjacnica drzi kurs SPAJA BTC-a 24/7.',
      dugme: { tekst: 'Banka', href: '/banka' },
    },
  },
  {
    id: 'menjacnica-kursevi-tabela',
    tip: 'tabela',
    naslov: '📋 Kursna lista — Kripto valute',
    podnaslov: 'Svetska menjacnica sa BTC, SPAJA BTC i ostalim kripto valutama',
    redosled: 5,
    podaci: {
      zaglavlje: ['Valuta', 'Simbol', 'Cena (USD)', 'Promena 24h', 'Volumen 24h', 'Market Cap'],
      redovi: [
        ['🪙 SPAJA BTC', 'SPAJA', '$892,500', '+3.8%', '$450M', '$18.7B'],
        ['₿ Bitcoin', 'BTC', '$67,450', '+2.4%', '$1.2B', '$1.32T'],
        ['🔷 Ethereum', 'ETH', '$3,820', '+1.8%', '$680M', '$459B'],
        ['☀️ Solana', 'SOL', '$185', '+5.1%', '$320M', '$82B'],
        ['🟡 BNB', 'BNB', '$612', '+1.2%', '$180M', '$94B'],
        ['🔴 Avalanche', 'AVAX', '$42', '+3.5%', '$95M', '$16B'],
        ['🟣 Polygon', 'MATIC', '$0.92', '+2.1%', '$65M', '$9.2B'],
        ['🔵 Cardano', 'ADA', '$0.65', '+1.5%', '$55M', '$23B'],
        ['⚪ USDT', 'USDT', '$1.00', '0.0%', '$5.2B', '$110B'],
        ['⚪ USDC', 'USDC', '$1.00', '0.0%', '$2.8B', '$33B'],
      ],
    },
  },
  {
    id: 'menjacnica-fiat-tabela',
    tip: 'tabela',
    naslov: '💵 Kursna lista — Fiat valute',
    podnaslov: 'Svetska menjacnica drzi kurseve svih fiat valuta',
    redosled: 6,
    podaci: {
      zaglavlje: ['Valuta', 'Kod', 'Kurs (RSD)', 'Kurs (USD)', 'Promena'],
      redovi: [
        ['🇪🇺 Evro', 'EUR', '117.15 RSD', '$1.0845', '-0.1%'],
        ['🇺🇸 Americki dolar', 'USD', '108.05 RSD', '$1.00', '0.0%'],
        ['🇬🇧 Britanska funta', 'GBP', '136.80 RSD', '$1.2660', '+0.3%'],
        ['🇨🇭 Svajcarski franak', 'CHF', '121.50 RSD', '$1.1245', '+0.1%'],
        ['🇯🇵 Japanski jen', 'JPY', '0.72 RSD', '$0.0067', '-0.2%'],
        ['🇨🇳 Kineski juan', 'CNY', '14.90 RSD', '$0.1380', '+0.1%'],
        ['🇷🇸 Srpski dinar', 'RSD', '1.00 RSD', '$0.0093', '0.0%'],
      ],
    },
  },
  {
    id: 'menjacnica-statistika',
    tip: 'statistika',
    naslov: '📊 Menjacnica u brojevima',
    redosled: 7,
    podaci: {
      stavke: [
        { naziv: 'Kripto valute', vrednost: '150+', ikona: '🪙' },
        { naziv: 'Fiat valute', vrednost: '30+', ikona: '💵' },
        { naziv: 'Dnevni promet', vrednost: '$2M+', ikona: '📊' },
        { naziv: 'AI tacnost', vrednost: '94%', ikona: '🎯' },
        { naziv: 'SPAJA BTC', vrednost: '$892K', ikona: '🪙' },
        { naziv: 'Trgovacki parovi', vrednost: '250+', ikona: '🔄' },
      ],
    },
  },
  {
    id: 'menjacnica-kartice',
    tip: 'kartice',
    naslov: '⚡ Funkcije menjacnice',
    redosled: 8,
    podaci: {
      kartice: [
        { naslov: 'SPAJA BTC', opis: 'Ekskluzivna kripto valuta — mnogo skuplja od obicnog BTC-a. Sopstveni blockchain, AI optimizacija, garantovana stabilnost.', ikona: '🪙', oznake: ['Ekskluzivno', 'Premium', 'AI'] },
        { naslov: 'Kripto Trading', opis: 'Kupovina i prodaja kriptovaluta — BTC, ETH, SOL, AVAX i 150+ drugih', ikona: '₿', oznake: ['BTC', 'ETH', 'SOL', 'USDT'] },
        { naslov: 'Fiat Konverzija', opis: 'Menjanje fiat valuta po najboljim kursevima — svetska menjacnica', ikona: '💵', oznake: ['EUR', 'USD', 'GBP', 'RSD'] },
        { naslov: 'Portfolio', opis: 'Upravljanje portfoliom sa AI asistentom — automatsko balansiranje', ikona: '📊', oznake: ['Balansiranje', 'Diverzifikacija', 'AI'] },
        { naslov: 'AI Predikcije', opis: 'Predvidjanje trzisnih trendova sa 94% tacnoscu', ikona: '🎯', oznake: ['ML modeli', 'Sentiment analiza', '94%'] },
        { naslov: 'Analitika', opis: 'Sve se moze proveriti i analizirati — ekstremno jaka menjacnica', ikona: '🔍', oznake: ['Real-time', 'Transparentnost', 'Analiza'] },
      ],
    },
  },
  {
    id: 'menjacnica-prompt-trgovanje',
    tip: 'lista',
    naslov: '📝 PROMPT — Kako trgovati na AI IQ Menjacnici',
    redosled: 9,
    podaci: {
      stavke: [
        { ikona: '1️⃣', naslov: 'Registracija', opis: 'Otvorite nalog na AI IQ Menjacnici — besplatna registracija' },
        { ikona: '2️⃣', naslov: 'Verifikacija', opis: 'Verifikujte identitet za puno koriscenje svih funkcija' },
        { ikona: '3️⃣', naslov: 'Deponujte sredstva', opis: 'Uplatite RSD, EUR, USD ili kripto valute na svoj nalog' },
        { ikona: '4️⃣', naslov: 'Izaberite valutni par', opis: 'Izaberite par za trgovanje: BTC/USDT, SPAJA/BTC, EUR/USD itd.' },
        { ikona: '5️⃣', naslov: 'Koristite AI predikcije', opis: 'AI sistem predvidja kretanje kurseva sa 94% tacnoscu' },
        { ikona: '6️⃣', naslov: 'Trgujte', opis: 'Kupujte i prodajte po najboljim kursevima u realnom vremenu' },
        { ikona: '🪙', naslov: 'SPAJA BTC', opis: 'Ekskluzivna valuta — mnogo skuplja od BTC-a, dostupna samo na AI IQ Menjacnici' },
        { ikona: '✅', naslov: 'Verifikacija', opis: 'Sve se moze proveriti i analizirati — ekstremno jaka menjacnica' },
      ],
    },
  },
  {
    id: 'menjacnica-prompt-spaja-btc',
    tip: 'tekst',
    naslov: '📝 PROMPT — Sta je SPAJA BTC?',
    redosled: 10,
    podaci: {
      sadrzaj: 'SPAJA BTC je ekskluzivna kripto valuta Kompanije SPAJA. Ona je mnogo skuplja od obicnog BTC-a jer koristi napredni SPAJA blockchain sa AI optimizacijom, garantovanu stabilnost i premium bezbednost. SPAJA BTC je dostupna iskljucivo na AI IQ Menjacnici.',
      istaknuteStavke: [
        '🪙 SPAJA BTC trenutna cena: $892,500 — mnogo skuplje od BTC ($67,450)',
        '🔗 Sopstveni SPAJA Blockchain sa AI optimizacijom',
        '🛡️ Garantovana stabilnost i premium bezbednost',
        '🏢 Ekskluzivno na AI IQ Menjacnici — Kompanija SPAJA',
        '📈 AI optimizovane transakcije i predikcije',
        '🌍 Globalno dostupan za trgovanje 24/7',
        '✅ Sve se moze proveriti i analizirati',
      ],
    },
  },
  {
    id: 'menjacnica-trading-platforma',
    tip: 'kartice',
    naslov: '📊 Trading Platforma',
    podnaslov: 'Profesionalna trading platforma sa Order Book, Canvas Chart i Buy/Sell formama',
    redosled: 11,
    podaci: {
      kartice: [
        { naslov: 'Order Book', opis: 'Live Order Book sa asks/bids prikazom i vizuelnim bar indikatorima — praćenje dubine tržišta u realnom vremenu', ikona: '📖', oznake: ['Live', 'Asks/Bids', 'Real-time'] },
        { naslov: 'Canvas Price Chart', opis: 'Simulirani real-time grafikon cena na HTML5 Canvas — vremenski okviri 1m, 5m, 15m, 1h, 4h, 1d', ikona: '📈', oznake: ['Canvas API', 'Timeframes', 'Live'] },
        { naslov: 'Buy/Sell forma', opis: 'Limit, Market i Stop narudžbine sa kalkulacijom ukupne cene i 0.2% naknade', ikona: '🛒', oznake: ['Limit', 'Market', 'Stop'] },
        { naslov: 'Coin Selector', opis: 'Brzi izbor trading parova — BTC/USD, ETH/USD, SOL/USD, BNB/USD sa live cenama', ikona: '🪙', oznake: ['BTC', 'ETH', 'SOL', 'BNB'] },
        { naslov: 'P&L Kalkulator', opis: 'Izracunajte profit ili gubitak pre trgovanja — unos cene kupovine, prodaje i kolicine', ikona: '🧮', oznake: ['Profit', 'Loss', 'Kalkulator'] },
        { naslov: 'Trade History', opis: 'Istorija transakcija u realnom vremenu sa cenama, kolicinama i vremenskim oznakama', ikona: '📋', oznake: ['Istorija', 'Real-time', 'Log'] },
      ],
    },
  },
  {
    id: 'menjacnica-ai-predikcija',
    tip: 'kartice',
    naslov: '🤖 AI Predikcija i Sentiment Analiza',
    podnaslov: 'Omega AI modeli za predvidjanje kretanja cena i analizu trzisnog sentimenta',
    redosled: 12,
    podaci: {
      kartice: [
        { naslov: 'AI Predikcija 1h', opis: 'Kratkorocno predvidjanje kretanja cena u narednih 60 minuta sa 74% sigurnosti', ikona: '🔮', oznake: ['1h', '74% sigurno', 'Kratkorocno'] },
        { naslov: 'AI Predikcija 4h', opis: 'Srednorocno predvidjanje kretanja cena u naredna 4 sata sa 68% sigurnosti', ikona: '🔮', oznake: ['4h', '68% sigurno', 'Srednje'] },
        { naslov: 'AI Predikcija 24h', opis: 'Dugorocno predvidjanje kretanja cena u naredna 24 sata sa 61% sigurnosti', ikona: '🔮', oznake: ['24h', '61% sigurno', 'Dugorocno'] },
        { naslov: 'Bullish Sentiment', opis: 'Pracenje pozitivnog sentimenta na drustvenim mrezama, vestima i on-chain podacima', ikona: '🐂', oznake: ['Bullish', '~65%', 'Pozitivan'] },
        { naslov: 'Bearish Sentiment', opis: 'Pracenje negativnog sentimenta i upozorenja na moguce padove trzista', ikona: '🐻', oznake: ['Bearish', '~13%', 'Upozorenje'] },
        { naslov: 'Smart DCA Bot', opis: 'Automatizovano Dollar-Cost Averaging sa AI optimizacijom ulaznih tacaka', ikona: '📈', oznake: ['DCA', 'Automatski', 'AI Bot'] },
      ],
    },
  },
  {
    id: 'menjacnica-novcenik',
    tip: 'kartice',
    naslov: '💼 Kripto Novcanik',
    podnaslov: 'Multi-valutni portfolio sa real-time pracenjem i Canvas pie chart alokacijom',
    redosled: 13,
    podaci: {
      kartice: [
        { naslov: 'Portfolio Pregled', opis: 'Ukupna vrednost portfolia sa procentualnom promenom — sve na jednom mestu', ikona: '💰', oznake: ['Ukupno', 'Real-time', 'Promena'] },
        { naslov: 'Pie Chart Alokacija', opis: 'Vizuelni prikaz alokacije portfolia po kriptovalutama — Canvas grafikon', ikona: '📊', oznake: ['BTC ~67%', 'ETH ~31%', 'SOL ~1%'] },
        { naslov: 'Lista Aktive', opis: 'Detaljna lista svih kriptovaluta u portfoliu sa kolicinama i vrednostima', ikona: '📋', oznake: ['Kolicina', 'Vrednost', 'Promena'] },
        { naslov: 'Istorija Transakcija', opis: 'Kompletna istorija svih transakcija — kupovine, prodaje, transferi sa statusom', ikona: '📜', oznake: ['Kupovina', 'Prodaja', 'Transfer'] },
        { naslov: 'Brze Akcije', opis: 'Kupi, posalji i primi kripto direktno iz novcanika — brze akcije na jednom mestu', ikona: '⚡', oznake: ['Kupi', 'Posalji', 'Primi'] },
        { naslov: 'Uplata/Isplata', opis: 'Deponujte i povucite sredstva — RSD, EUR, USD ili kripto valute', ikona: '💳', oznake: ['Uplata', 'Isplata', 'Multi-valuta'] },
      ],
    },
  },
  {
    id: 'menjacnica-edukacija',
    tip: 'lista',
    naslov: '🎓 Kripto Edukacija',
    podnaslov: 'Naucite osnove kriptovaluta, blockchain tehnologije i AI u kriptu',
    redosled: 14,
    podaci: {
      stavke: [
        { ikona: '₿', naslov: 'Sta je Bitcoin?', opis: 'Prva decentralizovana digitalna valuta — Satoshi Nakamoto, 21 milion BTC, digitalno zlato, peer-to-peer mreza bez centralne banke' },
        { ikona: '🔷', naslov: 'Sta je Ethereum?', opis: 'Programibilni blockchain za pametne ugovore — Vitalik Buterin, DeFi, NFT, DAOs, Layer 2, Proof of Stake' },
        { ikona: '🏗️', naslov: 'Kako radi Blockchain?', opis: 'Distribuirana baza podataka — transakcija, broadcast, validacija, blok, konsenzus (PoW/PoS), lanac sa hash-evima' },
        { ikona: '🏦', naslov: 'Sta je DeFi?', opis: 'Decentralizovane finansije — DEX (Uniswap), Lending (Aave), Yield Farming, Staking, Stablecoins' },
        { ikona: '🤖', naslov: 'AI u Kriptu', opis: 'Prediktivna analiza cena, automatski rebalansing portfolia, sentiment analiza, otkrivanje prevara, Smart DCA Bot' },
        { ikona: '🔐', naslov: 'Sigurnost Novcanika', opis: 'Privatni kljuc, seed phrase (12/24 reci), hardware wallet (Ledger/Trezor), 2FA, phishing zastita, backup' },
      ],
    },
  },
  {
    id: 'menjacnica-usluge-planovi',
    tip: 'kartice',
    naslov: '🔧 Usluge i Planovi',
    podnaslov: '9 profesionalnih usluga sa 3 plana — Starter (besplatno), Pro ($29/mes), Enterprise (custom)',
    redosled: 15,
    podaci: {
      kartice: [
        { naslov: 'Kripto Trading', opis: '500+ kriptovaluta sa naprednom platformom — real-time order book, chart analiza, 0.2% naknada', ikona: '💱', oznake: ['500+', '0.2%', 'Real-time'] },
        { naslov: 'AI Inteligencija', opis: 'AI-powered uvidi, automatizovane trading strategije, prediktivna analiza, sentiment', ikona: '🤖', oznake: ['AI', 'Strategije', 'Premium'] },
        { naslov: 'Enterprise Security', opis: '2FA, end-to-end enkripcija, cold storage zastita — bank-level sigurnost besplatno', ikona: '🔒', oznake: ['2FA', 'E2E', 'Cold Storage'] },
        { naslov: 'Siguran Novcanik', opis: 'Multi-valutni kripto novcanik sa portfolio pracenjem i pie chart alokacijom', ikona: '💼', oznake: ['Multi-valuta', 'Portfolio', 'Besplatno'] },
        { naslov: 'Market Analiza', opis: 'AI analiza trzista sa prediktivnim modelima i tehnickim indikatorima', ikona: '📊', oznake: ['AI', 'Big Data', 'Premium'] },
        { naslov: 'AI Konsalting', opis: 'Strucne smernice za implementaciju AI resenja — od strategije do tehnicke implementacije', ikona: '🤖', oznake: ['Konsalting', 'Strategija', 'Kontakt'] },
        { naslov: 'Razmena Valuta', opis: 'Brza razmena kripto i fiat valuta (EUR/RSD/USD) — minimalne naknade od 0.5%', ikona: '💱', oznake: ['EUR', 'RSD', '0.5%'] },
        { naslov: 'Copy Trading', opis: 'Automatski kopirajte trejdove uspesnih tradere — ideal za pocetnike', ikona: '📈', oznake: ['Copy', 'Auto', 'Premium'] },
        { naslov: 'Edukacija', opis: 'Kompletni edukativni resursi o kriptu, blockchain-u i AI — besplatno', ikona: '🎓', oznake: ['Besplatno', 'Kviz', 'Materijali'] },
      ],
    },
  },
  {
    id: 'menjacnica-cenovnik',
    tip: 'tabela',
    naslov: '💎 Planovi i Cene',
    podnaslov: 'Starter (besplatno), Pro ($29/mes), Enterprise (custom)',
    redosled: 16,
    podaci: {
      zaglavlje: ['Plan', 'Cena', 'Naknada', 'AI Predikcija', 'Copy Trading', 'Konsalting', 'Podrska'],
      redovi: [
        ['🆓 Starter', '$0/mes', '0.2%', '❌', '❌', '❌', 'Basic'],
        ['💎 Pro', '$29/mes', '0.1% (50% popust)', '✅', '✅', '❌', 'Napredna'],
        ['🏆 Enterprise', 'Custom', '0%', '✅', '✅', '✅', '24/7 Prioritetna'],
      ],
    },
  },
  {
    id: 'menjacnica-o-nama-tim',
    tip: 'kartice',
    naslov: '👥 O nama — Tim AI IQ Menjacnice',
    podnaslov: 'Posveceni profesionalci koji grade buducnost kripto finansija — osnivanje 2020',
    redosled: 17,
    podaci: {
      kartice: [
        { naslov: 'Nikola Spajic', opis: 'Osnivac & CEO — vizionar kripto industrije i AI entuzijasta. Vodi razvoj platforme od osnivanja 2020. godine.', ikona: '🧑‍💻', oznake: ['CEO', 'Osnivac', '2020'] },
        { naslov: 'AI Tim', opis: 'Razvija napredne AI modele za predvidjanje cena, otkrivanje prevara i automatizovano trejdovanje', ikona: '🤖', oznake: ['AI', 'ML', 'Predikcija'] },
        { naslov: 'Security Tim', opis: 'Garantuje bank-level sigurnost sa 2FA, enkripcijom podataka i cold storage zastitom sredstava', ikona: '🔒', oznake: ['2FA', 'Enkripcija', 'Cold Storage'] },
        { naslov: 'Trading Tim', opis: 'Trzisni analiticari koji prate kripto trendove i razvijaju trading strategije za korisnike', ikona: '📊', oznake: ['Analitika', 'Trendovi', 'Strategija'] },
      ],
    },
  },
  {
    id: 'menjacnica-vrednosti',
    tip: 'lista',
    naslov: '💡 Nase Vrednosti',
    podnaslov: 'Principi na kojima je izgradjena AI IQ Menjacnica',
    redosled: 18,
    podaci: {
      stavke: [
        { ikona: '🔐', naslov: 'Sigurnost na prvom mestu', opis: 'Vasa sredstva su pod zastitom najnaprednije sigurnosne infrastrukture — cold storage, multi-sig, 2FA' },
        { ikona: '🌍', naslov: 'Globalna dostupnost', opis: 'Platforma dostupna u 190+ zemalja sa podrskom za lokalne valute i jezike' },
        { ikona: '📱', naslov: 'Inovacija i tehnologija', opis: 'Neprestano ulazemo u AI i blockchain tehnologiju za bolji trading dozivljaj' },
        { ikona: '🎓', naslov: 'Edukacija korisnika', opis: 'Verujemo da je znanje moc — edukujemo korisnike o kriptu, DeFi i blockchain tehnologiji' },
      ],
    },
  },
  {
    id: 'menjacnica-kontakt-drustvene-mreze',
    tip: 'lista',
    naslov: '📱 Kontakt i drustvene mreze',
    podnaslov: 'Ostanite povezani sa AI IQ Menjaenicom - odgovaramo u roku od 24 sata',
    redosled: 19,
    podaci: {
      stavke: [
        { ikona: '📧', naslov: 'Email: spajicn@yahoo.com', opis: 'Primarni kontakt mejl za sve upite, trading pitanja i poslovnu saradnju' },
        { ikona: '📧', naslov: 'Email: spajicn@gmail.com', opis: 'Sekundarni kontakt mejl za tehnicku podrsku i sigurnosna pitanja' },
        { ikona: '📘', naslov: 'Facebook: Spaja86', opis: 'Pratite nas na Facebook-u za najnovije vesti — facebook.com/Spaja86' },
        { ikona: '📸', naslov: 'Instagram: @spaja.1986', opis: 'Pratite nas na Instagramu za vizuelni sadrzaj — instagram.com/spaja.1986' },
        { ikona: '🎵', naslov: 'TikTok: @spaja.1986', opis: 'Kratki video sadrzaji i kripto saveti — tiktok.com/@spaja.1986' },
        { ikona: '📺', naslov: 'YouTube: SpajaNikopEvolution', opis: 'Video tutoriali, trading strategije i analize — youtube.com/@spajanikopenevolution' },
      ],
    },
  },
  {
    id: 'menjacnica-banka-integracija',
    tip: 'tekst',
    naslov: '🏦 Integracija sa AI IQ World Bank',
    podnaslov: 'Menjacnica i Banka — savrseno drustvo za finansije',
    redosled: 20,
    podaci: {
      sadrzaj: 'AI IQ Menjacnica i AI IQ World Bank rade zajedno kao savrseni finansijski ekosistem. Menjacnica sluzi za kripto i fiat konverziju sa AI predikcijama, dok banka nudi stedne racune sa 40% kamatom, kredite i investiciono upravljanje. Oba sistema koriste ERSTE Banka DOO Smederevo za dinarske i devizne racune.',
      istaknuteStavke: [
        '💱 Menjacnica: Kripto i fiat konverzija sa AI predikcijama (94% tacnost)',
        '🏦 Banka: Stedni racuni sa 40% pozitivnom kamatnom stopom',
        '🏦 ERSTE Banka DOO Smederevo: Zajednicki bankarski partner',
        '💵 Podrzane valute: RSD, EUR, USD + 500+ kripto valuta',
        `🤖 Omega AI: Zajednicki AI motor sa ${OMEGA_AI_PERSONA_UKUPNO.toLocaleString('sr-Latn')} persona`,
        '🔄 Instant konverzija: Prebacivanje izmedju banke i menjacnice bez provizije',
        '📧 Profesionalni mejl: @banka.spaja.rs i @spaja.rs domeni za notifikacije',
      ],
    },
  },
  {
    id: 'menjacnica-statistika-prosireno',
    tip: 'statistika',
    naslov: '📊 Kompletna statistika platforme',
    redosled: 21,
    podaci: {
      stavke: [
        { naziv: 'Kripto valute', vrednost: '500+', ikona: '🪙' },
        { naziv: 'Fiat valute', vrednost: '30+', ikona: '💵' },
        { naziv: 'Korisnici', vrednost: '10M+', ikona: '👥' },
        { naziv: 'Zemalja', vrednost: '190+', ikona: '🌍' },
        { naziv: 'Dnevni promet', vrednost: '$100B+', ikona: '📊' },
        { naziv: 'Uptime', vrednost: '99.9%', ikona: '⏰' },
      ],
    },
  },
  {
    id: 'menjacnica-cta',
    tip: 'cta',
    naslov: '🚀 Pocnite trgovanje na svetskoj menjacnici',
    redosled: 22,
    podaci: {
      opis: 'AI IQ Menjacnica — svetska menjacnica sa BTC, SPAJA BTC i 500+ kripto valuta. Drzi kurseve svega. AI predikcije sa 94% tacnoscu. 10M+ korisnika u 190+ zemalja. Ekstremno jaka menjacnica — sve se moze proveriti.',
      stavke: [
        { naziv: 'SPAJA BTC', vrednost: '$892K', ikona: '🪙' },
        { naziv: 'BTC', vrednost: '$67,450', ikona: '₿' },
        { naziv: 'Kripto', vrednost: '500+', ikona: '🔄' },
        { naziv: 'AI tacnost', vrednost: '94%', ikona: '🎯' },
        { naziv: 'Korisnici', vrednost: '10M+', ikona: '👥' },
        { naziv: 'Zemalja', vrednost: '190+', ikona: '🌍' },
      ],
      dugmad: [
        { tekst: 'Banka', href: '/banka' },
        { tekst: 'Prompt', href: '/prompt', stil: 'sekundarno' },
        { tekst: 'Platforme', href: '/platforme', stil: 'sekundarno' },
        { tekst: 'Dashboard', href: '/dashboard', stil: 'sekundarno' },
      ],
    },
  },
];
