import type { Sekvenca } from '@/lib/types';

export const menjacnicaSekvence: Sekvenca[] = [
  {
    id: 'menjacnica-hero',
    tip: 'hero',
    naslov: '💱 AI IQ Menjacnica',
    podnaslov: 'Svetska menjacnica — BTC, SPAJA BTC, kripto i fiat valute sa AI predikcijama',
    ikona: '💱',
    redosled: 1,
    podaci: {
      opis: 'AI IQ Menjacnica je svetska menjacnica koja drzi kurseve svega — od klasicnog BTC-a do ekskluzivnog SPAJA BTC-a koji je mnogo skuplji od obicnog BTC-a. Podrzava kripto i fiat valute sa AI predikcijama za optimalne kurseve.',
      dugmad: [
        { tekst: 'Banka', href: '/banka' },
        { tekst: 'Platforme', href: '/platforme', stil: 'sekundarno' },
        { tekst: 'Dashboard', href: '/dashboard', stil: 'sekundarno' },
      ],
    },
  },
  {
    id: 'menjacnica-prompt-uputstvo',
    tip: 'baner',
    naslov: '📝 PROMPT — Kako koristiti AI IQ Menjacnicu',
    redosled: 2,
    podaci: {
      bedz: '📝 PROMPT UPUTSTVO',
      opis: 'AI IQ Menjacnica je svetska menjacnica koja drzi kurseve SVEGA. Ima BTC, ETH, SOL i ostale kripto valute, ali ima i ekskluzivni SPAJA BTC koji je mnogo skuplji od obicnog BTC-a! Menjacnica je ekstremno jaka — sve se moze proveriti i analizirati. Koristite Prompt za detaljne instrukcije o trgovanju.',
      dugme: { tekst: 'Prompt Sistem', href: '/prompt' },
    },
  },
  {
    id: 'menjacnica-tekst',
    tip: 'tekst',
    naslov: 'Kako radi AI IQ Menjacnica?',
    redosled: 3,
    podaci: {
      sadrzaj: 'AI IQ Menjacnica je svetska menjacnica koja koristi napredne algoritme vestacke inteligencije za analizu trzista, predikciju kurseva i automatizovano trgovanje. Posebna karakteristika je SPAJA BTC — ekskluzivna kripto valuta koja je mnogo skuplja od obicnog BTC-a. Menjacnica drzi kurseve za sve kripto i fiat valute na svetu.',
      istaknuteStavke: [
        '🪙 SPAJA BTC — ekskluzivna kripto valuta, mnogo skuplja od obicnog BTC-a',
        '₿ BTC (Bitcoin) — standardna kripto valuta sa real-time kursom',
        '🔷 ETH (Ethereum) — druga najveca kripto valuta',
        '☀️ SOL (Solana) — brza blockchain platforma',
        '💵 Fiat valute: RSD, EUR, USD, GBP, CHF, JPY i 30+ drugih',
        '🎯 AI predikcije kurseva sa 94% tacnoscu',
        '📊 Dnevni promet od $2M+',
        '🌍 Svetska menjacnica — drzi kurseve svega',
        '✅ Sve se moze proveriti i analizirati — ekstremno jaka menjacnica',
      ],
    },
  },
  {
    id: 'menjacnica-spaja-btc-baner',
    tip: 'baner',
    naslov: '🪙 SPAJA BTC — Ekskluzivna kripto valuta',
    redosled: 4,
    podaci: {
      bedz: '🪙 SPAJA BTC',
      opis: 'SPAJA BTC je ekskluzivna kripto valuta Kompanije SPAJA — mnogo skuplja od obicnog BTC-a! Dostupna iskljucivo na AI IQ Menjacnici. SPAJA BTC ima sopstveni blockchain, naprednu AI optimizaciju i garantovanu stabilnost. Svetska menjacnica drzi kurs SPAJA BTC-a 24/7.',
      dugme: { tekst: 'Banka', href: '/banka' },
    },
  },
  {
    id: 'menjacnica-kursevi-tabela',
    tip: 'tabela',
    naslov: '📋 Kursna lista — Kripto valute',
    podnaslov: 'Svetska menjacnica sa BTC, SPAJA BTC i ostalim kripto valutama',
    redosled: 5,
    podaci: {
      zaglavlje: ['Valuta', 'Simbol', 'Cena (USD)', 'Promena 24h', 'Volumen 24h', 'Market Cap'],
      redovi: [
        ['🪙 SPAJA BTC', 'SPAJA', '$892,500', '+3.8%', '$450M', '$18.7B'],
        ['₿ Bitcoin', 'BTC', '$67,450', '+2.4%', '$1.2B', '$1.32T'],
        ['🔷 Ethereum', 'ETH', '$3,820', '+1.8%', '$680M', '$459B'],
        ['☀️ Solana', 'SOL', '$185', '+5.1%', '$320M', '$82B'],
        ['🟡 BNB', 'BNB', '$612', '+1.2%', '$180M', '$94B'],
        ['🔴 Avalanche', 'AVAX', '$42', '+3.5%', '$95M', '$16B'],
        ['🟣 Polygon', 'MATIC', '$0.92', '+2.1%', '$65M', '$9.2B'],
        ['🔵 Cardano', 'ADA', '$0.65', '+1.5%', '$55M', '$23B'],
        ['⚪ USDT', 'USDT', '$1.00', '0.0%', '$5.2B', '$110B'],
        ['⚪ USDC', 'USDC', '$1.00', '0.0%', '$2.8B', '$33B'],
      ],
    },
  },
  {
    id: 'menjacnica-fiat-tabela',
    tip: 'tabela',
    naslov: '💵 Kursna lista — Fiat valute',
    podnaslov: 'Svetska menjacnica drzi kurseve svih fiat valuta',
    redosled: 6,
    podaci: {
      zaglavlje: ['Valuta', 'Kod', 'Kurs (RSD)', 'Kurs (USD)', 'Promena'],
      redovi: [
        ['🇪🇺 Evro', 'EUR', '117.15 RSD', '$1.0845', '-0.1%'],
        ['🇺🇸 Americki dolar', 'USD', '108.05 RSD', '$1.00', '0.0%'],
        ['🇬🇧 Britanska funta', 'GBP', '136.80 RSD', '$1.2660', '+0.3%'],
        ['🇨🇭 Svajcarski franak', 'CHF', '121.50 RSD', '$1.1245', '+0.1%'],
        ['🇯🇵 Japanski jen', 'JPY', '0.72 RSD', '$0.0067', '-0.2%'],
        ['🇨🇳 Kineski juan', 'CNY', '14.90 RSD', '$0.1380', '+0.1%'],
        ['🇷🇸 Srpski dinar', 'RSD', '1.00 RSD', '$0.0093', '0.0%'],
      ],
    },
  },
  {
    id: 'menjacnica-statistika',
    tip: 'statistika',
    naslov: '📊 Menjacnica u brojevima',
    redosled: 7,
    podaci: {
      stavke: [
        { naziv: 'Kripto valute', vrednost: '150+', ikona: '🪙' },
        { naziv: 'Fiat valute', vrednost: '30+', ikona: '💵' },
        { naziv: 'Dnevni promet', vrednost: '$2M+', ikona: '📊' },
        { naziv: 'AI tacnost', vrednost: '94%', ikona: '🎯' },
        { naziv: 'SPAJA BTC', vrednost: '$892K', ikona: '🪙' },
        { naziv: 'Trgovacki parovi', vrednost: '250+', ikona: '🔄' },
      ],
    },
  },
  {
    id: 'menjacnica-kartice',
    tip: 'kartice',
    naslov: '⚡ Funkcije menjacnice',
    redosled: 8,
    podaci: {
      kartice: [
        { naslov: 'SPAJA BTC', opis: 'Ekskluzivna kripto valuta — mnogo skuplja od obicnog BTC-a. Sopstveni blockchain, AI optimizacija, garantovana stabilnost.', ikona: '🪙', oznake: ['Ekskluzivno', 'Premium', 'AI'] },
        { naslov: 'Kripto Trading', opis: 'Kupovina i prodaja kriptovaluta — BTC, ETH, SOL, AVAX i 150+ drugih', ikona: '₿', oznake: ['BTC', 'ETH', 'SOL', 'USDT'] },
        { naslov: 'Fiat Konverzija', opis: 'Menjanje fiat valuta po najboljim kursevima — svetska menjacnica', ikona: '💵', oznake: ['EUR', 'USD', 'GBP', 'RSD'] },
        { naslov: 'Portfolio', opis: 'Upravljanje portfoliom sa AI asistentom — automatsko balansiranje', ikona: '📊', oznake: ['Balansiranje', 'Diverzifikacija', 'AI'] },
        { naslov: 'AI Predikcije', opis: 'Predvidjanje trzisnih trendova sa 94% tacnoscu', ikona: '🎯', oznake: ['ML modeli', 'Sentiment analiza', '94%'] },
        { naslov: 'Analitika', opis: 'Sve se moze proveriti i analizirati — ekstremno jaka menjacnica', ikona: '🔍', oznake: ['Real-time', 'Transparentnost', 'Analiza'] },
      ],
    },
  },
  {
    id: 'menjacnica-prompt-trgovanje',
    tip: 'lista',
    naslov: '📝 PROMPT — Kako trgovati na AI IQ Menjacnici',
    redosled: 9,
    podaci: {
      stavke: [
        { ikona: '1️⃣', naslov: 'Registracija', opis: 'Otvorite nalog na AI IQ Menjacnici — besplatna registracija' },
        { ikona: '2️⃣', naslov: 'Verifikacija', opis: 'Verifikujte identitet za puno koriscenje svih funkcija' },
        { ikona: '3️⃣', naslov: 'Deponujte sredstva', opis: 'Uplatite RSD, EUR, USD ili kripto valute na svoj nalog' },
        { ikona: '4️⃣', naslov: 'Izaberite valutni par', opis: 'Izaberite par za trgovanje: BTC/USDT, SPAJA/BTC, EUR/USD itd.' },
        { ikona: '5️⃣', naslov: 'Koristite AI predikcije', opis: 'AI sistem predvidja kretanje kurseva sa 94% tacnoscu' },
        { ikona: '6️⃣', naslov: 'Trgujte', opis: 'Kupujte i prodajte po najboljim kursevima u realnom vremenu' },
        { ikona: '🪙', naslov: 'SPAJA BTC', opis: 'Ekskluzivna valuta — mnogo skuplja od BTC-a, dostupna samo na AI IQ Menjacnici' },
        { ikona: '✅', naslov: 'Verifikacija', opis: 'Sve se moze proveriti i analizirati — ekstremno jaka menjacnica' },
      ],
    },
  },
  {
    id: 'menjacnica-prompt-spaja-btc',
    tip: 'tekst',
    naslov: '📝 PROMPT — Sta je SPAJA BTC?',
    redosled: 10,
    podaci: {
      sadrzaj: 'SPAJA BTC je ekskluzivna kripto valuta Kompanije SPAJA. Ona je mnogo skuplja od obicnog BTC-a jer koristi napredni SPAJA blockchain sa AI optimizacijom, garantovanu stabilnost i premium bezbednost. SPAJA BTC je dostupna iskljucivo na AI IQ Menjacnici.',
      istaknuteStavke: [
        '🪙 SPAJA BTC trenutna cena: $892,500 — mnogo skuplje od BTC ($67,450)',
        '🔗 Sopstveni SPAJA Blockchain sa AI optimizacijom',
        '🛡️ Garantovana stabilnost i premium bezbednost',
        '🏢 Ekskluzivno na AI IQ Menjacnici — Kompanija SPAJA',
        '📈 AI optimizovane transakcije i predikcije',
        '🌍 Globalno dostupan za trgovanje 24/7',
        '✅ Sve se moze proveriti i analizirati',
      ],
    },
  },
  {
    id: 'menjacnica-cta',
    tip: 'cta',
    naslov: '🚀 Pocnite trgovanje na svetskoj menjacnici',
    redosled: 11,
    podaci: {
      opis: 'AI IQ Menjacnica — svetska menjacnica sa BTC, SPAJA BTC i 150+ kripto valuta. Drzi kurseve svega. AI predikcije sa 94% tacnoscu. Ekstremno jaka menjacnica — sve se moze proveriti.',
      stavke: [
        { naziv: 'SPAJA BTC', vrednost: '$892K', ikona: '🪙' },
        { naziv: 'BTC', vrednost: '$67,450', ikona: '₿' },
        { naziv: 'Kripto', vrednost: '150+', ikona: '🔄' },
        { naziv: 'AI tacnost', vrednost: '94%', ikona: '🎯' },
      ],
      dugmad: [
        { tekst: 'Banka', href: '/banka' },
        { tekst: 'Prompt', href: '/prompt', stil: 'sekundarno' },
        { tekst: 'Platforme', href: '/platforme', stil: 'sekundarno' },
        { tekst: 'Dashboard', href: '/dashboard', stil: 'sekundarno' },
      ],
    },
  },
];
